seL4/l4v

- lib/NonDetMonadLemmaBucket.thy
- proof/invariant-abstract/ARM/ArchVSpace_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchVSpace_AI.thy
- proof/invariant-abstract/RISCV64/ArchVSpace_AI.thy
- proof/invariant-abstract/VSpacePre_AI.thy
- proof/invariant-abstract/X64/ArchVSpace_AI.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/TcbAcc_R.thy
This extends typ_at_lifts to also handle the negated versions. As part of this it produces two different formulations of the lifting lemmas, using ML_goal instead of manually duplicating all of them.
> mcs: strengthen typ_at_lifts

- proof/tests.xml
Github runners are fairly slow; give them more time.
> bump timeout

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/ObjectType.lhs
- spec/haskell/src/SEL4/Object/Reply.lhs
This updates Haskell replyUnlink, replyRemove, replyPop, and replyClear to take a tcb ref argument, which should be appropriately linked to the first argument.
This corresponds to the C change in seL4 [PR#1808](https://bitbucket.ts.data61.csiro.au/projects/SEL4/repos/sel4/pull-requests/1808/overview) (on the internal bitbucket).
> Add tcb arg to replyUnlink etc.

- proof/refine/ARM/ADT_H.thy
- proof/refine/ARM/CSpace1_R.thy
- proof/refine/ARM/CSpace_R.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/StateRelation.thy
This commits flips the traversal direction of `sc_replies_relation`, to follow the `replyPrev` links instead of the `replyNext` links.
This means that we have the following:
- `reply_relation reply reply'` gives `reply_sc reply = replySc reply’”
- `sc_replies_relation s s'` gives 1)`hd (sc_replies sc) = scReply sc’`; and 2) `sc_replies sc` equals to the `replyPrev` traversal of the linked list starting from `scReply sc’`
- we need `sym_refs (list_refs_of_replies’ s') to know that the `replyNext` traversal matches the `replyPrev` traversal
This is a minimal and necessary change to `sc_replies_relation` (meaning this should be merged). 
There is also a question of whether it helps or makes it more painful to include the “Next” traversal in the relation or not. My plan is to experiment a bit …
> sc replies relation

- lib/Monad_WP/OptionMonad.thy
- proof/refine/ARM/StateRelation.thy
This adds a few lemmas about `replyPrev` and `replyNext`.
This also adds opt_map_SomeD, which is
```
lemma opt_map_SomeD:
"f x = Some y \<Longrightarrow> (f |> g) x = g y"
```
and it might be good to add this to the simp set. But that requires some work to fix proofs, so I haven’t done that yet.
I think it makes sense because, for `opt_map` and `Some`, it seems that we currently only have lemmas for cases where the whole computation returns `Some`, but even without that knowledge we should be able to proceed with the computation from the inside if we know enough to do so. Currently, if we want to do that, we effectively have to unfold `opt_map` which is often less than ideal typically because you have other `opt_map`s in the subgoal that you’d rather not unfold. Let me know if I am …
> Rt sc replies relation #2

- lib/Corres_UL.thy
- lib/HaskellLemmaBucket.thy
- lib/HaskellLib_H.thy
- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- spec/design/skel/KernelStateData_H.thy
- spec/haskell/src/SEL4/Model/PSpace.lhs
- spec/haskell/src/SEL4/Model/Preemption.lhs
- spec/haskell/src/SEL4/Model/StateData.lhs
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/ObjectType.lhs
This PR removes sym_refs (state_refs_of' s) from invs'. See the commit messages for a quick run-down.
I was not sure whether I have the best approach to the definition of `stateAssertE`. I'm happy to reformulate it. And happy to move things around, too
> Remove sym_refs

- spec/haskell/src/SEL4/Model/StateData.lhs
- tools/haskell-translator/lhs_pars.py
This fixes the Haskell compile breakage introduced in #51.
It turns out that to do that, we need to teach the Haskell translator how to deal with (and ignore) multi-variable type classes.
> Haskell fix

- .github/workflows/proof.yml
- spec/haskell/Makefile
This should now run all tests the internal testboard currently runs on github.
Unfortunately, once we get to CRefine github CI will runners be too small to do that, but until then we can enjoy completeness.
> complete github CI check for MCS 

- spec/haskell/Makefile
Bring happiness to both bamboo and github: create ~/.stack, but don't fail if it's there.
[Testboard running](https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD-593)
> haskell: deal with existing "~/.stack"

- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- spec/abstract/Ipc_A.thy
- spec/abstract/SchedContext_A.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
This PR updates the aspec, ainvs, haskell, and refine proofs to properly re-sync the `rt` branch with `master` with respect to `maybe_return_sc`: both in its contents, and where it is called.
> [MCS] revert notification binding changes

- tools/c-parser/standalone-parser/Makefile
Initially the `Makefile` copied `umm_heap/ARM_HYP` from `umm_heap/ARM`,
and deleted `umm_heap/ARM_HYP` during `make clean`. However, the
contents of `umm_heap/ARM_HYP` have since been committed, so this is no
longer appropriate.
Reported-by: Michael Norrish <Michael.Norrish@data61.csiro.au>
Signed-off-by: Matthew Brecknell <Matthew.Brecknell@data61.csiro.au>
> c-parser: avoid cleaning `umm_heap/ARM_HYP`

- lib/Corres_UL.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/Move_R.thy
- the main purpose of this commit is to have a more usable
`update_sc_no_reply_stack_update_corres` lemma.
In order to match up `update_sched_context` with `setSchedContext` which is actully `setObject`, we need to consider `set_object` updating the abstract heap with a new scheduling context with some particular `n`. The new `update_sc_no_reply_stack_update_corres` gets this from the concrete side object `sc’`.
- this also led to cleaning up the way we deal with the scheduling
context sizes. This commit adds a few lemmas that provide ways to
handle scheduling context sizes explicitly.
See `get_sc_corres_size`.
- this also adds `sc_obj_at_cross` and `corres_cross_add_abs_guard`
- also includes some cleanup for `ArchMove_R` import
> some lemmas for handling sched_context size + improved `update_sc_no_reply_stack_update_corres`

- proof/asmrefine/SEL4GraphRefine.thy
- tools/asmrefine/ProveGraphRefine.thy
Also cleans up some of the debug config setup and makes result reporting
more useful.
Signed-off-by: Edward Pierzchalski <ed.pierzchalski@data61.csiro.au>
> asmrefine: add timeouts for debugging

- proof/asmrefine/SEL4GlobalsSwap.thy
Depends on https://github.com/seL4/l4v/pull/70.
Adds a `simp` rule to handle new heap access patterns arising in MCS.
> SimplExportAndRefine update for MCS

- proof/invariant-abstract/ARM/ArchFinalise_AI.thy
- proof/invariant-abstract/CNodeInv_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/Tcb_AI.thy
- proof/refine/ARM/IpcCancel_R.thy
- spec/abstract/SchedContext_A.thy
This proves `suspend_corres`.
I reordered the abstract definition of `suspend` to make the corres proof more straightforward. I also introduced the definition `sched_context_cancel_yield_to`, in analogy with the Haskell and C definitions
> Prove suspend_corres

- lib/Word_Lib/Word_Lemmas_Internal.thy
- tools/asmrefine/ProveGraphRefine.thy
This is a small preemptive update to asmrefine to support a forthcoming kernel patch that will speed up binary verification for the RISC-V MCS kernel. The kernel patch will compress read-only data, by making `register_t` a `typedef` of `uint8_t`, whereas it was previously `word_t`. Lists of registers used in IPC messages are therefore correspondingly smaller, and cause less overhead in binary verification. This asmrefine patch adds support for indexing into the user context with a variable of type `uint8_t`.
> asmrefine: support small array index types

- proof/refine/ARM/CSpace_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/TcbAcc_R.thy
- spec/design/skel/KernelStateData_H.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
- spec/haskell/src/SEL4/Model/StateData.lhs
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/Notification.lhs
- spec/haskell/src/SEL4/Object/Structures.lhs
This removes the condition on the thread state from `valid_queues` by using asserts instead (similar to the `sym_refs_asrt`)
> Remove runnable

- lib/clib/CCorres_Rewrite.thy
- lib/clib/SIMPL_Lemmas.thy
- lib/clib/Simpl_Rewrite.thy
This is like `ccorres_rewrite`, but for `hoarep`, and uses the same
infrastructure.
The interaction between the `simpl_rewrite` locale and the
`simpl_rewrite` method was confusing, and didn't work well with multiple
interpretations. We replace it with a simple anonymous context. Since
that puts more things in the global namespace, we rename many of them.
The `simpl_rewrite` method is now parameterised by a `hom` fact which
determines the predicate under which we are rewriting.
This also includes a slight generalisation of `exec_eq_is_valid_eq`,
which allows a similar generalisation of `hoarep_rewrite`.
> clib: add a `hoarep_rewrite` method

- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/Schedule_R.thy
- spec/abstract/Ipc_A.thy
- spec/abstract/SchedContext_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This change to the abstract spec bring the `rt` branch closer to `master` by simplifying how round-robin scheduling contexts are handled in some cases.
It based on the commit here:
https://bitbucket.ts.data61.csiro.au/projects/SEL4/repos/sel4/pull-requests/1781/commits/17e54fa8d0e389b44c7f87b91c35b568fcc14924#include/kernel/sporadic.h
in the pull-request here:
https://bitbucket.ts.data61.csiro.au/projects/SEL4/repos/sel4/pull-requests/1781/commits
> Simplify handling of round_robin sched contexts

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Tcb_R.thy
Some lemmas about `tcbSchedDequeue` had preconditions involving `tcb_at'` that were too strong due to the use of `threadGet_const_tcb_at` instead of `threadGet_wp`.
> Weaken tcbSchedDequeue preconditions

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/TcbAcc_R.thy
Fixes the following lemmas:
`cteDeleteOne_invs`
`unbind_notification_corres`
`unbind_maybe_notification_corres`
Modifies `finaliseCap_replaceable` precondition for `cteDeleteOne_invs`
Adds the following helper lemmas:
`no_fail_simple_ko_at`
`no_fail_get_notification`
`get_simple_ko_exs_valid`
`get_notification_exs_valid`
> Finalise_R sorries

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
Proved `schedContextUnbindTCB_invs'` + moved a few lemmas around + introduced a counterpart to `same_caps` from AInvs for reasoning about `ex_nonz_cap_to'` after an update.
> Prove schedContextUnbindTCB_invs'

- spec/haskell/src/SEL4/Object/Reply.lhs
The [C code](https://github.com/seL4/seL4/blob/master/src/object/reply.c#L101) returns early in the `reply_pop` branch, which leads to different behaviour than the previous Haskell implementation. While refactoring this I also moved the `replyUnlink` calls to the end of the function, which is consistent with `replyRemoveTCB` and I think will be convenient when proving hoare triples for `replyRemove`.
It might not be necessary to completely refactor the C code in the same way, but it would make crefine easier if we did. At the very least I think that we should move the `reply_unlink` calls to the end of `reply_remove` there as well.
> rt haskell: refactor replyRemove to match the c

- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/CSpace_I.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/TcbAcc_R.thy
- spec/haskell/src/SEL4/Object/ObjectType.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
The remaining subgoal involves showing that a reply that isn't linked to a tcb does not have any prev/next pointers. Unfortunately, we can only get from the abstract invariants that it is not part of a queue connected to a scheduling context. To solve this properly we expect that we will need a new Haskell-level invariant.
> rt: finish most of finaliseCap_replaceable

- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Reply_R.thy
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/ObjectType.lhs
- spec/haskell/src/SEL4/Object/Reply.lhs
Deleting a reply object that is linked to a BlockedOnReceive thread is unusual behaviour and it's not clear what the expected behaviour should be. Previously replyUnlink was used, but it sets the thread to Inactive while leaving it in the endpoint's queue which breaks the invariants. Calling cancelIPC at least guarantees that the system ends up in a consistent state.
While updating the proofs I was able to delete or prove a few sorries and some crunches became more powerful, which unfortunately might end up conflicting with other ongoing work.
> rt: cancel IPC when finalising reply caps 

- misc/regression/tests.xml
PEP 394 expects that Python 3 installations provide a `python3` command,
but does not require a `python` command. Some distributions (including
Debian) are no longer providing a `python` command, but do provide
`python3`.
In this change, the `python3` interpreter is invoked via the existing
`#!` line in the `testspec.py` script.
> regression: use `python3` for tests-xml-correct

- .github/workflows/proof.yml
This is in preparation for the repo manifest switching over to Isabelle2020.
Until we have merged the Isabelle2020 update, this commit will make sure the
github tests continue to run Isabelle2019 for this branch.
> rt: fix ts-2019 branch for github CI tests

- lib/Corres_UL.thy
- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/Decode_A.thy
- spec/abstract/Invocations_A.thy
- spec/abstract/SchedContext_A.thy
- spec/abstract/Schedule_A.thy
- spec/abstract/Syscall_A.thy
- spec/haskell/src/SEL4/API/Invocation.lhs
- spec/haskell/src/SEL4/API/Syscall.lhs
- spec/haskell/src/SEL4/Kernel/Thread.lhs
- spec/haskell/src/SEL4/Object/ObjectType.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This solves `activateThread_invs'` and `activateThread_corres` but requires a number of small spec-changes:
* haskell for activateThread was slightly out-of-date
* Update ipc buffer handling: the code now does a lookup before invocation decoding and is passed all the way down.
* Fix ordering of commands for inlining of cancel_yield_to into complete_yield_to.
> activate_thread: proofs for corres lemma and invs' lemma.

- proof/Makefile
- spec/Makefile
- tools/autocorres/ROOT
- tools/autocorres/test-seL4/TestSEL4.thy
This session wasn't included in the testboard and of course promptly failed.
The fix is a) a small tweak in the imports, and b) a slight refactor in the Makefile to make sure the ASpec doc version files are generated early enough.
> fix AutoCorresSEL4 session

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Reply_R.thy
- spec/haskell/src/SEL4/Object/Reply.lhs
Doing this requires introducing a new invariant called `valid_replies'`. Adding this to `invs'` and proving that it is preserved still needs to be done.
> rt refine: finish replyClear_makes_unlive

- lib/HaskellLemmaBucket.thy
- lib/NICTATools.thy
- lib/Repeat_Attribute.thy
- proof/access-control/CNode_AC.thy
- proof/bisim/Separation.thy
- proof/bisim/Syscall_S.thy
- proof/refine/ARM/ArchAcc_R.thy
- proof/refine/ARM/Bits_R.thy
- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/CSpace1_R.thy
- proof/refine/ARM/CSpace_R.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/ARM/Untyped_R.thy
- proof/refine/ARM/VSpace_R.thy
- proof/refine/ARM_HYP/CSpace1_R.thy
- proof/refine/RISCV64/CSpace1_R.thy
- proof/refine/X64/CSpace1_R.thy
- spec/abstract/CSpace_A.thy
This makes the locales explicitly discharge all `typ_at_lifts` assumptions and updates the proofs to use the locales instead of manually instantiating `typ_at_lifts` with a lemmas command.
To properly discharge all of the assumptions I added a `REPEAT` attribute, that applies the given attributes one or more times. This should successfully handle almost all standard uses of attributes that I have been able to think of, with the only exception being `symmetric` which will loop. We could guard against this by passing along all seen thms and checking that we haven't looped to any previous one, but this is a bit unpleasant and wouldn't perform well in complicated cases. Opinions and suggestions welcome!
As side distractions, while doing this I also added wp rules for several Haskell assert …
> mcs: improve typ_at_props locales and typ_at lifting

- proof/Makefile
The SimplExportOnly session is now just SimplExport.
> asmrefine: SimplExportOnly renamed

- proof/invariant-abstract/DetSchedAux_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/KHeap_R.thy
- spec/design/skel/KernelStateData_H.thy
- spec/haskell/src/SEL4/Model/StateData.lhs
- spec/haskell/src/SEL4/Object/ObjectType.lhs
This updates valid_replies' to only hold for replies with pointers to other replies. Replies connected to an SC are instead handled by an assertion and a cross lemma, using the abstract valid_replies invariant.
> rt: make valid_replies' easier to prove

- tools/c-parser/CProof.thy
- tools/c-parser/modifies_proofs.ML
This commit adds support for inline assembly whose `lhs` updates a
global variable (such as the heap).
Prior to this commit, the modifies prover assumed that the `lhs` update
of an `asm_spec` only updated local variables. Specifically, the use of
`asm_store_eq_helper[OF globals.surjective globals.surjective]` as a
rewrite rule assumes that `globals (lhs v s)` simplifies to `globals s`,
exposing the `asm_store` inside `s` to the rewrite rule.
This commit avoids the assumption by using `globals.equality` as an
introduction rule. This produces more subgoals, but the subgoals are
relatively simple, so the perfomance is essentially unchanged.
> c-parser: improve asm support in modifies proofs

- README.md
- proof/access-control/README.md
- proof/asmrefine/README.md
- proof/capDL-api/README.md
- proof/crefine/README.md
- proof/drefine/README.md
- proof/infoflow/README.md
- proof/invariant-abstract/README.md
- proof/refine/README.md
- proof/sep-capDL/README.md
- sys-init/README.md
- tools/README.md
- tools/asmrefine/README.md
The links to nicta.com.au have stopped working, so the publication links
now point to the TS publication pages.
> update publications links

- lib/Lib.thy
The lemma set `exception_set_finite` contained the members
`exception_set_finite_1` and `exception_set_finite_2`. The `_1`/`_2`
suffix clashes with the internal `(1)` suffix for lemma set references,
which in some code paths is internally represented as `_1`, leading to
an error message.
Curiously this error message only occurs when the proof is run
single-threaded, so it has gone unnoticed for quite some time.
> lib: avoid internal index names

- tools/autocorres/doc/quickstart/Chapter1_MinMax.thy
- tools/autocorres/doc/quickstart/Chapter2_HoareHeap.thy
- tools/autocorres/doc/quickstart/Chapter3_HoareHeap.thy
The AutoCorres quickstart document includes code from `*.c` files from a
given line number, to avoid including license headers and other details
that aren't useful in the document. This updates the line numbers for
the current license headers.
> autocorres: fix code inclusion in quickstart doc

- proof/tests.xml
CRefine takes longer with Isabelle2020, so this gives more headroom.
Yes, the "proof performance" label is meant to be ironic. :-)
> regression: increase CRefine timeout

- .github/workflows/proof.yml
With Isabelle2020 the Refine sessions are too close to memory
boundaries on github runners, the tests randomly fail with out-of-store
exceptions in polyml (but also randomly succeed without change).
Removing the session here until we have a better solution.
> github: remove Refine sessions from github CI

- lib/Corres_UL.thy
- lib/NonDetMonadLemmaBucket.thy
- proof/invariant-abstract/Tcb_AI.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/Decode_A.thy
- spec/abstract/KHeap_A.thy
- spec/haskell/src/SEL4/Object/TCB.lhs
Also involves some uninteresting spec updates to make the corres proof easier.
* Changes `decode_update_sc` to return just the updated SC parameter (rather than a whole invocation from which we just extract the SC parameter anyway), and changes it to use pattern matching rather than chained checks - this is both easier to read and matches the Haskell and C.
* Removes `andM` from `decodeSetSchedParams`. Turns out reasoning about corres for `andM` is really, _really_ fiddly - I spent at least a day trying to figure out how to prove and use `monadic_rewrite` rules to massage it into a better form before bailing.
> Prove `decode_set_sched_params_corres`

- proof/crefine/ARM/Invoke_C.thy
- proof/crefine/ARM_HYP/Invoke_C.thy
- proof/crefine/RISCV64/Invoke_C.thy
- proof/crefine/X64/Invoke_C.thy
The corresponding seL4 patch removes an unused line in `invokeUntyped_Retype`
The CI tests will fail, because there is a corresponding seL4 PR that needs to be merged at the same time for this.
Testboard with everything green is [here](https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD-665)
> crefine: proof update for seL4 7cc50c3039

- README.md
- docs/setup.md
There is another (out-of-date) dependency description for l4v on the
docs site. To avoid this duplication, this commit factors out the
dependency part of the README, so that it be included directly on the
docs site without going stale.
Also, the README was getting way too long.
> docs: factor out dependency specs

- lib/HaskellLib_H.thy
- lib/Lib.thy
- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/EmptyFail_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/Ipc_AI.thy
- proof/invariant-abstract/RealTime_AI.thy
- proof/invariant-abstract/Tcb_AI.thy
- spec/abstract/IpcCancel_A.thy
- spec/abstract/Ipc_A.thy
Replace the implementation of sort_queue with tcb_ep_dequeue and tcb_ep_append to match the Haskell and C implementations. Keeping sort_queue would require us to prove a new invariant instead and would also make the refinement more difficult.
> rt lib+aspec+ainvs: replace sort_queue

- lib/Heap_List.thy
- lib/Lib.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/refine/ARM/Reply_R.thy
This PR contains `heap_path` related lemmas that I wrote for proving the `reply_remove_tcb_corres` lemma. It might be good to merge this first instead of keeping these lemmas back. It also removes a few sorries.
- misc lemmas for `heap_path`: `heap_path_prefix`, `heap_path_takeWhile_lookup_next` and others for looking at and around a middle point of the path
- introduces `sym_heap` and related lemmas: when two heaps are injective and each is an inverse of the other, they are `sym_heap`, and a path in one implies a reversed path in the other (plus some details about the ends)
- proof that `replyPrevs_of s'` and `replyNexts_of s'` are `sym_heap` if you can assume `sym_refs (list_refs_of_replies’ s’)`, and various lemmas derived from there
- some cleanup
> rt heap_path/sym_heap lemmas

- proof/crefine/ARM_HYP/Machine_C.thy
- proof/invariant-abstract/ARM_HYP/Machine_AI.thy
- spec/machine/ARM_HYP/MachineOps.thy
seL4 commit seL4/seL4@c381c7e14c (PR seL4/seL4#289) changes cache flushing behaviour for the
verified ARM_HYP configuration. This commit adjusts accordingly.
> arm-hyp: proof updates for seL4 c381c7e14c

- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/TcbAcc_R.thy
Previously, sym_refs' was inside invs' and so setThreadState needed to be careful about modifying references coming from tcb thread states. Now that sym_refs' has been removed, it is easier to reason about how setThreadState interacts with invs'.
This is a small improvement that should make the lemma much more useable.
> Improve `sts_invs_minor'`

- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/ObjectType.lhs
- spec/haskell/src/SEL4/Object/Reply.lhs
Because setReplyTCB is only called in 4 places, and it is just a wrapper for updateReply, having it as a separate definition means writing double the lemmas, or just unfolding the definition in many places. It is simpler just to remove the function altogether. This should streamline a few proofs and reduce duplicated work.
I have also done the same with getReplyTCB.
> Remove setReplyTCB and getReplyTCB

- lib/Lib.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
This was factored out of my ongoing `valid_replies'` work so that it could be used in other PRs. It updates various lemmas that are connected to `valid_replies'` to use projections instead of `obj_at'`.
> rt refine: make more use of reply projections

- proof/crefine/ARM_HYP/Arch_C.thy
- spec/abstract/ARM_HYP/VCPU_A.thy
- spec/haskell/src/SEL4/Machine/RegisterSet/ARM.lhs
- spec/haskell/src/SEL4/Object/VCPU/ARM.lhs
The seL4/seL4@93ab2543d9d8 commit factors out special treatment of specific VCPU
registers, and this commit updates the ARM_HYP proofs accordingly.
> arm_hyp: proof updates for seL4 commit 93ab2543d9d8

- proof/invariant-abstract/ARM/ArchFinalise_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchFinalise_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
- proof/invariant-abstract/X64/ArchFinalise_AI.thy
The lemma finalise_cap_replaceable is only used in arch proofs,
so it doesn't need to be in the interface locale to generic proofs.
Signed-off-by: Gerwin Klein <gerwin.klein@data61.csiro.au>
> ainvs: reduce Finalise interface

- proof/invariant-abstract/ARM/ArchFinalise_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
- proof/invariant-abstract/RealTime_AI.thy
- spec/abstract/IpcCancel_A.thy
This PR contains:
1. tweak the if-true branch of reply_unlink_sc to match replyPop
- reorder to align with replyPop
- use update_sched_context instead of set_sc_obj_ref
2. some proof fixes for the above change
> reply_unlink_sc update

- .github/workflows/pr.yml
This started out as test for seL4/ci-actions#40, and can now be merged to activate the theory lint check.
> enable theory lint action

- .github/workflows/pr.yml
This github action checks PRs for unwanted outer syntax commands like
`sorry`, `sledgehammer`, or `thm`. The check is non-required, so can be
ignored for those cases where the command is wanted after all.
In addition to console output, the action annotates the sources in the
"changed files" tab. This only works for PRs from within the same repo,
unfortunately (forks have insufficient rights for annotations)
> cherry-pick thylint action from master branch

- proof/invariant-abstract/ARM/ArchFinalise_AI.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/Interrupt_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/Ipc_AI.thy
- proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- proof/invariant-abstract/TcbAcc_AI.thy
- proof/refine/ARM/IpcCancel_R.thy
- spec/abstract/Structures_A.thy
It's not clear that this is much nicer, but it at least makes the names and locations of these functions more consistent.
Unfortunately, using the standard discriminators and selectors that the datatype package can generate led to confusing issues with unrelated proofs breaking. I wasn't able to fix this and ended up manually defining them.
The actual goal that started me down this path was wanting a nice way to define `is_reply_state`.
> rt: more consistent thread_state discriminators

- lib/Corres_UL.thy
- proof/refine/ARM/Interrupt_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Tcb_R.thy
This also includes `corres_split_skip`, a little rule to skip over a function in a `corres` proof in a way similar to `hoare_seq_ext_skip`
> Some small sorries

- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/InvariantsPre_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/RealTime_AI.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/Move_R.thy
- spec/abstract/IpcCancel_A.thy
- spec/haskell/src/SEL4/Object/Reply.lhs
This proves `replyPush_corres` and adds proofs about a new function `bindScReply`.
* A large number of reply-related lemmas are moved to Reply_R and some new ones added.
* Tweaks to `donateSchedContext_corres` only weaken the preconditions slightly.
* Moving `donateSchedContext_corres` is isolated to a separate commit to make reviewing easier
* Some `FIXME RT: move` comments remain. I would rather not resolve them now, but I can if needed.
This PR replaces the previous one (https://github.com/seL4/l4v/pull/146) which I will decline since so much has changed.
> rt_replyPush

- .github/workflows/pr.yml
The annotation action only works for in-repo pull requests. This flag
ignores any errors from this action so that forked pull requests don't
get spurious test failures.
> thylint: ignore annotation errors

- proof/refine/ARM/Finalise_R.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
This updates the Haskell so that `unbindFromSC` checks the `scYieldFrom` field before accessing it and also makes it better match the abstract.
> rt: update unbindFromSC

- proof/invariant-abstract/ARM/ArchRetype_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchRetype_AI.thy
- proof/invariant-abstract/Detype_AI.thy
- proof/invariant-abstract/RISCV64/ArchRetype_AI.thy
- proof/invariant-abstract/X64/ArchRetype_AI.thy
This PR is for the master branch.
While working on the preemption_point spec update for MCS, I noticed some odd requalification work-around at the end of ArchRetype_AI, when it is perfectly fine to do requalification normally.
For MCS, it makes sense to clean this up on this occasion, and I thought I might as well do it for the master, too.
I am running the testboard here: [testboard](https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD3)
but it looks like something is not quite right with it. I think the testing will be operating in a useful way, but it is running on its own new branch. Is this what is expected??
> ainvs cleanup: requalify some arch lemmas proved in ArchRetype_AI

- proof/refine/ARM/Finalise_R.thy
- spec/haskell/src/SEL4/Object/Reply.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
This changes all of the remaining `getReply; setReply` patterns to use `updateReply`, except for `replyPop` which is left for https://github.com/seL4/l4v/pull/185.
> rt: use updateReply everywhere

- lib/Corres_UL.thy
- proof/invariant-abstract/Ipc_AI.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/haskell/src/SEL4/API/Invocation.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
Prove `tc_corres_caps` and `tc_corres_sched`. Some changes to the specs based on what I've proved as part of my patch. Priority proofs are still sorried. Some adjustments to the main two lemmas will be needed soon.
> rt refine+haskell: prove tc_corres_caps and tc_corres_sched

- proof/invariant-abstract/ARM/ArchFinalise_AI.thy
- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
- spec/abstract/CSpace_A.thy
- spec/abstract/SchedContext_A.thy
This is to make it possible to prove correspondence when setting `sc_refill_max` to `0` in `finalise_cap`. Due to how the state relation is defined, in Haskell doing this implicitly also leads to an empty refill list, and this change makes the abstract do the same thing.
There was potentially an alternative solution involving updating the state_relation. We decided to go with this option because we found it more intuitive, and it also has the potential to simplify some of the abstract invariants. For example, it might now be possible to prove that some invariants hold for all scheduling contexts instead of just active ones.
> rt: set refills to empty in finalise_cap

- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/refine/ARM/SchedContextInv_R.thy
- spec/abstract/ARM/Arch_Structs_A.thy
- spec/abstract/Decode_A.thy
- spec/abstract/RISCV64/Arch_Structs_A.thy
- spec/abstract/Structures_A.thy
- spec/design/skel/ARM/Hardware_H.thy
- spec/design/skel/RISCV64/Hardware_H.thy
- spec/design/skel/SchedContext_H.thy
- spec/haskell/src/SEL4/Machine/Hardware.lhs
- spec/haskell/src/SEL4/Machine/Hardware/ARM.lhs
- spec/haskell/src/SEL4/Machine/Hardware/RISCV64.hs
- spec/haskell/src/SEL4/Object/TCB.lhs
- spec/machine/ARM/MachineOps.thy
- spec/machine/MachineExports.thy
- spec/machine/RISCV64/MachineOps.thy
There is a constant `maxPeriodUs` in the C. For verified configurations, the `maxPeriodUs` in the C is defined in the C to be equal to one hour. See 
https://bitbucket.ts.data61.csiro.au/projects/SEL4/repos/sel4/pull-requests/1882/overview
for the changes to the C and where this constant originates. This is the maximum number of microseconds that the user may set as the period of a scheduling context. The equivalent in the abstract spec is `MAX_PERIOD_US`, and in the Haskell, this is `maxPeriodUs`, which is defined to be equal to `MAX_PERIOD_US`. In the abstract spec, we define `MAX_PERIOD = us_to_ticks MAX_PERIOD_US`, and similarly for the Haskell. 
The definition of `decode_sched_control_invocation` is changed so that all values given by the user are considered to be in microseconds. …
> decode sched control

- lib/Corres_UL.thy
- lib/Heap_List.thy
- lib/ListLibLemmas.thy
- lib/MonadicRewrite.thy
- proof/refine/ARM/Corres.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/TcbAcc_R.thy
This PR contains more of the on-going cleanup, as well as several small additions and abstractions that are part of the `reply_remove_tcb_corres` PR (#180 ).
At this point, I am giving up on merging #180 as is mainly because of the complications from reply related duplications and changes. This contains part of that PR that can be merged without more work. For the rest, I am planning to quickly redo it on top of the current rt, and will include there some refactors for reusing some part for `replyRemove` and `replyPop`.
A full description of `sr_inv_ul` can be found in #160 .
> rt cleanup + some bits for reply_remove_tcb corres

- README.md
- proof/access-control/README.md
- proof/asmrefine/README.md
- proof/capDL-api/README.md
- proof/crefine/README.md
- proof/dpolicy/Dpolicy.thy
- proof/drefine/README.md
- proof/infoflow/README.md
- proof/invariant-abstract/README.md
- proof/refine/README.md
- proof/sep-capDL/README.md
- sys-init/README.md
- tools/README.md
- tools/asmrefine/README.md
- tools/autocorres/README.md
The TS website has settled on no `.pml` postfix
> trivial: fix links to papers

- tools/c-parser/program_analysis.ML
- tools/c-parser/syntax_transforms.ML
- tools/c-parser/testfiles/jiraver1389.c
- tools/c-parser/testfiles/jiraver1389.thy
Prior to rendering an expression to SIMPL, the C parser extracts
function calls from the expression and reinserts them as new statements
placed just before the statement containing the expression. The result
of each such function call is assigned to a temporary variable which
takes the place of the function call in the original expression.
Prior to this commit, the C parser would not always generate fresh
temporary variable names when multiple temporaries were needed. In
particular, when the left-hand side of an assignment contained a
function call returning the same type as a function call in the
right-hand side expression, the extracted function calls would be
assigned to the *same* temporary variable.
This commit addresses the issue by carrying name generation state across
all …
> c-parser: use fresh names for temporaries

- tools/c-parser/FunctionalRecordUpdate.ML
Loading the FunctionaRecordUpdate file in Isabelle's jedit is slow.
This change expands the fN family of functions, which fixes the problem.
Signed-off-by: vjackson725 <v.jackson@unsw.edu.au>
> c-parser: rewrite functional-record-update fN defs

- lib/Corres_UL.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/TcbAcc_R.thy
This PR contains the final cleaned-up version of the `replyRemoveTCB_corres` proof. Most part of it might have been reviewed elsewhere. The most notable thing perhaps is a simpler version of `sc_with_reply’` as suggested by Corey in #180 , but there isn’t so much change in the proof for that.
This also cleans up various corres rules for `setSchedContext`. A more (most?) generic version of `setSchedContext_corres` is added, and other existing versions are consolidated and derived from it.
> rt replyRemoveTCB_corres

- tools/autocorres/README.md
This reverts commit 985ce0d28a87298427e9836055cfbad0751b13c5.
> trivial: fix c-parser link

- misc/testboard/README.md
- misc/testboard/testboardpush
This should work with the public GitHub testboard ([seL4/gh-testboard](https://github.com/seL4/gh-testboard)).
Use the same as before, should work with verification-manifest as well as verification-manifest-internal (remotes and repo names of verification-manifest-internal will appear publicly, though).
Sub-repo commands are not yet supported.
> testboardpush script for github testboard

- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/ARM/VSpace_R.thy
I'm not quite sure what the best approach to reviewing this will be. It's almost all lemmas that have been moved with a couple of minor updates to proofs being required in a few places.
Most lemmas have ended up in TcbAcc_R, SchedContext_R or Schedule_R, so you might want to focus on where lemmas now are and if you agree with that file.
I have also reordered the dependency graph slightly so that Reply_R imports Schedule_R which imports SchedContext_R. This led to much less lemmas needing to be moved and I think results in all of the required results being available where we expect them to be needed.
> rt: move schedContextDonate and related lemmas

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Ipc_R.thy
- spec/haskell/src/SEL4/Object/Reply.lhs
This PR contains some spec updates for `repplyPop` and the proof fixes
- use `updateReply` where possible
- contains Victor’s commit from #175: move `schedContextDonate` to just before `cleanReply`
- move `threadGet` to just before `schedContextDonate`
> rt reply pop tweaks

- lib/Word_Lib/Word_Lemmas_Internal.thy
- proof/ROOT
- proof/asmrefine/export/ARM/ArchSEL4SimplExport.thy
- proof/asmrefine/export/RISCV64/ArchSEL4SimplExport.thy
- proof/asmrefine/export/SEL4SimplExport.thy
- proof/crefine/Move_C.thy
- proof/crefine/RISCV64/IpcCancel_C.thy
- proof/crefine/RISCV64/Machine_C.thy
- proof/crefine/RISCV64/Syscall_C.thy
- tools/c-parser/CProof.thy
Some architectures support count-leading-zeroes and count-trailings-zeros functions within the instruction set and others do not. This means that binary verification must treat them differently on RISCV64 than on ARM. In ARM their behaviour is axiomatized because we must make basic assumptions about the semantics of instructions. In RISCV, we must verify the C code which implements these functions. As a result, instructions to the CParser must be updated, and that creates a hole in the existing CRefine proofs for RISCV64.
This work supplies the appropriate CRefine proofs, and arch-splits the SimplExportAndRefine session so that this issue is handled appropriatelt on different architectures.
> riscv crefine and SEAR: arch-split SEAR and custom proofs about clz and ctz

- lib/Word_Lib/Word_Lemmas_Internal.thy
- proof/crefine/RISCV64/StateRelation_C.thy
- proof/crefine/RISCV64/SyscallArgs_C.thy
- proof/crefine/RISCV64/TcbAcc_C.thy
- proof/crefine/RISCV64/Wellformed_C.thy
This PR verifies the changes found in the corresponding pull-request here:
https://bitbucket.ts.data61.csiro.au/projects/SEL4/repos/sel4/pull-requests/1817/overview
> riscv: use `uint8_t` for `register_t`

- camkes/adl-spec/Wellformed_CAMKES.thy
The current formulation allows an interface of an instance to be mentioned multiple times in the from side of the same connection.
There is the possibility that I have overlooked/misunderstood how this is intended to work, but this looks like a bug to me.
> Fix refs_valid_procedures definition

- lib/Heap_List.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/refine/ARM/ArchAcc_R.thy
- proof/refine/ARM/Bits_R.thy
- proof/refine/ARM/CSpace1_R.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/Ipc_A.thy
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/Reply.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
I recommend reviewing commit-by-commit.
This is the same as https://github.com/seL4/l4v/pull/234 but free of all the previous comments.
**In this PR:**
1. Update send_ipc (abstract) to match source. Fix AInvs.
2. Update sendIPC to be slightly easier for refinement.
3. Remove sym_ref assertions from replyPush and schedContextDonate
a. These assertions can actually fail in executable code.
5. Fix up refine for these changes in Haskell
6. Some slight improvements to replyPush lemmas.
**As a side effect:**
- 1 new heap
- change `sym_heap` to a definition and some related cleanup
> Fixes to sendIPC (fresh PR)

- proof/asmrefine/export/ARM/ArchSEL4SimplExport.thy
- proof/crefine/ARM/IpcCancel_C.thy
- proof/crefine/ARM_HYP/IpcCancel_C.thy
- proof/crefine/ARM_HYP/Syscall_C.thy
- proof/crefine/X64/IpcCancel_C.thy
- proof/crefine/X64/Syscall_C.thy
This commit verifies seL4 PR [#325][], which fixes the riscv32 build broken by seL4 commit [9ec5df5f][].
[#325]: https://github.com/seL4/seL4/pull/325
[9ec5df5f]: https://github.com/seL4/seL4/commit/9ec5df5f
> riscv: fix CLZ and CTZ for riscv32 builds

- misc/bump/README.md
- misc/bump/bump-local-repos
- misc/bump/bump-ver-manifest
- misc/bump/ver-bump.py
Use this to update revisions in `devel.xml` of `verification-manifest` at <https://github.com/seL4/verification-manifest>
The script assumes direct push access to `verification-manifest` without pull request requirement. This is currently not configured and ill only work for people with admin access (TSC members).
We could either make the script also raise a pull request on `verification-manifest` or we could relax the access rights on `verification-manifest` to not require pull requests from people with commit access. I'd be happy with the latter.
> `bump` script for `verification-manifest`

- proof/invariant-abstract/DetSchedAux_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/KHeap_AI.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/Move_R.thy
This proves `sendIPC_corres` and attempts to do so with minimal other impact on proofs, aside from some strengthening of lemmas for `replyPush` and `schedContextDonate`.
> rt refine: sendIPC_corres

- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This is some cleanup, mainly on Haskell, that came up in Michael’s Overrun PR (and others).
I did this as part of the work to finish Refill corres PR, but the cleanup here also overlaps with the Schedule proofs that Mitch wants me to look at, in that both the PRs want `no_ofail` proof for ‘refillHeadOverlapping`. All things considered, I think it makes sense to have this change merged before working on that lemma and other related ones.
the changes included are:
- remove `readMapScPtr` (because this was an extra layer of definition that we could do without)
- cleanup for `updateSchedContext`
- remove dest! attribute for `readObject_misc_ko_at’`
(we do need to add it quite often, but there are cases when we specifically don’t want it, and it is harder to figure out when the lemma is added …
> Haskell cleanup

- proof/invariant-abstract/ARM/ArchCNodeInv_AI.thy
- proof/invariant-abstract/ARM/ArchLevityCatch_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchCNodeInv_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchLevityCatch_AI.thy
- proof/invariant-abstract/CNodeInv_AI.thy
- proof/invariant-abstract/RISCV64/ArchCNodeInv_AI.thy
- proof/invariant-abstract/RISCV64/ArchLevityCatch_AI.thy
- proof/invariant-abstract/X64/ArchCNodeInv_AI.thy
- proof/invariant-abstract/X64/ArchLevityCatch_AI.thy
The improvements are:
* add comments into proof
* unwind some automation to clarify how each subgoal is solved.
* Remove some awkward "in monad" lemmas about `premption_point`
> A small improvement to `rec_del_termination`

- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/Move_R.thy
- spec/abstract/Ipc_A.thy
- spec/abstract/SchedContext_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This proves `corres` rules for `refillUpdate`, `refillNew`, and (I think) all other functions which modify refills other than `refillBudgetCheck` and `refillUnblockCheck`. 
There are many lemmas which we may want to move
> Refill corres rules

- docs/setup.md
there are a few more updates to the instructions in the pipeline (for MacOS), but for now just markdown linting and a bit of cleanup.
> setup docs: markdown lint and slight tweaks

- proof/crefine/ARM/Arch_C.thy
- proof/crefine/ARM_HYP/Arch_C.thy
A previous update to C code added a disjunct to an `if` condition
outside the existing `unlikely` branch hint. This commit is the proof
update for a C patch that extends the branch hint to the full `if`
condition.
Corresponding seL4 PR: https://github.com/seL4/seL4/pull/310
This change is motivated by a C parser update I'm working on, which is in turn required for BV and MCS verification. Without this change, the C parser update would require some proof updates. I figure it's better to do any proof updates with this patch, which I think makes a small improvement to the kernel. After this change, the C parser update won't require any further l4v proof updates.
For a preview of the C parser update, see https://github.com/seL4/l4v/pull/230. (Note that the C parser PR is rebased over this …
> arm crefine: fix `decodeARMMMUInvocation` branch hint

- docs/haskell-assertions.md
We import some documentation regarding the role of assertions in Haskell, and how we use assertions in Haskell to transport information from abstract invariants to Haskell-to-C refinement proofs.
The file is a Markdown-ified version of previous documentation hosted at UNSW and Data61.
(This is a pure addition to docs, and should not change or impact verification in any way)
> Import documentation: Haskell assertions

- lib/LemmaBucket.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
This is incremental progress towards `schedule_corres`. The main contributions are:
* `setNextInterrupt_corres`
* `getReprogramTimer_corres`
* `setDomainTime_corres`
* `setConsumedTime_corres`
* `setCurSc_corres`
* `machine_op_lift_corres_trivial`
* `refillSingle_corres`
This also introduces `standard_sc` which might be useful, I'd appreciate some feedback on that.
> Incremental progress towards `schedule_corres`

- proof/crefine/ARM/VSpace_C.thy
- proof/crefine/ARM_HYP/VSpace_C.thy
- proof/crefine/RISCV64/VSpace_C.thy
- proof/crefine/X64/VSpace_C.thy
- proof/drefine/Finalise_DR.thy
- proof/refine/ARM/VSpace_R.thy
- proof/refine/ARM_HYP/VSpace_R.thy
- spec/abstract/ARM/ArchVSpace_A.thy
- spec/abstract/ARM_HYP/ArchVSpace_A.thy
- spec/haskell/src/SEL4/Kernel/VSpace/ARM.lhs
- spec/machine/ARM/Platform.thy
- spec/machine/ARM_HYP/Platform.thy
This verifies a C kernel patch (seL4/seL4#409) which consolidates
translation between virtual and physical addresses, and makes it
consistent across architectures. In particular, we always use
`addrFromKPPtr`, even on architectures that don't use a distinct region
to map the kernel ELF. This will facilitate future improvements which
move the ELF mapping into a distinct virtual address region.
Signed-off-by: Matthew Brecknell <Matthew.Brecknell@data61.csiro.au>
> always use `addrFromKPPtr` for kernel addresses

- proof/refine/ARM/ADT_H.thy
- proof/refine/ARM/Init_R.thy
- proof/refine/ARM_HYP/ADT_H.thy
- proof/refine/ARM_HYP/Init_R.thy
- proof/refine/RISCV64/ADT_H.thy
- proof/refine/RISCV64/Init_R.thy
- proof/refine/X64/ADT_H.thy
- proof/refine/X64/Init_R.thy
Defined a series of `zeroed` states on the abstract and haskell sides
that together satisfy the state relation. These states do not satisfy
invs or invs'.
This is connected to https://sel4.atlassian.net/browse/VER-1342
> refine: The state relation is not empty.

- proof/ROOT
- proof/refine/ARM/ADT_H.thy
- proof/refine/ARM_HYP/ADT_H.thy
- proof/refine/RISCV64/ADT_H.thy
- proof/refine/X64/ADT_H.thy
Importing Init_R into ADT_H was causing EmptyFail_H to fail. Since
no other theories actually depend on Init_R we can instead include
it in the Refine session directly.
Signed-off-by: Mitchell Buckley <mitchell.alan.buckley@gmail.com>
> refine: fix regression caused by bad theory import

- lib/Monad_WP/OptionMonad.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
This PR contains the following changes, part of the refill spec cleanup PR (#290 ):
- a most generic corres rule and some wp rules for `updateSchedContext`
- some abbreviations and rewrite lemmas for simplifying AInvs projections
- add a bunch of wrap_slice and refill related lemmas
- add `length_replaceAt` to the simp set, and related cleanup
Some more detailed comments on those changes:
- the `updateSchedContext_corres` rules is generic enough to handle all the refill related corres rules in the main PR #290 . The way we implement refill circular list in Haskell introduces unusual interdependency and the rule requires assumptions involving both the abstract and concrete states that satisfy the state relation. This probably suggests one direction we could extend our corres framework, …
> updateSchedContext_corres, opt_pred, some cleanup, etc.

- lib/crunch-cmd.ML
- lib/test/Crunch_Test_NonDet.thy
- proof/invariant-abstract/CNodeInv_AI.thy
Previously, if `crunch` encountered monadic constants with different state spaces then it would throw a type unification failure due to trying to combine the different preconditions. This meant that any lifted functions had to be explicitly ignored.
This PR changes `crunch` so that it catches and ignores the type unification failure. This allows it to process lifted functions and even prove simple properties about them. However, if the lifted functions require any side conditions for the main property being crunched, then these will not be propagated and the proof of the top-level function will most likely fail.
I do not believe that it is possible to propagate these side conditions without manually passing in a state-lifting function, and I have not yet seen a use case that makes it …
> Support crunching lifted monadic functions

- proof/refine/ARM/StateRelation.thy
It was surprisingly hard to find this proof.
> rt: replace call to `smt`

- .github/workflows/proof.yml
- misc/regression/run_tests.py
This completes the previous commit to run all proof tests on reasonably high-powered AWS VMs instead of GitHub runners. All tests run in one go for efficiency.
This needs seL4/ci-actions#113 merged first.
For now we test on each push to master and rt, and for all pull requests. Since runs for fork-PRs need to be approved for the first run, this should be reasonably safe against abuse.
One full run from scratch costs about USD 2.70 of the free, but limited seL4 foundation AWS credits. Most runs will not be from scratch, but if you don't need the results of a run, it's a good idea to cancel. Assuming that, we can do a few thousand test per year, which should be plenty, but we'll monitor cost closely for the first few months.
I'm planning to make the logs a bit prettier, and potentially to …
> github: complete "switch proof runs to AWS"

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/RealTime_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/InvariantUpdates_H.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- spec/abstract/Ipc_A.thy
- spec/abstract/SchedContext_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This PR contains several lines of cleanups and improvements that I hope will help with the upcoming refill related proofs. The brief descriptions of the changes are as follows:
- more systematic use of updateSchedContext and its derivatives, mainly in refill related functions
- abstract spec cleanup to go along with the above, with some rewrite rules to take advantage of existing proofs
- more streamlined approach for indexing haskell scRefills (`updateAt`)
- rewrite rules for simplifying projections in the abstract side statements
- projection style wp rules for `getSchedContext`, `updateSchedContext` and others
- rewrite rules for `updateSchedContext`, etc., for managing some complex corres proofs
- rewrite some refill related corres in a more modular style
There are some smaller lemmas …
> Refill spec cleanup

- .github/workflows/proof.yml
This mirrors the corresponding commit on the master branch. We'll unfortunately only see if everything works properly after this is merged, but it seems to be going fine on `master` and PRs there.
The benefit is (should be) that the tests for MCS and PRs to the rt branch will be complete and run faster than on GitHub or Bamboo.
> run rt proofs on AWS

- misc/regression/run_tests.py
- run_tests
This switches on colour for GitHub and makes sure the proof output is actually placed into the corresponding log groups.
> More readable proof logs

- spec/abstract/RISCV64/ArchDecode_A.thy
- spec/abstract/X64/ArchDecode_A.thy
- spec/abstract/X64/Machine_A.thy
These are already imported upstream.
Signed-off-by: Rafal Kolanski <rafal.kolanski@proofcraft.systems>
> abstract x64+riscv: clean up some Word_Lib imports

- .github/workflows/external.yml
- .github/workflows/weekly-clean.yml
Further step in removing Bamboo:
- External means default.xml and vanilla Isabelle instead of internal TS Isabelle and devel.xml (1st and 15th of month).
- The weekly clean test runs without reading the proof image cache, writing back a fresh cache state (every Sun).
> github: scheduled external + weekly clean proofs

- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/refine/ARM/ArchAcc_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/StateRelation.thy
The main point of this PR is to change the existing AInvs DetSched projections (`tcb_of`, `sc_of` and `ep_of`) to from “definition” to “primrec”.
It also adds `ntfn_of` and `reply_of`, but they are not used yet.
Defining them as primrec seems to work well in terms of simplification and often results in simpler codes. The proof update for this change resulted in slight clean-up overall.
---
So far, tcb_of and sc_of in AInvs are case statements on kernel objects
defined as definitions, and they needed to be explicitly unfolded to
simplify to an option value.
Making them abbreviations is one way to automate the simplification, but
it has a drawback in that the case statement often has unfortunate
interaction with Map.empty, which is an abbreviation of its own, that
tends to produce …
> AInvs projections

- proof/invariant-abstract/DetSchedAux_AI.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/refine/ARM/Tcb_R.thy
`valid_ready_qs` is a statement about a thread in a ready_queue that
has three components: one is about the ready queue matching the domain
and the priority of the thread, and the others are the thread being in a
runnable state and has a released SC.
- this commit adds an abbreviation, `ready_queues_etcb_eq`, which states the validity of the first component only, i.e., "if in a ready_queue, it must be in the correct queue (corresponding to its domain and priority)"
- `etcb_eq` is used for better compatibility with current `valid_ready_qs`, for the time being
- `valid_ready_qs` preconditions in some wp rules are replaced with this, as they were too generous; this leads to some simplifications in proofs
- most notable one is the `not_queued` wp rules for `tcb_sched_dequeue`; it removes a …
> rt ainvs: valid_ready_qs substatement and cleanup

- docs/setup.md
Add a section on installation and configuration procedures of common Isabelle PIDE (jEdit) plug-ins.
Signed-off-by: Zoltan Kocsis <zoltan.kocsis@data61.csiro.au>
> docs: add setup instructions for PIDE plug-ins

- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
This refactors the proof runs into a separate run for the master branch (which has deployment) and development branches (currently RT and PRs).
For the test on the master branch, we need to make sure that all tests and the deployment action see the same revisions of all participating repos.
> github: deploy manifest after test on master

- .github/workflows/push.yml
- README.md
This adds badges to the repo README to show CI status overview of the master and rt branches.
It also adds the CI "push" checks to the rt branch, so the "no status" it currently shows should soon change to "passing".
> add CI badges

- misc/testboard/testboardpush
A few small improvements:
- use https URLs
- less noisy output
- add dry-run option
- print GitHub commit URL
The https URLs are needed because the test runner does not have ssh access to GitHub.
With this the testboard should work as before, and you have testboard access when you have push access to the gh-testboard repo.
(added lots of people as reviewers mostly to make sure you are aware this exists now again)
> testboard improvements

- proof/access-control/ARM/ArchRetype_AC.thy
- proof/crefine/ARM/Arch_C.thy
- proof/crefine/ARM/Invoke_C.thy
- proof/crefine/ARM/Machine_C.thy
- proof/crefine/ARM/Recycle_C.thy
- proof/crefine/ARM/Retype_C.thy
- proof/crefine/ARM_HYP/Arch_C.thy
- proof/crefine/ARM_HYP/Invoke_C.thy
- proof/crefine/ARM_HYP/Machine_C.thy
- proof/crefine/ARM_HYP/Recycle_C.thy
- proof/crefine/ARM_HYP/Retype_C.thy
- proof/drefine/KHeap_DR.thy
- proof/drefine/Untyped_DR.thy
- proof/infoflow/ADT_IF.thy
- proof/infoflow/IRQMasks_IF.thy
- proof/infoflow/Retype_IF.thy
- proof/invariant-abstract/ARM/ArchRetype_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchRetype_AI.thy
- spec/machine/ARM/MachineOps.thy
- spec/machine/ARM_HYP/MachineOps.thy
This updates the proofs for PR seL4/seL4#485, which fixes the correctness and security issue seL4/seL4#481.
In addition this PR contains one commit for adjacent cleanup and one commit to fix too-general machine assumptions.
The cache fix makes 3 new machine assumptions necessary: that more of the caching functions do not touch memory. This is derivable in ASpec and ExecSpec, but needs to be assumed for the corresponding C/asm-level machine ops.
Test with seL4/seL4#485
> proof update for cache fix PR

- .github/workflows/proof.yml
Save some CI cycles by not running the full proofs for each documentation update.
> github: no PR proof run for text file updates

- .github/workflows/push.yml
- README.md
This adds the badges and CI-runs for RT from the master branch so that the MCS CI badge shows actual status information.
> cherry-pick CI update from master

- .github/workflows/proof-deploy.yml
The repository_dispatch event will be generated in the [verification-manifest] repo when devel.xml is updated by anyone other than the seL4-ci user.
[verification-manifest]: https://github.com/seL4/verification-manifest
> github: trigger proof run on manifest update

- lib/Monad_WP/OptionMonad.thy
Another small addition to our `opt_map` lemma collection.
For state updates and others. The eta_contraction tweak from the last PR is also included.
> more opt map lemmas: updates

- lib/ExtraCorres.thy
- proof/invariant-abstract/KHeap_AI.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Schedule_R.thy
This PR restores the original `corres` rule for `whileLoop`; it seems that the rule which included crossing is unnecessary. A new `corres` rules for `whileLoop` with termination and `no_fail` conditions stated on the abstract side is added. This is then used to prove `headInsufficientLoop_corres`.
> New corres rule for whileLoop, and headInsufficientLoop_corres

- spec/abstract/Schedule_A.thy
Spec update for seL4 PR#467: "Don't check if old SC is still configured"
https://github.com/seL4/seL4/pull/467
- no proof update needed.
> spec update for seL4 #467

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/Ipc_AI.thy
- proof/invariant-abstract/KHeap_AI.thy
- proof/invariant-abstract/Tcb_AI.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- spec/abstract/IpcCancel_A.thy
- spec/abstract/Structures_A.thy
This adds a common selector `ep_queue` for `SendEP` and `RecvEP` in the definition of `endpoint` in Structures_A, consequently triggering the datatype package to generate a bunch of additional facts.
`get_ep_queue` and `valid_ep` are redefined using `ep_queue`. `queue_of` is removed because it is now a duplication of `ep_queue`.
Proof updates are mostly due to the above definition changes, and also from using `endpoint.case_eq_if` in place of locally defined lemmas to simplify the case distinction. Various versions are essentially the same and easily replaced by the `case_eq_if` lemma.
One interesting observation is that the Haskell `endpoint` is defined in a suboptimal order - first `RecvEP`, then `IdleEP`, followed by `SendEP`. It uses a shared queue selector, which is good, but we'd …
> use datatype package for abstract endpoint

- proof/refine/ARM/Ipc_R.thy
so that we stay with a nice decreasing trend :)
It turns out that the two of the three remaining sorries in Ipc_R are not needed. This PR deletes them.
The last sorry in Ipc_R is the one for `refill_unblock_corres`, which itself is done but waiting for the spec update. So we are almost finished with Ipc_R.
> Ipc_R cleanup

- README.md
- lib/EVTutorial/document/root.bib
- proof/access-control/README.md
- proof/asmrefine/README.md
- proof/capDL-api/README.md
- proof/crefine/README.md
- proof/dpolicy/Dpolicy.thy
- proof/drefine/README.md
- proof/infoflow/README.md
- proof/invariant-abstract/README.md
- proof/refine/README.md
- proof/sep-capDL/README.md
- spec/abstract/document/root.bib
- sys-init/README.md
- tools/README.md
- tools/asmrefine/README.md
- tools/autocorres/README.md
- tools/autocorres/doc/quickstart/Chapter1_MinMax.thy
- tools/autocorres/doc/quickstart/document/root.bib
- tools/autocorres/tools/release_files/README
PDFs and abstracts have moved to trustworthy.systems/
> READMEs: fix publication links

- lib/Corres_UL.thy
- lib/LemmaBucket.thy
- lib/Word_Lib/Word_Lemmas_Internal.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Schedule_R.thy
- spec/abstract/SchedContext_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
This proves `scheduleUsed_corres`.
I've rewritten `schedule_used` in the abstract to be monadic. I had hoped that the changes to AInvs would be minimal, but it turned out to be quite a lot of reorganising. Most of the more difficult word proofs (`schedule_used_no_overflow`, `schedule_used_odered_disjoint`, `schedule_used_window`) are pretty much unchanged. Some of the helper lemmas (`refill_budget_check_ordered_disjoint_helper'`, etc.) are new and replace older, clunkier versions. Nothing very exciting is going on in AInvs.
As expected after rewriting `schedule_used`, the `corres` rule was very straightforward. I had to slightly modify `refillAddTail_corres` to allow it to be applied in my lemma. This did not break anything in this branch, but perhaps it is being used elsewhere
> `scheduleUsed_corres`

- proof/invariant-abstract/DetSchedAux_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
This PR contains a further cleanup on DetSchedSchedule_AI, in particular, about `sched_context_resume`.
We know that, with `valid_sched` in the precondition, after calling `sched_context_resume` on a thread, the thread being schedulable implies it is ready. We had several versions of lemmas essentially stating the same thing. Those are consolidated into `sched_context_resume_schedulable_imp_ready`.
Also, the existing lemmas mostly argue for "ready and sufficient" but it is actually only the readiness that matters (that could have changed) under `valid_sched`. We carry around separately (as part of `valid_sched`) in `valid_refills` the fact that "active implies sufficient".
Somewhat related, I think it probably makes sense to modify the notion of `released` in our proof to drop the …
> sched_context_resume cleanup

- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/StateRelation.thy
This clears the last sorry in `PageTableDuplicates` by proving a lemma I've called `scBits_at_least_2`, which is a slight strengthening of `scBits_pos'`. It was a little annoying replacing the latter with the former, so I decided to keep the latter and prove it using the former. I'm not sure about the name for the new lemma but let me know if you have suggestions
> `PageTableDuplicates` last sorry

- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
Adding refillUnblockCheck_corres proof to Schedule_R under
a slightly different name (with ‘), so that it will be available for 
making progress with schedule_corres.
* to be renamed later, when "add refill_unblock_check everywhere" spec
change is finished, and the corres rule is integrated in proofs in
the later theory files (this process will remove one sorry)
Also with some tweaks (weakening assumptions). It might help to review commit by commit.
> Add refillUnblockCheck_corres proof

- proof/invariant-abstract/ARM/ArchDetSchedAux_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/RISCV64/ArchDetSchedAux_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/refine/ARM/Refine.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Schedule_R.thy
- spec/abstract/Schedule_A.thy
- spec/machine/ARM/MachineOps.thy
- spec/machine/MachineExports.thy
- spec/machine/RISCV64/MachineOps.thy
This makes `us_to_ticks` a definition, and axiomatizes some of the necessary properties, in a way that is hopefully consistent. If the axioms are all fine, I'd be happy to add a comprehensive comment which motivates each of the axioms. 
The sorry that I recently added to `Refine.thy` related to `valid_domain_list'` being true of the initial state is (easily) solved.
I was hoping that I'd be able to use a more uniform approach that gives no overflow and non zero properties for some collection of constants, but I wasn't able to find a way that was evidently consistent. Any ideas would be appreciated.
I was unsure of what to call `factor1` and `factor2`. Maybe `timer_frequency` would be suitable for `factor1`, but I'm not entirely sure. I wanted to avoid something as boring as …
> `us_to_ticks`

- misc/testboard/testboardpush
The AWS test runner does not have a GitHub ssh key, so can only access repositories via https.
> testboard: alwaus use https URLs

- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
Working on Refine fix for "add refill_unblock_check everywhere" change, I started to find the "is_active_sc2" precondition of the refill_unblock_check corres rule rather difficult to deal with. So, I had a look, and it turned out that we don't need it. The haskell assert is also removed.
This also contains a small cleanup in Schedule_R that removes duplications about `tcbReleaseDequeue`.
> Remove "is_active_sc" variants from preconditions / remove haskell assert

- proof/invariant-abstract/DetSchedSchedule_AI.thy
This PR moves `refill_unblock_check` lemmas in the way needed by the rest of the “add refill_unblock_check” changes.
I would like to this merged now so that I don’t need to keep redoing this... 😅 
Contains a bit of cleanup of unused lemmas I noticed along the way.
> Move refill_unblock_check lemmas

- misc/testboard/testboardpush
Had missed the `:` suffix in the git URL, so the ssh URL test would never succeed.
This is a fix for my prevision commit ce302e0c6586dedfc09d740e3b2c58ee37c77099 which didn't quite achieve what it promised.
> testboardpush: fix URL processing

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/Schedule_R.thy
- spec/abstract/ARM/ArchIpcCancel_A.thy
- spec/abstract/RISCV64/ArchIpcCancel_A.thy
- spec/abstract/SchedContext_A.thy
- spec/abstract/Schedule_A.thy
- spec/abstract/Sporadic_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This is the first PR of “adding refill_unblock_check” for thread activation/switching.
The C side change is now part of the "mcs: Add sporadic flag to SchedControl_Configure” commit.
This PR contains the following:
- definition of `if_cond_refill_unblock_check`/`ifCondRefillUnblockCheck`, which package up a call to `refill_unblock_check` with various guards encoded as two bool option parameters
- this encoding currently has unsimplified duplication due to temporary changes added to ease verification (see the commit message for the details)
- remove `refill_unblock_check` from `sched_context_yield_to`, proof fix for that
- add `refill_unblock_check` to `switch_sched_context`, proof fix for that
- add `ifCondRefillUnblockCheck_corres` rule, to be used in the sequel PRs
- also contains …
> “add refill_unblock_check” spec update, part I

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/RISCV64/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/SchedContext_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
This PR completes the `refill_unblock_check` spec change for `sched_context_bind_tcb`.
> “add refill_unblock_check” spec update, part II

- proof/crefine/ARM/Refine_C.thy
- proof/crefine/ARM_HYP/Refine_C.thy
- proof/crefine/RISCV64/Refine_C.thy
- proof/crefine/X64/Refine_C.thy
The PR seL4/seL4#473 removes Arch_finaliseInterrupt; this PR updates the C proofs accordingly.
Test with seL4/seL4#473
> crefine: remove Arch_finaliseInterrupt

- lib/Corres_UL.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/InvariantUpdates_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/StateRelation.thy
This proves `replyRemove_corres` and `replyPop_corres`.
These proofs are rather verbose. Both of them have a similar structure as that of `replyRemoveTCB_corres`, but, while it is probably not impossible to abstract the similarity and make use of it one way or another, it is quite fiddly to make everything work in details and I concluded that it is not a worthwhile investment at this point. Replacing the sorried version with the proved lemma with new preconditions went pretty smoothly.
> replyRemove_corres and replyPop_corres

- docs/setup.md
- tools/autocorres/README.md
- tools/autocorres/tools/release.py
- tools/autocorres/tools/release_files/ChangeLog
- tools/autocorres/tools/release_files/README
- tools/c-parser/INSTALL.md
- tools/c-parser/RELEASES.md
- tools/c-parser/mkrelease
- add release notes for C Parser 1.18 and Autocorres 1.8
- bump Isabelle2020 -> Isabelle2021 in docs and release notes
- adjust release scripts to work on MacOS and python3
> C parser tweaks

- proof/invariant-abstract/ARM/ArchSchedule_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/RISCV64/ArchSchedule_AI.thy
- proof/invariant-abstract/Schedule_AI.thy
- proof/refine/ARM/EmptyFail_H.thy
- proof/refine/ARM/InvariantUpdates_H.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
If everyone is happy with the (input) abbreviation `schedule_switch_thread_branch`, then I could use it for the `cur_sc_active` work, and use `schedule_switch_thread_branch_active_sc_tcb_at_cur_thread` in `schedule_cur_sc_active`.
`corres_fail'` should probably be moved to `Corres_UL.thy`. `corres_fail` there can be strengthen, too. So I could do that separately in another PR if people would like
> `schedule_corres`

- docs/conventions.md
Turns out we had not actually documented general variable names yet. This PR addresses that.
In a separate commit, there are markdown lint adjustments, and rewrap. To review those it is easiest to look at the "rich diff" that shows the rendered markdown, which should not actually change.
> Document variable name conventions

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/InvariantsPre_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/InvariantUpdates_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/SchedContext_A.thy
- spec/abstract/Schedule_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- also includes proofs for `schedContextBindNtfn` and `schedContextYieldTo_corres`
- resolves the issue of IPC buffer preconditions for `setConsumed_corres`
> prove `invokeSchedContext_corres`

- proof/invariant-abstract/AInvs.thy
- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/DetSchedAux_AI.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/KHeap_AI.thy
- proof/invariant-abstract/RISCV64/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Refine.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/Move_R.thy
- spec/abstract/KHeap_A.thy
- spec/abstract/Schedule_A.thy
This weakens the precondition of `akernel_invs` as described in VER-1301. This also renames `is_schedulable_bool` to `schedulable`, and introduces the abbreviation `ct_schedulable`.
I will continue on with the remainder of VER-1301, namely proving a Hoare triple for `call_kernel` with postcondition `ct_running s --> ct_schedulable s`
> Weaken `akernel_invs` precondition

- proof/refine/ARM/ArchAcc_R.thy
- proof/refine/ARM/Arch_R.thy
- proof/refine/ARM/CSpace1_R.thy
- proof/refine/ARM/CSpace_I.thy
- proof/refine/ARM/CSpace_R.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Untyped_R.thy
- proof/refine/ARM/VSpace_R.thy
- spec/design/skel/PSpaceStorable_H.thy
In master, we have
```
lemma objBitsKO_bounded[simp]:
"objBitsKO ko < word_bits”
```
which is implicitly used in many many places where we need to argue alignments, etc.
In MCS, we cannot have this fact without an assumption on the SC size. The decode function guarantees that the user-defined size for an SC object is bounded, but we need to pass around that information or something equivalent in one way or another. So far, we had a sorry in StateRelation.thy that basically gave this assumption for free. This PR removes this sorry and sorts the situation out properly.
This PR adds an invariant `pspace_bounded’`, which states that all the kernel object `ko` in the `ksPSpace` satisfy `objBitsKO ko < word_bits`. This essentially replaces the above fact in master.
`pspace_bounded'` goes along …
> pspace_bounded'

- lib/BCorres_UL.thy
- lib/Monad_WP/NonDetMonadVCG.thy
- proof/invariant-abstract/AInvs.thy
- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/BCorres_AI.thy
- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/Tcb_AI.thy
- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Interrupt_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/IpcCancel_A.thy
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/Notification.lhs
This adds a call to `refill_unblock_check` in `cancel_all_ipc` and `cancel_badged_sends` (via `restart_thread_if_no_fault` for the abstract spec), as well as in `cancel_all_signals`.
Also includes:
- bcorres rules for `maybeM` and `whileLoop`
- distribution rules for `pred_conj` and `pred_disj`
> "add refill_unblock_check” spec update, part IV

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- spec/abstract/Ipc_A.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
- spec/haskell/src/SEL4/Object/Notification.lhs
This is the last PR for the “add refill_unblock_check” spec update.
This adds `refill_unblock_check` via `if_cond_refill_unblock_check` in `send_signal`,  `receive_ipc`, and `do_reply_transfer`.
> "add refill_unblock_check” spec update, part VI

- spec/design/m-skel/RISCV64/MachineTypes.thy
- spec/machine/RISCV64/Platform.thy
In the rest of the proofs we use machine_word to refer to addresses.
This commit brings the machine definitions in line with that.
> riscv machine: use address size consistently

- proof/crefine/ARM/CSpace_RAB_C.thy
- proof/crefine/ARM_HYP/CSpace_RAB_C.thy
- proof/crefine/RISCV64/CSpace_RAB_C.thy
- proof/crefine/X64/CSpace_RAB_C.thy
The aim of the PR was readability, but it actually also brings the C more in line with the spec.
Test with seL4/seL4#321
> crefine: update for PR seL4/seL4#321

- spec/cspec/c/kernel.mk
The new docker containers that upgraded to gcc-10 use a different version of the gcc Arm toolchain (`arm-linux-gnueabi`).
> cspec: more compiler options

- proof/invariant-abstract/AInvs.thy
- proof/invariant-abstract/ARM/ArchDetSchedSchedule_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Ipc_AI.thy
- proof/invariant-abstract/RISCV64/ArchDetSchedSchedule_AI.thy
This shows that after `handle_event` and `preemption_path`, if the scheduler action is resume current thread, then the current thread is activatable. This will be important in showing that `cur_sc_offset_ready (consumed_timed s) s` and `cur_sc_offset_sufficient (consumed_time s) s` are true after `call_kernel`.
Many of the proofs are much more manual than I would have liked. I think this is because the statement is an implication, and because so many functions can potentially change the thread state of the current thread. `crunches` was unfortunately not very helpful at all. If anyone has any ideas on how to make these proofs less manual, please let me know.
> Current thread activatable

- docs/arch-split.md
This link is stable over Isabelle releases and can be updated once
the repo switches over to the next release.
> docs: use archive link for locale docs

- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Syscall_R.thy
- spec/design/skel/KernelStateData_H.thy
- spec/haskell/src/SEL4/API/Syscall.lhs
- spec/haskell/src/SEL4/Model/StateData.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This proves `he_invs’` (`invs’` for `handleEvent`).
This also introduces three asserts for the properties we want to have in `handleEvent`, after the calls to first phase `handleInvocation` prior to `handleRecv`. In the proof for `handleEvent_corres` (which will be in a separate PR after this), we can validate these asserted properties by crossing over from the abstract side. For the proof in this PR, only one of the three asserts is needed (`ct_active’`).
> Prove `he_invs’`

- proof/refine/ARM/Refine.thy
This proves `kernel_entry_invs`. 
This also makes some modificatin to `full_invs` and `full_invs'`. I'm not entirely sure that these are OK, or whether they're optimal. The final theorem, `refinement`, works without modification to either `ADT_H` or `ADT_A`, so I think something like what is here is OK.
I have made an effort to weaken the postconditions of a couple `invs'` lemmas which are still sorried. I don't think it's of any benefit to weaken the concrete guards of any of the remaining `corres` rules - and I think doing so would also break some of the proofs here which are a little annoying.
> `kernel_entry_invs`

- proof/refine/ARM/EmptyFail_H.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/Refine.thy
- proof/refine/ARM/Syscall_R.thy
- spec/design/skel/KernelStateData_H.thy
- spec/haskell/src/SEL4.lhs
- spec/haskell/src/SEL4/Model/StateData.lhs
This removes the last sorry in Syscal_R.thy.
The main proof and its helper lemmas make use of the asserts added in https://github.com/seL4/l4v/pull/409.
Update: this PR now contains #416 , which removes all the remaining sorries in Refine. Since this PR touches quite a lot of places in Syscall_R, it should make sense to review the two together rather than one after the other.
> prove handleEvent_corres + fix sorries in Refine.thy

- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
By default GitHub spawns a new test for each push event. To avoid hitting the maximum number of AWS instances too quickly, we run the PR and master proof tests only on the most recent push since the last test finished.
The concurrency exclusion is per git ref, i.e. separate PRs and separate branches still run tests concurrently.
> github: run AWS proofs only on most recent push

- proof/invariant-abstract/AInvs.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/EmptyFail_H.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Interrupt_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Refine.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/machine/ARM/MachineOps.thy
- spec/machine/MachineExports.thy
- spec/machine/RISCV64/MachineOps.thy
Most of the diff is entirely uninteresting - you can probably just ignore `DetSchedSchedule_AI.thy`. Apart from removing the various numbers, several lemmas which are now unnecessary have also been removed
> Remove parameter from `current_time_bounded`

- .github/workflows/proof.yml
${{github.ref}} will resolve to the base branch of the PR, not the
PR branch, so it is not useful for distinguishing PRs. The pull request
number will do the job.
> github: use PR number to distinguish pull requests

- spec/cspec/c/kernel.mk
This commit adds compiler prefixes for AArch64 so that the preprocess test finds the right cross compilers for this architecture.
> cspec: enable preprocess test for AArch64

- lib/Word_Lib/AARCH64/WordSetup.thy
- tools/c-parser/.gitignore
- tools/c-parser/INSTALL.md
- tools/c-parser/mkrelease
- tools/c-parser/standalone-parser/Makefile
- tools/c-parser/testfiles/AARCH64/imports/MachineWords.thy
- tools/c-parser/umm_heap/AARCH64/Addr_Type.thy
- tools/c-parser/umm_heap/AARCH64/ArchArraysMemInstance.thy
- tools/c-parser/umm_heap/AARCH64/TargetNumbers.ML
- tools/c-parser/umm_heap/AARCH64/Word_Mem_Encoding.thy
The setup for `L4V_ARCH`=`AARCH64` is identical to `RISCV64`, i.e. same word length, encoding, and endianness.
The setup includes Word_Lib and the standalone parser used for compile and preprocess checks in the seL4 repo.
> CParser and Word_Lib setup for AArch64

- spec/machine/ARM/Platform.thy
- spec/machine/ARM_HYP/Platform.thy
This matches the C code, as seen at https://github.com/seL4/seL4/blob/master/include/arch/arm/arch/32/mode/hardware.h#L72.
I explored aligning more of the platform constants, both for ARM and the other architectures, but it very rapidly became more work than what seemed worthwhile.
> arm+arm-hyp machine: align platform constants to C

- run_tests
- spec/cspec/c/Makefile
If L4V_FEATURES is not already set to something specific, set it to
MCS so we don't accidentally run the wrong configuration.
> rt run_tests: make sure L4V_FEATURES is set

- .github/workflows/proof-deploy.yml
In the l4v proof-deploy workflow, export the C graph-lang produced by SimplExportAndRefine. In the near future, this will feed into binary verification. Also add a new job matrix to produce C graph-lang for MCS configurations supported by binary verification.
> ci proof-deploy: save C graph-lang

- .github/workflows/binary.yml
- .github/workflows/proof-deploy.yml
- spec/cspec/c/kernel.mk
This adds a workflow that prepares the inputs needed by graph-refine. It is triggered at the end of a proof-deploy workflow. It collects C graph-lang artifacts from the proof-deploy workflow, and runs the decompiler to generate ASM graph-lang. Finally, it submits a job to a graph-refine back end over SSH.
Depends on https://github.com/seL4/ci-actions/pull/204.
> ci: add binary verification workflow

- docs/Style.thy
Include an update to use that style in the style file itself.
We are so far using multiple different comment and text styles in the l4v repository. This is an attempt at defining a single style that we can converge things to.
Main objectives:
- make sure most comments show up in PDF/HTML documents (-> prefer `text` over `(* .. *)`) 
- preserve some vertical space without making everything look completely compressed (-> don't use an entire line on only. the closing bracket; everything on the same line for one-line comments)
- visual separation for long comments (-> indent by 2)
Please excuse the large diff, the only really new bit is the text under "Text and comments". The rest is updating the style file to use the style.
> docs: text and comment style

- lib/Monad_WP/NonDetMonadVCG.thy
- proof/invariant-abstract/ARM/ArchArch_AI.thy
- proof/invariant-abstract/ARM/ArchRetype_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchArch_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchDetSchedAux_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchDeterministic_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchRetype_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchVCPU_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/RISCV64/ArchArch_AI.thy
- proof/invariant-abstract/RISCV64/ArchRetype_AI.thy
- proof/invariant-abstract/Untyped_AI.thy
- proof/invariant-abstract/X64/ArchArch_AI.thy
- proof/invariant-abstract/X64/ArchRetype_AI.thy
This adds the new invariant `valid_cur_vcpu` that says that the active current vcpu is the vcpu of the current thread.
> `valid_cur_vcpu`

- .github/workflows/external.yml
- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
`ci-actions/aws-proofs` no longer excludes the AutoCorresSEL4 session by default, so we no longer need to provide a fake argument to the session parameter to not exclude it.
This is significant, because we now want the default to be non-verbose since we're running multiple sessions in parallel.
> github: changed AutoCorresSEL4 default

- .github/workflows/binary.yml
Don't assume that artifacts are ready for download, since the job that triggered a binary workflow might not have finished. Instead, retry artifact download for up to 10 minutes.
Links to example test runs where the artifacts were:
- [not present](https://github.com/seL4/l4v-bv-ci/runs/5784102796?check_suite_focus=true)
- [present](https://github.com/seL4/l4v-bv-ci/runs/5784065354?check_suite_focus=true)
> ci binary: wait for artifacts

- proof/Makefile
Both `AInvs` and the refinement chain need the generated files necessary for `ASpec` and `ExecSpec`. We could depend on `ASpec` directly, but that would mess with Isabelle being able to schedule sessions as it wants them, and depending on all of `ExecSpec` is too much for `AInvs`.
> add missing Makefile dependencies

- misc/regression/compare.py
This adds a small script that parses two run_tests logs for session times and compares them.
Example output in the comments of #452
> regression: tool for comparing session times

- proof/refine/ARM/CSpace1_R.thy
- proof/refine/ARM/CSpace_R.thy
- proof/refine/ARM_HYP/CSpace1_R.thy
- proof/refine/ARM_HYP/CSpace_R.thy
- proof/refine/RISCV64/CSpace1_R.thy
- proof/refine/RISCV64/CSpace_R.thy
- proof/refine/X64/CSpace1_R.thy
- proof/refine/X64/CSpace_I.thy
- proof/refine/X64/CSpace_R.thy
- proof/refine/X64/KHeap_R.thy
Not finished yet, but maybe useful to look at already before we apply this to the other architectures and MCS.
There is also more work to be done still in the second CSpace theory (`CSpace_R`), but I hope that the same ideas will apply.
I haven't measured the actual time gain, but it feels interactively reasonably fast now, whereas before it was definitely in "get a cup of tea" territory.
(this is accidentally on top of #451, which hopefully is merged soon and will disappear here).
> Speed up CSpace1_R proofs

- docs/README.md
- docs/crefine-notes.md
We import some documentation with notes/issues on the refinement from
Haskell to C.
The file is a Markdown-ified version of previous documentation hosted at
UNSW.
> Import documentation: CRefine notes

- spec/tests.xml
-  give more time for downloading and compiling dependencies for runs  where these are not cached.
-   make sure we're catching all dependencies that are declared for `design-spec` in the top-level Makefile. In particular, we want `c-config` to run at least once before either `ASpec` or `ExecSpec` run it, to make sure these two are not racing on config generation in `-j 2`.
> run_tests: HaskellKernel and C config

- proof/invariant-abstract/AARCH64/ArchBCorres_AI.thy
- proof/invariant-abstract/AARCH64/ArchCrunchSetup_AI.thy
- proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
- proof/invariant-abstract/AARCH64/ArchLevityCatch_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- spec/abstract/AARCH64/ArchVSpaceAcc_A.thy
- spec/abstract/AARCH64/Arch_Structs_A.thy
- spec/abstract/AARCH64/Init_A.thy
- spec/haskell/src/SEL4/Kernel/VSpace/AARCH64.hs
- spec/haskell/src/SEL4/Model/StateData/AARCH64.hs
- spec/machine/AARCH64/Platform.thy
This PR fills in abstract invariants up to `ArchInvariants_AI` for the `AARCH64` target (AArch64, FPU, VCPU, no MMU). This means the architecture-specific invariants are specified, and the basic properties hold.
> Preliminary formulation of abstract invariants for AARCH64

- docs/ROOT
- docs/Style.thy
Document that and why we should prefer `case` over `primrec`/`fun` for non-recursive definitions with pattern matching.
> docs: split_simps and case over fun/primrec

- proof/crefine/ARM/Ipc_C.thy
- proof/crefine/ARM/Recycle_C.thy
- proof/crefine/ARM/Retype_C.thy
- proof/crefine/ARM_HYP/Ipc_C.thy
- proof/crefine/ARM_HYP/Recycle_C.thy
- proof/crefine/ARM_HYP/Retype_C.thy
- proof/crefine/Move_C.thy
- proof/crefine/RISCV64/Ipc_C.thy
- proof/crefine/RISCV64/Recycle_C.thy
- proof/crefine/RISCV64/Retype_C.thy
- proof/crefine/X64/Ipc_C.thy
- proof/crefine/X64/Recycle_C.thy
- proof/crefine/X64/Retype_C.thy
The lemma map_to_ko_atI2 was exactly the same as map_to_ko_atI.
> crefine: remove duplicate lemma

- lib/Crunch.ML
- lib/test/Crunch_Test_NonDet.thy
Add support to crunch_ignore so that multiple instances can be added to and removed from simultaneously.
There is an example in [lib/test/Crunch_Test_NonDet.thy](https://github.com/seL4/l4v/compare/master...corlewis:master#diff-a70563cedfb16fff3aebf5def8732ad4a8133223084b0330635b1b4b907a41f7) of this being used.
> lib: add syntax to crunch_ignore multiple instances

- lib/Crunch.ML
- lib/Crunch_Instances_NonDet.thy
- lib/Crunch_Instances_Trace.thy
- lib/crunch-cmd.ML
These warn when attempting to add a constant to crunch_ignore that is
already being ignored, or when removing a constant that is not being ignored.
> lib: add warnings to crunch_ignore

- misc/stats/fixme-count.sh
- misc/stats/sorry-count.sh
The sorry-count script used to live in ci-actions/aws-proofs and still needs to be removed there. The FIXME count script is new.
Both start counting at the repo root and report per major interesting directory (e.g. `spec/abstract` or `proof/refine`). The FiXME count includes a total over the entire repo.
> add sorry + FIXME count scripts

- lib/crunch-cmd.ML
- proof/invariant-abstract/RISCV64/Machine_AI.thy
I wasn't sure whether to put more tags on this commit. I changed one line in `invariant-abstract` which I already knew was explicitly due to this issue, but I'm sure that there are others that I don't know about and I don't want to go looking for them. Should I add `ainvs` to the tag?
> lib: fix crunch to only apply attributes once

- lib/BCorres_UL.thy
- lib/Crunch_Instances_NonDet.thy
- lib/Crunch_Instances_Trace.thy
- lib/crunch-cmd.ML
- lib/test/Crunch_Test_NonDet.thy
- lib/test/Crunch_Test_Trace.thy
- proof/invariant-abstract/ARM/Machine_AI.thy
- proof/invariant-abstract/ARM_HYP/Machine_AI.thy
- proof/invariant-abstract/RISCV64/Machine_AI.thy
- proof/invariant-abstract/X64/ArchVSpace_AI.thy
- proof/invariant-abstract/X64/Machine_AI.thy
- proof/refine/ARM_HYP/CNodeInv_R.thy
- proof/refine/ARM_HYP/Ipc_R.thy
- proof/refine/ARM_HYP/VSpace_R.thy
Some properties that crunch can be used for have different legacy naming schemes. This commit makes it possible for different instances of crunch to be configured for either prefix or suffix naming.
> lib: add a crunch option for naming schemes

- tools/haskell-translator/lhs_pars.py
- tools/haskell-translator/make_spec.sh
- tools/haskell-translator/msgs.py
- tools/haskell-translator/pars_skl.py
This is the second round of improvements for error/warning reporting in the Haskell translator:
- suppress warnings for types we know about
- remove warnings for intentionally missing X64 CPP setup
- use a status line for file progress output when running in a terminal. This should reduce clutter when run interactively.
- provide file name for warnings and errors
> fewer haskell translator warnings

- spec/haskell/.gitignore
- spec/haskell/Makefile
- spec/haskell/SEL4.cabal
- spec/haskell/src/Data/BinaryTree.hs
- spec/haskell/src/SEL4/Machine/RegisterSet/AARCH64.hs
- spec/haskell/src/SEL4/Machine/RegisterSet/ARM.lhs
- spec/haskell/src/SEL4/Machine/RegisterSet/RISCV64.hs
- spec/haskell/src/SEL4/Machine/RegisterSet/X64.lhs
- spec/haskell/src/SEL4/Model/PSpace.lhs
- spec/haskell/src/SEL4/Model/StateData.lhs
- spec/haskell/src/SEL4/Object/CNode.lhs
- spec/haskell/src/SEL4/Object/Interrupt.lhs
- spec/haskell/src/SEL4/Object/ObjectType.lhs
- spec/haskell/src/SEL4/Object/ObjectType/AARCH64.hs
- spec/haskell/src/SEL4/Object/ObjectType/ARM.lhs
- spec/haskell/src/SEL4/Object/ObjectType/RISCV64.hs
- spec/haskell/src/SEL4/Object/ObjectType/X64.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
- spec/haskell/src/SEL4/Object/Untyped.lhs
- spec/haskell/src/Simulation/FFIBindings.hs
- spec/haskell/stack.yaml
- tools/haskell-translator/caseconvs
- tools/haskell-translator/lhs_pars.py
This is mostly to reduce build time/cache size for docker images.
Main change with ghc 9.0.2 is that `fail` now requires the class `MonadFail` instead of just `Monad` and a few small surface syntax tweaks. As far as I can see, there is no impact on the Isabelle side.
> update to ghc 9.0.2

- .github/workflows/proof-deploy.yml
This removes the mcs-export matrix job from the proof-deploy workflow,
as the first step towards solving seL4/l4v#497. This should unblock
verification manifest deployments.
The mcs-export job was added to the proof-deploy workflow to perform
SimplExportAndRefine for binary verification targets. It took a short
cut, using the master branch of l4v to perform SimplExportAndRefine for
MCS configurations, since there were no differences between rt and
master that were relevant to SimplExportAndRefine. This is no longer the
case, because MCS seL4 C code now contains C parser annotations that use
symbols only available in the rt branch of l4v.
We intend to add an equivalent job that uses the rt branch of l4v for
MCS SimplExportAndRefine, but are still working out the best way to do
that. …
> ci: temporarily remove mcs-export from proof-deploy

- proof/crefine/Move_C.thy
- proof/crefine/RISCV64/Ctac_lemmas_C.thy
- proof/crefine/RISCV64/IsolatedThreadAction.thy
- proof/crefine/RISCV64/SR_lemmas_C.thy
- proof/crefine/RISCV64/StateRelation_C.thy
- proof/refine/RISCV64/KHeap_R.thy
This sorries until the beginning of `CSpace_C.thy`. In fact, only one sorry is added, namely `setCurThread_isolatable`, which is probably no longer true (if people think it is preferable, I can simply remove this lemma).
Many lemmas involving `setObject` and `getObject` have been updated now that they involve the reader monad.
> Sorrying till `CSpace_C.thy`

- proof/crefine/RISCV64/Arch_C.thy
- proof/crefine/RISCV64/StateRelation_C.thy
- proof/crefine/RISCV64/VSpace_C.thy
- proof/infoflow/refine/RISCV64/Example_Valid_StateH.thy
- proof/refine/RISCV64/ADT_H.thy
- proof/refine/RISCV64/StateRelation.thy
- spec/haskell/src/SEL4/Kernel/VSpace/RISCV64.hs
- spec/haskell/src/SEL4/Machine/Hardware/RISCV64.hs
According to the RISC-V spec, PageTablePTEs must have the access,
dirty, and user bits set to 0. This means that
- there is no user attribute that can be set on PageTablePTEs
(removed from Haskell spec)
- the encoding for PageTablePTEs in C must have 0 in these fields
instead of 1.
See PR seL4/seL4#880 for discussion and corresponding C changes.
Test with seL4/seL4#880
> riscv haskell+proofs: fix PageTablePTE encoding

- proof/crefine/RISCV64/Detype_C.thy
- proof/crefine/RISCV64/SR_lemmas_C.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/RISCV64/Detype_R.thy
- proof/refine/RISCV64/KHeap_R.thy
- proof/refine/RISCV64/StateRelation.thy
- proof/refine/RISCV64/TcbAcc_R.thy
- spec/abstract/Structures_A.thy
- spec/cspec/RISCV64/Kernel_C.thy
- spec/design/skel/KernelStateData_H.thy
- spec/haskell/src/SEL4/Model/PSpace.lhs
- spec/haskell/src/SEL4/Model/StateData.lhs
- spec/haskell/src/SEL4/Object/Structures.lhs
This sorries `Detype_C.thy`, adding one sorry related to `refill_buffer_relation`.
The size of the scheduling context structs is updated in the abstract spec and the Haskell.
An assert was added to `deleteObjects` to help resolves an assumption in the `delete_locale` locale.
> Sorry `Detype_C`

- lib/NICTATools.thy
- lib/Named_Eta.thy
- lib/ROOT
- lib/test/Named_Eta_Test.thy
These allow selective eta-contraction in the goal based on the bound
variable's name. The `no_name_eta` method speficially targets
abstractions where the variable has no name, which can come up in
complicated unification scenarios.
These nameless abstractions can cause symbolic execution lemmas to no
longer pick up on the name of the bound variable in do-notation,
requiring multiple rename_tac invocations.
Co-authored-by: Gerwin Klein <gerwin.klein@proofcraft.systems>
Signed-off-by: Rafal Kolanski <rafal.kolanski@proofcraft.systems>
> lib: add named_eta and no_name_eta methods

- docs/setup.md
They moved it from `/README` to `/`
> docs: update Haskell stack link

- lib/ROOT
- lib/Rules_Tac.thy
- lib/test/Rules_Tac_Test.thy
In `Rules_Tac`, add a `rules_tac` which is `rule_tac` but with the ability to instantiate the same variable name in multiple theorems.
Also add the specialised `single_instantiate_tac` which allows using the above mechanism to instantiate a specific variable name in a specific set of theorems (e.g. "rv" in a set of symbolic-execution lemmas).
Note1: Rules_Tac.thy and Rules_Tac_Tests.thy are a bit small. We should consider whether we want every little method and tactic to show up with its own file in lib, or whether grouping them by some kind of topic or size (e.g. Small_Methods.thy) is more appropriate
Note2: this PR is used by the monadic_rewrite overhaul and will need to be merged before it.
> lib: add rules_tac and related multi-thm instantiators

- proof/access-control/CNode_AC.thy
- proof/access-control/Finalise_AC.thy
- proof/bisim/Syscall_S.thy
- proof/dpolicy/Dpolicy.thy
- proof/drefine/Arch_DR.thy
- proof/drefine/CNode_DR.thy
- proof/drefine/Corres_D.thy
- proof/drefine/Finalise_DR.thy
- proof/drefine/Intent_DR.thy
- proof/drefine/Ipc_DR.thy
- proof/drefine/KHeap_DR.thy
- proof/drefine/Tcb_DR.thy
- proof/drefine/Untyped_DR.thy
- proof/infoflow/ADT_IF.thy
- proof/infoflow/CNode_IF.thy
Several proof directories on the rt branch had diverged from master in unexpected ways. This commit manually brings them back in sync.
The specific directories are access-control, bisim, dpolicy, drefine, and infoflow.
> MCS: synchronise proof directories with master

- lib/Value_Type.thy
- tools/autocorres/tools/release.py
- tools/autocorres/tools/release_files/ChangeLog
- tools/autocorres/tools/release_files/README
- tools/c-parser/RELEASES.md
This PR mostly has changelong updates and small tweaks to include AARCH64 and make the release scripts pass.
The actual release files can be uploaded once this PR is merged.
> Autcorres 1.9 + CParser 1.19 release

- proof/invariant-abstract/AARCH64/ArchAcc_AI.thy
- proof/invariant-abstract/AARCH64/ArchDetype_AI.thy
- proof/invariant-abstract/AARCH64/ArchEmptyFail_AI.thy
- proof/invariant-abstract/AARCH64/ArchFinalise_AI.thy
- proof/invariant-abstract/AARCH64/ArchInterrupt_AI.thy
- proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
- proof/invariant-abstract/AARCH64/ArchIpc_AI.thy
- proof/invariant-abstract/AARCH64/ArchRetype_AI.thy
- proof/invariant-abstract/AARCH64/ArchSchedule_AI.thy
- proof/invariant-abstract/AARCH64/ArchSyscall_AI.thy
- proof/invariant-abstract/AARCH64/ArchTcb_AI.thy
- proof/invariant-abstract/AARCH64/ArchUntyped_AI.thy
- proof/invariant-abstract/AARCH64/ArchVCPU_AI.thy
- proof/invariant-abstract/AARCH64/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/AARCH64/ArchVSpace_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/LevityCatch_AI.thy
- proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
- proof/invariant-abstract/Retype_AI.thy
- spec/abstract/AARCH64/ArchVSpace_A.thy
- spec/abstract/AARCH64/Arch_Structs_A.thy
- spec/haskell/src/SEL4/Kernel/VSpace/AARCH64.hs
This PR clears all sorries up to the theory `ArchFinalise_AI` and in addition clears `ArchEmptyFail`, `ArchInterrupt`, `ArchTcb`, `ArchIPC`, and `ArchVSpaceEntries`.
In the spec, we add an additional read operation to model the atomic ASID pool field update that happens C, and we correct the definition of `arch_is_frame_type` to properly take into account the presence of VCPU objects.
> progress on aarch64 invariants

- .github/workflows/aarch64.yml
- .github/workflows/external.yml
- .github/workflows/pr.yml
- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
- .github/workflows/trigger.yml
- .github/workflows/weekly-clean.yml
Upgrade to node16 actions to reduce warnings on CI.
> github: bump github action dependencies

- tools/c-parser/standalone-parser/Makefile
The default (=first) Makefile target for the standalone parser was `all`, which gains additional dependencies in the included Makefile. We want `make` in this directory to just build the standalone parser, so we set `stp_all` as the default.
> c-parser: fix default target for standalone parser

- tools/haskell-translator/lhs_pars.py
- tools/haskell-translator/make_spec.sh
MCS has a few more instances of type assignments that are handled manually, and the lambda `\usage` confuses the C preprocessor (potential unicode escape sequence). Switch these off, because we know they are fine.
> haskell-translator: suppress known-good warnings

- lib/Corres_UL.thy
- lib/LemmaBucket.thy
- lib/Lib.thy
- lib/MonadicRewrite.thy
- lib/NonDetMonadLemmaBucket.thy
- proof/capDL-api/Invocation_DP.thy
- proof/crefine/ARM/Fastpath_C.thy
- proof/crefine/ARM_HYP/Fastpath_C.thy
Changes isLeft, isRight, theLeft, and theRight to abbreviations and updates the proofs accordingly.
Proof changes are small, the larger one in capDL-api is mostly fixing broken indentation of the original proof.
> modernise sum type discriminators+selectors

- lib/CLib.thy
- lib/HaskellLib_H.thy
- lib/Lib.thy
- lib/ROOT
- lib/clib/BitFieldProofsLib.thy
- lib/clib/LemmaBucket_C.thy
- proof/crefine/lib/CToCRefine.thy
- spec/cspec/TypHeapLimits.thy
- tools/asmrefine/ExtraSpecs.thy
- tools/asmrefine/FieldAccessors.thy
- tools/asmrefine/GraphLang.thy
- tools/asmrefine/GraphRefine.thy
- tools/autocorres/AbstractArrays.thy
- tools/autocorres/CCorresE.thy
- tools/autocorres/CorresXF.thy
- tools/autocorres/ExceptionRewrite.thy
- tools/autocorres/ExecConcrete.thy
- tools/autocorres/HeapLift.thy
- tools/autocorres/L2Defs.thy
- tools/autocorres/MonadMono.thy
- tools/autocorres/NatBitwise.thy
- tools/autocorres/NonDetMonadEx.thy
- tools/autocorres/TypHeapSimple.thy
- tools/autocorres/TypeStrengthen.thy
- tools/autocorres/WordAbstract.thy
- tools/autocorres/tests/examples/Memcpy.thy
- tools/c-parser/ROOT
- tools/c-parser/TypHeapLib.thy
This doesn't fully implement #545 yet, but it's worth a check point.
- remove all dependencies from C parser to Lib session
- reduce dependencies of AutoCorres session to theories that can be moved out of Lib
The only Lib imports in AutoCorres are now:
- `CLib.LemmaBucket_C` which can be moved to `CParser` session
- `Lib.Monad_Equations` and `Lib.More_NonDetMonadVCG` which can be moved to `Monads` session
- `CLib.LemmaBucket_C` itself depends on `Lib.CLib` which has no further dependencies. Naming and destination of `CLib.thy` still unclear. Ideas welcome.
> reduce AutoCorres dependencies

- lib/Monads/OptionMonad.thy
- proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
- proof/invariant-abstract/RISCV64/ArchInvariants_AI.thy
- proof/refine/RISCV64/ArchAcc_R.thy
- proof/refine/RISCV64/VSpace_R.thy
- removes `opt_mapE` from `[elim!]`, but leaves other reader option monad elims in the set. The reasoning is that `opt_mapE` is mostly used for projections that you want to keep stable in assumptions, but the others are used for option monads, which you usually want to break up.
- minimal proof fixes in RISCV64 and AARCH64
> remove opt_mapE from global `[elim!]` set 

- .github/workflows/proof-deploy.yml
The current xmllint tools don't like %0A to mean newline so are crashing.
> Unescape verification-manifest.xml before saving it

- .github/workflows/proof-deploy.yml
Need to check out the ci-actions repo first (where the nl-unescape.sh script is located).
This should get the trigger action working to the degree that `xmllint` doesn't complain any more.
> github: provide nl-unescape script to BV trigger job

- README.md
We have so far not been mentioning L4V_ARCH in the instructions and haven't pointed out which sessions need generated input.
Add this information to the instructions.
(supersedes #585)
> readme: explain L4V_ARCH and spec generation

- spec/cspec/c/gen-config-thy.py
- spec/cspec/c/kernel.mk
seL4/seL4#975 slightly changed how the config headers are generated. They now need a (short) `ninja` build step and they produce less spaces in the header file.
This PR adjusts for that, but does not read the generated json file yet, which should be more robust in the future than parsing the C header.
> cspec: adjust Kernel_Config generation

- proof/crefine/ARM_HYP/Arch_C.thy
- proof/crefine/ARM_HYP/SR_lemmas_C.thy
- proof/crefine/ARM_HYP/VSpace_C.thy
- spec/cspec/c/gen-config-thy.py
Extract the numeric value physBase_raw from the generated header gen_headers/plat/machine/devices_gen.h and provide it as the constant physBase in Kernel_Config.thy.
In C this will later match up with the value returned by physBase().
Test with: seL4/seL4#983
(Test will fail until we have adjusted the proofs for use of `physBase()`)
> cspec: extract physBase from C headers

- .gitignore
- spec/cspec/README.md
- spec/cspec/c/kernel.mk
- spec/cspec/c/overlays/AARCH64/default-overlay.dts
- spec/cspec/c/overlays/ARM/default-overlay.dts
- spec/cspec/c/overlays/ARM_HYP/default-overlay.dts
- spec/cspec/c/overlays/README.md
- spec/cspec/c/overlays/RISCV64/default-overlay.dts
Add mechanism for adding overlay.dts files to the l4v build for all architectures apart from X64 (which does not use dts files).
For example, place a file `overlays/ARM/overlay.dts` into the tree and the build will pick it up as custom overlay file with the correct proof session dependencies.
If no file is provided, an empty default overlay file is used.
This mechanism is useful for a multi-kernel setup that uses overlays to restrict the available memory regions per CPU node.
> cspec: provide mechanism for adding dts overlays

- spec/cspec/c/kernel.mk
Previous commit 1a7eb921110da missed two instances.
(We were still getting BV artifact export errors that are masked in the PR tests, because they don't usually need to re-run SimplExportAndRefine)
> cspec: make remaining relative paths absolute

- spec/haskell/src/Data/WordLib.lhs
- spec/haskell/src/SEL4/Kernel/VSpace/AARCH64.hs
- spec/haskell/src/SEL4/Object/VCPU/AARCH64.hs
- spec/haskell/src/SEL4/Object/VCPU/ARM.lhs
- move countTrailingZeros to Data.Word_Lib (make generic, also remove from ARM_HYP)
- defer reader monad to MCS
- eliminate isValidNativeRoot
> resolve some of the AARCH64 Haskell FIXMEs

- lib/Lib.thy
- proof/invariant-abstract/AARCH64/ArchKHeap_AI.thy
Terms of the form "(if P then None else Some _) = None" and all their
combinations can be simplified automatically. For the "Some" variants
we provide a safer form, e.g.:
((if P then Some x else None) = Some x) = P
because
((if P then Some x else None) = Some y) = (P /\ x = y)
adds an equation to the goal that the simplifier will pick up. That is
often wanted, but sometimes leads to non-termination.
Even the safer form can lead to non-termination if P is an equation, so
none of these are [simp] by default.
- `if_option_eq` is the safer set
- `if_option` is the less safe set that simplifies more
This resolves one of the FIXMEs int he AARCH64 proofs.
> simp setup for If and option

- proof/invariant-abstract/AARCH64/ArchAcc_AI.thy
- proof/invariant-abstract/AARCH64/ArchKHeap_AI.thy
- proof/invariant-abstract/AARCH64/ArchRetype_AI.thy
- proof/invariant-abstract/AARCH64/ArchVSpace_AI.thy
Keep simp set more in line with other architectures.
Using `if_option_eq` or `if_option` locally turns out to work fine and a relatively small change.
> aarch64 ainvs: avoid global [simp] for if_option_eq

- .github/workflows/external.yml
A previous commit added a new job which depended on a job that didn't exist. We rename the `all` job to `proofs` for consistency with other workflows.
Fixes #611.
> ci: Fix broken external workflow

- spec/tests.xml
Make the C kernel config extraction visible as a separate test session in `run_tests` so that `run_tests` can do concurrency control for it.
> tests: add kernel-config session

- proof/access-control/README.md
- proof/bisim/README.md
- proof/capDL-api/README.md
- proof/crefine/README.md
- proof/drefine/README.md
- proof/infoflow/README.md
- proof/invariant-abstract/README.md
- proof/refine/README.md
- proof/sep-capDL/README.md
- spec/abstract/README.md
- spec/capDL/README.md
- spec/cspec/README.md
- spec/design/README.md
- spec/sep-abstract/README.md
- spec/take-grant/README.md
- sys-init/README.md
- tools/autocorres/README.md
- tools/c-parser/Simpl/README.md
Avoid mixing `isabelle`, `make`, and `run_tests` invocations. Standardise on `run_tests` and mention `L4V_ARCH` each time to indicate that you can and should set `L4V_ARCH`.
> READMEs: use run_tests consistently in READMEs

- README.md
- docs/setup.md
- Provide one flattened set of instructions to install all dependencies, google repo, manifest checkout, and Isabelle installation. At the end of it, link to the description on how to run the proofs.
- Remove jEdit section from main README, since it's duplicated in `setup.md`.
- update Google repo link to a page that contains installation instructions
This doesn't do anything yet about `mlton` on Apple silicon. Next steps would be to provide a binary for that and to turn this page into a script instead.
> README: flatten installation instructions

- docs/setup.md
Installation instructions for Intel and Apple Silicon Mac are now equal
> docs/setup: mlton for M1 now available on homebrew

- proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
- spec/machine/AARCH64/Arch_Kernel_Config_Lemmas.thy
The condition `pptrBase < kernelELFBase` is not required on AArch64 in hyp mode and was left over from the initial RISC-V setup.
Since this check does fail for some platforms (where physBase = 0 and consequently pptrBase = kernelELFBase) we remove it here.
(Failing platforms discovered in seL4/seL4#1001)
> aarch64 ainvs: remove unused physBase lemmas

- lib/Word_Lib/Bitwise.thy
- lib/Word_Lib/Bitwise_Signed.thy
- lib/Word_Lib/Boolean_Inequalities.thy
- lib/Word_Lib/Many_More.thy
- lib/Word_Lib/More_Bit_Ring.thy
- lib/Word_Lib/More_Word.thy
- lib/Word_Lib/More_Word_Operations.thy
- lib/Word_Lib/Sgn_Abs.thy
- lib/Word_Lib/Word_EqI.thy
- lib/Word_Lib/Word_Lemmas.thy
- lib/Word_Lib/Word_Lib_Sumo.thy
- define `sgn` and `abs`
- prove equalities between boolean and arithmetic operations (in rings, so applies to `int` and `word`). Examples include
```
x + y = (x OR y) + (x AND y)
x + y = (x XOR y) + 2 * (x AND y)
x - y = (x AND NOT y) - (NOT x AND y)
x XOR y = (x OR y) - (x AND y)
x OR y = (x AND NOT y) + y
```
etc. This should be a fairly complete set.
- prove all inequalities between binary boolean functions on words (e.g. `a && b <= a || b` etc)
- add laws about min, max, and NOT 
- some cleanup in `More_Word` (because some of these are now subsumed by ring lemmas) and doc improvements
- a lemma to turn `a < b` into a bitwise expression on abstract word lengths
Provides only additional rules or changes proofs, but should not change the proof context in any destructive way.
> Word_Lib improvements

- .github/workflows/external.yml
- .github/workflows/proof-deploy.yml
- .github/workflows/push.yml
- .github/workflows/weekly-clean.yml
The worklow_dispatch trigger adds a button in the GitHub UI that lets one trigger the workflow manually. Useful for testing the workflows.
> github: add manual triggers for testing

- docs/Style.thy
This is a first stab at stating what's going on with the two styles, and could really use more than one round of feedback.
Please ignore the `by` commit, PR is in progress for that one.
The part about `Inner-syntax indentation is not automatable in the general case, so our goal is to help ...` isn't clear where it should go, help welcome.
> Style guide: left- vs right-wrapping of operators

- spec/haskell/Makefile
- spec/tests.xml
Provide L4V_ARCH targets in the Haskell Makefile and constrain run_tests to use only the current L4V_ARCH, to avoid building all architectures in all tests.
A manual invocation of just `make` will still build all architectures for easier checking.
> haskell: constrain run_tests to current L4V_ARCH

- spec/cspec/c/Makefile
- spec/cspec/c/kernel.mk
L4V_PLAT selects a platform variation within a L4V_ARCH. This mostly affects which seL4 cmake config file is loaded when building config data and the kernel C code. This in turn affects (and will rebuild) ASpec, ExecSpec, and CSpec.
Examples:
L4V_ARCH=ARM L4V_FEATURES="" L4V_PLAT=""
will load `ARM_verified.cmake`
L4V_ARCH=ARM L4V_FEATURES="" L4V_PLAT=imx8mm
will load `ARM_imx8mm_verified.cmake`, and
L4V_ARCH=ARM L4V_FEATURES=MCS L4V_PLAT=imx8mm
will load `ARM_MCS_imx8mm_verified.cmake`.
When `L4V_PLAT` is empty, everything should work as it has so far.
See also https://github.com/seL4/ci-actions/pull/275 and #638
> cspec: introduce L4V_PLAT

- spec/cspec/c/export-kernel-builds.py
CI is introducing an `L4V_PLAT` variable to support proof runs across more platform configurations. This commit incorporates `L4V_PLAT` into the paths generated by `export-kernel-builds.py`, to ensure that exported builds can be disambiguated.
See also https://github.com/seL4/ci-actions/pull/275.
> cspec: Use L4V_PLAT in build export script

- run_tests
- echo L4V_FEATURES and L4V_PLAT when running tests
- fix outdated comment
- can leave out REFINE_QUICK_AND_DIRTY, because it's set in proofs/Makefile
> minor run_tests improvements

- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
The action will abort when no clean rebase is possible, and force-push the rebased branch when the rebase over origin/master was clean.
The push will trigger proof runs on the rebased branches.
This required L4V_PLAT etc to be merged first, i.e. everything related to #639
> github: auto-rebase platform branches

- lib/BCorres_UL.thy
- lib/Bisim_UL.thy
- lib/EquivValid.thy
- lib/MonadicRewrite.thy
- lib/Monads/Empty_Fail.thy
- lib/Monads/No_Fail.thy
- lib/Monads/NonDetMonadVCG.thy
- lib/Monads/NonDetMonad_Total.thy
- lib/Monads/TraceMonadVCG.thy
- lib/Monads/wp/WPC.thy
- proof/access-control/CNode_AC.thy
- proof/crefine/lib/AutoCorres_C.thy
- proof/crefine/lib/Ctac.thy
- proof/drefine/Corres_D.thy
- proof/invariant-abstract/AARCH64/Machine_AI.thy
- proof/invariant-abstract/ARM/Machine_AI.thy
- proof/invariant-abstract/ARM_HYP/Machine_AI.thy
- proof/invariant-abstract/RISCV64/Machine_AI.thy
- proof/invariant-abstract/X64/Machine_AI.thy
- sys-init/DuplicateCaps_SI.thy
- document the `wpc_helper` predicate and setup for `wpc` (but not the proof method internals at this point)
- add facilities for a second guard of predicate type
The current setup works well for judgements with one guard of type predicate or set (valid, validE, etc), or with two guards where one is a predicate and the other is a set (ccorres), but not for judgements that have two predicate guards, i.e. plain corres. This commit adds a second such guard, which can be ignored for the judgements that don't need it in the same way that valid/validE currently ignore the set-type guard.
> allow a second predicate-type guard in `wpc`

- lib/Corres_Method.thy
- lib/Corres_UL.thy
- lib/MonadicRewrite.thy
- lib/Monads/wp/WP-method.ML
- lib/Monads/wp/WP_Pre.thy
- proof/crefine/ARM/Ctac_lemmas_C.thy
- proof/crefine/ARM/Fastpath_C.thy
- proof/crefine/ARM/IpcCancel_C.thy
- proof/crefine/ARM/Syscall_C.thy
- proof/crefine/ARM_HYP/Ctac_lemmas_C.thy
- proof/crefine/ARM_HYP/Fastpath_C.thy
- proof/crefine/ARM_HYP/IpcCancel_C.thy
- proof/crefine/ARM_HYP/Retype_C.thy
- proof/crefine/ARM_HYP/Syscall_C.thy
- proof/crefine/RISCV64/CSpaceAcc_C.thy
- proof/crefine/RISCV64/Ctac_lemmas_C.thy
- proof/crefine/RISCV64/IpcCancel_C.thy
- proof/crefine/X64/CSpaceAcc_C.thy
- proof/crefine/X64/Ctac_lemmas_C.thy
- proof/crefine/X64/IpcCancel_C.thy
- proof/crefine/lib/Ctac.thy
- proof/crefine/lib/ctac-method.ML
- proof/refine/AARCH64/ArchAcc_R.thy
Factor out pre_tac such that we can have separate theorem sets and methods for wp_pre, monadic_rewrite_pre, corres_pre, and potentially others in the future.
Leave everything in wp_pre that we expect to use wp or wp_simp on, in particular also no_fail.
Implements a tiny part of #634
> lib: split out WP_Pre.pre_tac for wp_pre

- lib/MonadicRewrite.thy
- lib/ROOT
- lib/test/MonadicRewrite_Test.thy
- proof/infoflow/Ipc_IF.thy
This is a first stab at some documentation / demo material to help understand what the `monadic_rewrite` top-level tactics do.
There is also a commit with a very long message that describes the changes to handling bound variables in monadic statements when iterating over them with `monadic_rewrite_bind_tail` and grabbing onto them with `monadic_rewrite_bind_head`. This was very, very hard to figure out. I still don't understand why bind_head must not have eta terms for example, and for the bind_tail it's a reasonable, but best-guess.
I have some issues confusing `eta` and `[lambda] abstraction` that could use some correcting, plus feedback on the (in)comprehensibility of the demo (I know Michael wanted to see some examples in the past).
This probably needs to be tweaked after the wp_pre …
> Monadic rewrite: improve bound name handling, add docs/tests

- spec/haskell/SEL4.cabal
- spec/haskell/stack.yaml
GHC 9.2.8 has better support for Linux/aarch64/v8 for use in Docker.
Like seL4/capdl#50, this is in preparation for upgrading ghc in docker, so we can add multi-architecture (x64/aarch64) docker images.
> haskell: upgrade to lts-20.25 and ghc 9.2.8

- .github/workflows/proof-deploy.yml
The implicit GITHUB_TOKEN does not trigger further push actions in the same repo, but in this case we do want the push action to happen on the `-rebased` branches, so we use an explicit auth token instead.
> github: use explicit token to enable push triggers

- .github/workflows/proof-deploy.yml
Apologies, #647 needs a small update -- the name of the provided secret token was wrong.
> github: use correct secret

- lib/Corres_Cases.thy
- lib/Corres_Method.thy
- proof/crefine/RISCV64/VSpace_C.thy
- proof/crefine/X64/VSpace_C.thy
- proof/crefine/lib/AutoCorres_C.thy
- proof/refine/ARM/VSpace_R.thy
Add safe datatype case distinction for corres -- wpc turns out to be  insufficient even after generalisation of the helper predicate.
- `corres_cases_left`: case distinction on abstract monad
- `corres_cases_right`: case distinction on concrete monad
- `corres_cases`: case distinction first of abstract/concrete monad
- `corres_cases_both`: simultaneous (quadratic) case distinction on both sides, with safe elimination of trivially contradictory cases
Main intended benefit is less thinking about safety of schematics, fewer mentions of goal parameter names, and fewer manual guard instantiations.
The PR also removes the old defunct wpc setup for corres and changes a few proofs in refine/ARM to demonstrate how the method is intended to be used.
> add corres_cases method

- lib/CorresK_Method.thy
- lib/Corres_Method.thy
- lib/Corres_UL.thy
- lib/ExtraCorres.thy
- lib/Monads/In_Monad.thy
- lib/Monads/MonadEq_Lemmas.thy
- lib/Monads/TraceMonadVCG.thy
- lib/ROOT
- proof/refine/AARCH64/LevityCatch.thy
- proof/refine/ARM/LevityCatch.thy
- proof/refine/ARM_HYP/LevityCatch.thy
- proof/refine/RISCV64/ArchAcc_R.thy
- proof/refine/RISCV64/Bits_R.thy
- proof/refine/RISCV64/LevityCatch.thy
- proof/refine/RISCV64/SubMonad_R.thy
- proof/refine/RISCV64/VSpace_R.thy
- proof/refine/X64/LevityCatch.thy
This new `corres` method is similar to the `corresK` method and calculus, but much less ambitious. Its main purpose is to automate boilerplate proof steps in corres proofs and is specifically not trying to fully automate such proofs (although some few might be solved).
The idea is that the method will make some progress with obvious steps and leave over a proof state the user can operate on further.
I've tried to put in a lot of comments to document the design and some of the rationale, but there are no examples yet. 
Implements #634  (see there for parts of the design discussion)
This is on top of #653, which renames the old `Corres_Method` to `CorresK_Method`
> a simpler corres method

- proof/crefine/ARM/Retype_C.thy
- proof/crefine/ARM_HYP/Retype_C.thy
- proof/drefine/StateTranslation_D.thy
- spec/abstract/ARM/ArchDecode_A.thy
- spec/abstract/ARM_HYP/ArchDecode_A.thy
- spec/design/skel/ARM/ArchTypes_H.thy
- spec/design/skel/ARM_HYP/ArchTypes_H.thy
Update proofs for the changes in seL4/seL4#801, in particular commit https://github.com/seL4/seL4/commit/b3cc85242563b9e08c243b62e181c4a8f075239c
> Update proofs for AArch64 seL4 PR 

- lib/Corres_Method.thy
- lib/Corres_UL.thy
- lib/ROOT
- lib/test/Corres_Test.thy
- proof/refine/RISCV64/ArchAcc_R.thy
- proof/refine/RISCV64/Arch_R.thy
- proof/refine/RISCV64/VSpace_R.thy
- enforce (no_asm) more strongly for corres term rewriting in `corres`
- add an additional breakpoint for debugging `corres_cleanup`
- add a tutorial for the `corres` method, which also serves as a longer test case
> test and docs for `corres` method + slight tweaks for the same

- proof/crefine/ARM/CSpace_RAB_C.thy
- proof/crefine/ARM_HYP/CSpace_RAB_C.thy
- proof/crefine/RISCV64/CSpace_RAB_C.thy
- proof/crefine/X64/CSpace_RAB_C.thy
Trying to figure this out was very educational, since ccorres_abstract was used without intending to abstract a variable, the xf' and lambda name were both red herrings (in fact, this proof only worked if xf' was instantiated with an *irrelevant* C local var name), and the body was not transformed.
> crefine: change misleading proof step in CSpace_RAB_C

- lib/Monads/Fun_Pred_Syntax.thy
- lib/Monads/Monad_Lib.thy
- lib/Monads/trace/Trace_Empty_Fail.thy
- lib/Monads/trace/Trace_In_Monad.thy
- lib/Monads/trace/Trace_Lemmas.thy
- lib/Monads/trace/Trace_Monad.thy
- lib/Monads/trace/Trace_Monad_Equations.thy
- lib/Monads/trace/Trace_More_VCG.thy
- lib/Monads/trace/Trace_No_Fail.thy
- lib/Monads/trace/Trace_No_Throw.thy
- lib/Monads/trace/Trace_RG.thy
- lib/Monads/trace/Trace_Sat.thy
- lib/Monads/trace/Trace_Strengthen_Setup.thy
- lib/Monads/trace/Trace_Total.thy
- lib/Monads/trace/Trace_VCG.thy
This fills out the rule set by copying in as many definitions and rules as possible from the nondet monad.
Note, for review purposes the first commit has been separated into two. The first commit currently seen here copies in verbatim from nondet monad and can be ignored. The second commit updates as required for the trace monad and the third is completely new content. Both should be reviewed as normal, although there is quite a bit of crossover between the second commit here and the first commit in https://github.com/seL4/l4v/pull/666.
> Progress on completing the trace monad rule set 

- lib/Monads/nondet/Nondet_Det.thy
- lib/Monads/nondet/Nondet_Lemmas.thy
- lib/Monads/nondet/Nondet_Monad_Equations.thy
- lib/Monads/nondet/Nondet_More_VCG.thy
- lib/Monads/nondet/Nondet_VCG.thy
- lib/Monads/nondet/Nondet_While_Loop_Rules.thy
- lib/Monads/nondet/Nondet_While_Loop_Rules_Completeness.thy
In particular, try to remove as many _tac methods that refer to system-generated variable names as possible. Any remaining uses are explicitly protected by a rename_tac.
> Remove uses of _tac methods from nondet

- lib/ExtraCorres.thy
- lib/Monads/nondet/Nondet_No_Fail.thy
Please see the commit message for a brief explanation
> Improve `corres` rules `whileLoop`

- proof/Makefile
- run_tests
- spec/cspec/AARCH64/Kernel_C.thy
- tools/asmrefine/AARCH64/ArchSetup.thy
- set up base sessions for CRefine
- disable SimplExportAndRefine for AArch64 (no BV infrastructure for this architecture yet)
- switch off `quick_and_dirty` for Refine session (proof finished)
- switch on `quick_and_dirty` for CRefine session (proof in development)
> CKernel, CSpec, and CBaseRefine sessions for AArch64

- lib/clib/CCorresLemmas.thy
- lib/clib/Corres_UL_C.thy
- lib/clib/SIMPL_Lemmas.thy
- proof/crefine/ARM_HYP/Retype_C.thy
- proof/crefine/RISCV64/Retype_C.thy
- proof/crefine/X64/Retype_C.thy
These commits have already been reviewed in https://github.com/seL4/l4v/pull/673
> MCS: cherry-pick CLib rules

- proof/Makefile
- proof/crefine/RISCV64/ADT_C.thy
- proof/crefine/RISCV64/ArchMove_C.thy
- proof/crefine/RISCV64/Arch_C.thy
- proof/crefine/RISCV64/Finalise_C.thy
- proof/crefine/RISCV64/Invoke_C.thy
- proof/crefine/RISCV64/IpcCancel_C.thy
- proof/crefine/RISCV64/Ipc_C.thy
- proof/crefine/RISCV64/IsolatedThreadAction.thy
- proof/crefine/RISCV64/Recycle_C.thy
- proof/crefine/RISCV64/Refine_C.thy
- proof/crefine/RISCV64/Retype_C.thy
- proof/crefine/RISCV64/SchedContext_C.thy
- proof/crefine/RISCV64/Schedule_C.thy
- proof/crefine/RISCV64/StateRelation_C.thy
- proof/crefine/RISCV64/Syscall_C.thy
- proof/crefine/RISCV64/Tcb_C.thy
- run_tests
This sorries the last files in the CRefine session, thereby completing the setup of the proof infrastructure for MCS CRefine. 
In addition, this enables testing of the CRefine session via our continuous integration setup.
> MCS CRefine sorried for RISCV64

- spec/cspec/c/kernel.mk
PR seL4/seL4#1105 moves config generation back to configure time. This means we can revert eaf735c38f.
> cspec: adjust for kernel build change

- tools/autocorres/tools/release.py
- tools/autocorres/tools/release_files/AUTOCORRES_FILES
- tools/autocorres/tools/release_files/CONTRIBUTORS
- tools/autocorres/tools/release_files/ChangeLog
- tools/autocorres/tools/release_files/README
- tools/autocorres/tools/release_files/ROOT.release
- tools/autocorres/tools/release_files/ROOTS.base_dir
- tools/c-parser/INSTALL.md
- tools/c-parser/RELEASES.md
- tools/c-parser/mkrelease
The library restructure means a few things need to be updated in the release scripts for the C parser and AutoCorres. Overall this simplified both scripts, so it looks like this is at least a small win.
Summary:
- update change logs, bump versions
- update release scripts for new library structure
- update ROOT/ROOTS files in the releases
- update AutoCorres CONTRIBUTORS file
> updates for 2023 C-Parser and AutoCorres releases

- proof/crefine/ARM_HYP/Arch_C.thy
Length argument for these functions was previously unsigned int, which was fine for AArch32, but an implicit downcast on AArch64. Changing it to word_t makes it unsigned long, thus requiring signature update in ccorres proofs.
Test with https://github.com/seL4/seL4/pull/1145
> arm-hyp crefine: update length to word_t for VCPU functions

- lib/clib/CCorresLemmas.thy
Please see the commit message.
> Further improvements to ccorres_While

- .github/workflows/proof-deploy.yml
- .github/workflows/weekly-clean.yml
- run_tests
- spec/cspec/c/kernel.mk
Setting the environment variable `INPUT_NUM_DOMAINS` will cause the build to override the `KernelNumDomains` setting in the config file with the provided setting. `INPUT_NUM_DOMAINS` is the name we get from the GitHub workflow input with the name `NUM_DOMAINS`.
The second commit switches the test to the following `NUM_DOMAINS` settings:
- PRs: default as in config file, no matrix
- push to master: with NUM_DOMAINS = 1 and default (= '')
- weekly test: with NUM_DOMAINS = 1, 7, and default
The default is 16 in the current config files. 1 leads to structural code changes is the setting most likely to break. 7 is for checking that the proofs also work with a value that is not a power of 2.
This needs seL4/ci-actions#293 to be merged first.
> provide a NUM_DOMAINS test override

- .github/workflows/proof-deploy.yml
- .github/workflows/weekly-clean.yml
If we don't provide the additional name fragment, previous artifacts would be overwritten, which leads to a failure with error message on GitHub.
> github: add num_domains key to artifact upload

- lib/Eisbach_Tools/Eisbach_Methods.thy
- lib/clib/Simpl_Rewrite.thy
- add a method for setting context visibility to `false` for Eisabach methods
- use it in `simpl_rewrite` to suppress simplifier warnings in `ccorres_rewrite`
This should make `ccorres_rewrite` quite about `Collect_const` being in the simpset or not.
> Suppress simplifier warnings in `corres_rewrite`

- spec/abstract/AARCH64/Arch_Structs_A.thy
- spec/cspec/AARCH64/Kernel_C.thy
- spec/machine/AARCH64/Platform.thy
- add ghost state corresponding to gsPTTypes in Haskell and ASpec
- add ghost type comments
- style update for old definitions since we need to touch most of these
- define vs/pt_array_len for use in C annotations
- make NormalPT_T/VSRootPT_T names available for use in C annotations
Currently the vs/pt_array_len declarations introduce a dependency of CSpec on ASpec. We could remove that if we moved the definitions of pt_index_len and vs_index_bits higher, so that they become visible in ExecSpec.
This PR is required for merging seL4/seL4#1156
> aarch64 cspec+crefine: pt_type ghost state + table array sizes

- docs/commit-messages.md
Add a guide for how to write commit messages and commit message tags to make the messages more consistent and to help new people on the project get started more quickly.
> docs: add a guide for commit messages

- tools/c-parser/isar_install.ML
If the path configures as "cpp_path" is not an absolute path, convert it to an absolute path by prepending the directory in which the "install_C_file" is used.  This makes it easier to share the same configuration across a team using different operating systems.
> If cpp_path is relative, make it relative to the current theory.

- tools/c-parser/calculate_state.ML
This change ensures that the file "umm_types.txt" is written in the same directory the theory file containing the "install_C_file" Isar command. Otherwise, the file might be written into current working directory of Isabelle, which might not be writable by the user.
> Ensure that umm_types.txt is saved relative to theory file.

- .github/workflows/external.yml
- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
- .github/workflows/weekly-clean.yml
Avoid clashes between uploaded artifact names for each workflow. Previously these were just overwritten, but the new GitHub actions error instead.
Fixes #713
> github: make sure artifact names are unique

- lib/Monads/nondet/Nondet_No_Fail.thy
- lib/Monads/nondet/Nondet_Total.thy
- lib/Monads/trace/Trace_Empty_Fail.thy
- lib/Monads/trace/Trace_Monad.thy
- lib/Monads/trace/Trace_No_Fail.thy
- lib/Monads/trace/Trace_No_Throw.thy
- lib/Monads/trace/Trace_No_Trace.thy
- lib/Monads/trace/Trace_Prefix_Closed.thy
- lib/Monads/trace/Trace_RG.thy
- lib/Monads/trace/Trace_Total.thy
- lib/concurrency/Atomicity_Lib.thy
- lib/concurrency/Prefix_Refinement.thy
- lib/concurrency/examples/Peterson_Atomicity.thy
- lib/concurrency/examples/Plus2_Prefix.thy
- proof/crefine/RISCV64/VSpace_C.thy
- proof/crefine/X64/VSpace_C.thy
- proof/crefine/lib/AutoCorres_C.thy
- proof/invariant-abstract/AARCH64/Machine_AI.thy
- proof/invariant-abstract/ARM/Machine_AI.thy
- proof/invariant-abstract/ARM_HYP/Machine_AI.thy
- proof/invariant-abstract/RISCV64/Machine_AI.thy
- proof/invariant-abstract/X64/Machine_AI.thy
This extends the rule sets for the various monad properties (`no_trace`, `no_fail`, etc.) to cover all of the monad primitives that we have. It does not touch the RG rule set.
> More progress on completing the trace monad rule set

- lib/Monads/wp/WP-method.ML
This changes it so that setting `wp_trace_instantiation` to true is enough to see the trace, instead of also needing to set `wp_trace`.
> monads/wp: update checks for when to trace wp

- lib/Corres_UL.thy
- lib/HaskellLib_H.thy
- lib/Heap_List.thy
- lib/Lib.thy
- lib/ListLibLemmas.thy
- lib/MonadicRewrite.thy
- lib/Monads/reader_option/Reader_Option_ND.thy
- lib/Monads/reader_option/Reader_Option_VCG.thy
- lib/clib/Corres_UL_C.thy
Currently separated into many smaller commits, but I could consolidated them into just a few commits if that's preferred: one commit for reader monad lemmas, one for lists, then one for `CLib`, `Heap_List.thy`, `Corres_UL.thy`, and `MonadicRewrite.thy`
> Some more rules for `Lib`

- lib/HaskellLib_H.thy
- lib/Monads/ROOT
- lib/Monads/nondet/Nondet_Reader_Option.thy
- lib/Monads/reader_option/Reader_Option_Monad.thy
- lib/Monads/reader_option/Reader_Option_VCG.thy
- lib/Monads/trace/Trace_Monad.thy
- lib/Monads/trace/Trace_Reader_Option.thy
- lib/NonDetMonadLemmaBucket.thy
- lib/clib/Corres_UL_C.thy
- proof/sep-capDL/Lookups_D.thy
- spec/design/m-skel/AARCH64/MachineTypes.thy
- spec/design/m-skel/ARM/MachineTypes.thy
- spec/design/m-skel/ARM_HYP/MachineTypes.thy
- spec/design/m-skel/RISCV64/MachineTypes.thy
- spec/design/m-skel/X64/MachineTypes.thy
- tools/autocorres/NonDetMonadEx.thy
- tools/autocorres/TypeStrengthen.thy
I am very open to suggestions if anyone has an idea for a nicer way to structure this or to reduce the copied content. I had a brief attempt at a locale but couldn't find a way to get it to work that didn't involve even more copying.
> Monads: refactor reader_option and nondet connection 

- proof/crefine/AARCH64/ArchMove_C.thy
- proof/crefine/AARCH64/Retype_C.thy
- proof/crefine/AARCH64/SR_lemmas_C.thy
- proof/crefine/AARCH64/Wellformed_C.thy
- proof/crefine/ARM_HYP/ArchMove_C.thy
- proof/crefine/ARM_HYP/Retype_C.thy
- proof/crefine/ARM_HYP/SR_lemmas_C.thy
- proof/crefine/ARM_HYP/Wellformed_C.thy
- spec/haskell/src/SEL4/Machine/RegisterSet/AARCH64.hs
- spec/haskell/src/SEL4/Machine/RegisterSet/ARM.lhs
This brings the spec in line with seL4/seL4#1181.
Test with: seL4/seL4#1181
> arm-hyp+aarch64 haskell: add VCPURegVMPIDR(_EL2)

- lib/Lib.thy
- lib/None_Top_Bot.thy
- lib/ROOT
Add theory `None_Top_Bot` with definitions, lemmas, and automation setup for predicates on `option` that map `None` to `True`/`False`, or more generally to `top`/`bot`. Can be used as e.g. `none_top tcb_at p`.
Bit more background: this came out of discussions on an MCS PR with Michael and me realising that we keep defining this concept over and over (have done it myself multiple times, I'm sure), so we should instead do it properly once, set up automation for it, and then use it. This PR does the first two parts, but make no attempt yet at removing the old versions that are all over the place. We should probably do that incrementally over time, either whenever we touch one of these points where there is a predicate on an option value or in a concerted effort for specific parts of the …
> lib: none_top/none_bot for option predicates

- lib/None_Top_Bot.thy
As @corlewis pointed out, `none_bot_top_neq_None` should indicated that it is about bool only, like the none_top_bot version.
> lib: consistent naming in None_Top_Bot

- lib/MonadicRewrite.thy
- proof/Makefile
- proof/crefine/AARCH64/CSpace_RAB_C.thy
- proof/crefine/AARCH64/Fastpath_C.thy
- proof/crefine/AARCH64/Fastpath_Defs.thy
- proof/crefine/AARCH64/Fastpath_Equiv.thy
- proof/crefine/AARCH64/Refine_C.thy
- proof/crefine/ARM/CSpace_RAB_C.thy
- proof/crefine/ARM/Fastpath_Equiv.thy
- proof/crefine/ARM/Refine_C.thy
- proof/crefine/ARM_HYP/CSpace_RAB_C.thy
- proof/crefine/ARM_HYP/Fastpath_Equiv.thy
- proof/crefine/ARM_HYP/Refine_C.thy
- proof/crefine/RISCV64/CSpace_RAB_C.thy
- proof/crefine/RISCV64/Refine_C.thy
- proof/crefine/X64/CSpace_RAB_C.thy
- proof/crefine/X64/Refine_C.thy
- proof/refine/AARCH64/Refine.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Refine.thy
- proof/refine/ARM_HYP/PageTableDuplicates.thy
- proof/refine/ARM_HYP/Refine.thy
- proof/refine/RISCV64/Refine.thy
- proof/refine/X64/Refine.thy
- spec/design/skel/API_H.thy
- spec/haskell/src/SEL4.lhs
Before I do more cleanup, I think this could use some feedback. Please ignore the horrid commit history (for now), but advice welcome on whether I should squash the actual fastpath commits into 3 parts (defs, rewrite, C refinement), or only one commit.
In any case the proofs work and look better than the ARM/ARM_HYP ones at least.
> AArch64 fastpath proofs

- proof/crefine/AARCH64/ADT_C.thy
- proof/crefine/AARCH64/ArchMove_C.thy
- proof/crefine/AARCH64/Arch_C.thy
- proof/crefine/AARCH64/CSpace_C.thy
- proof/crefine/AARCH64/Finalise_C.thy
- proof/crefine/AARCH64/IpcCancel_C.thy
- proof/crefine/AARCH64/Machine_C.thy
- proof/crefine/AARCH64/Recycle_C.thy
- proof/crefine/AARCH64/Retype_C.thy
- proof/crefine/AARCH64/StateRelation_C.thy
- proof/crefine/AARCH64/Syscall_C.thy
- proof/crefine/AARCH64/TcbQueue_C.thy
- proof/crefine/AARCH64/Tcb_C.thy
- proof/crefine/AARCH64/VSpace_C.thy
- proof/crefine/AARCH64/Wellformed_C.thy
- proof/crefine/ARM/Arch_C.thy
- proof/crefine/ARM_HYP/Finalise_C.thy
- proof/crefine/ARM_HYP/TcbQueue_C.thy
- proof/crefine/ARM_HYP/VSpace_C.thy
- proof/crefine/RISCV64/Arch_C.thy
- proof/crefine/RISCV64/Finalise_C.thy
- proof/crefine/RISCV64/TcbQueue_C.thy
- proof/crefine/RISCV64/VSpace_C.thy
- proof/crefine/X64/Arch_C.thy
- proof/crefine/X64/Finalise_C.thy
- proof/crefine/X64/TcbQueue_C.thy
- proof/crefine/X64/VSpace_C.thy
First pass resolving obvious FIXMEs in AARCH64 proofs:
- questions that have resolved themselves
- lemmas that are unused (some on all architectures)
- trivial lemma moves
- some FIXME updates for easier grep later
> crefine: remove unused lemmas; resolve AARCH64 FIXMEs

- lib/Word_Lib/Word_Lemmas_64_Internal.thy
- lib/Word_Lib/Word_Lemmas_Internal.thy
- proof/crefine/AARCH64/ADT_C.thy
- proof/crefine/AARCH64/Arch_C.thy
- proof/crefine/AARCH64/CSpace_C.thy
- proof/crefine/AARCH64/Finalise_C.thy
- proof/crefine/AARCH64/Recycle_C.thy
- proof/crefine/AARCH64/Syscall_C.thy
- proof/crefine/AARCH64/VSpace_C.thy
- proof/crefine/ARM_HYP/ADT_C.thy
- proof/crefine/ARM_HYP/Ipc_C.thy
- proof/crefine/Move_C.thy
- proof/crefine/RISCV64/Ipc_C.thy
- proof/crefine/X64/Ipc_C.thy
- move AARCH64 word lemmas to the holding area in Word_Lib
- generalise word_ctz_upcast_id and provide word_ctz_upcast_id_32_64
> word_lib+crefine: move lemmas to Word_Lib

- lib/Crunch_Instances_Trace.thy
- lib/Monads/Fun_Pred_Syntax.thy
- lib/Monads/Monad_Lib.thy
- lib/Monads/ROOT
- lib/Monads/trace/Trace_Empty_Fail.thy
- lib/Monads/trace/Trace_Monad.thy
- lib/Monads/trace/Trace_More_RG.thy
- lib/Monads/trace/Trace_More_VCG.thy
- lib/Monads/trace/Trace_No_Trace.thy
- lib/Monads/trace/Trace_Prefix_Closed.thy
- lib/Monads/trace/Trace_RG.thy
- lib/Monads/trace/Trace_Strengthen_Setup.thy
- lib/concurrency/Atomicity_Lib.thy
- lib/concurrency/Prefix_Refinement.thy
- lib/concurrency/Triv_Refinement.thy
- lib/concurrency/examples/Peterson_Atomicity.thy
- lib/concurrency/examples/Plus2_Prefix.thy
This generally follows the structure and naming conventions of the existing rule set for Hoare logic, in `Trace_VCG.thy` and `Trace_More_VCG.thy` (and the very similar ruleset and files in the nondet directory).
I took the opportunity to make some changes as I went along. In particular:
* `validIE_R` and `validIE_L` are abbreviations instead of definitions.
* some lemmas were relocated to better follow the structure of the file and to improve reuse.
* some lemmas were renamed in an attempt to be more consistent.
It would be good to propagate the last two back to the Hoare versions, to keep things consistent and allow us to update the rest of the proofs now. The first one might not be worth it however, as it would require too many other changes to work.
Lemmas for lifting over combinators …
> Enlarge the trace monad rule set for RG logic

- lib/Monads/trace/Trace_Empty_Fail.thy
- lib/Monads/trace/Trace_Monad.thy
- lib/Monads/trace/Trace_Monad_Equations.thy
- lib/concurrency/Atomicity_Lib.thy
- lib/concurrency/Prefix_Refinement.thy
- lib/concurrency/Triv_Refinement.thy
- lib/concurrency/examples/Peterson_Atomicity.thy
- lib/concurrency/examples/Plus2_Prefix.thy
This roughly follows the structure and naming conventions of the `corres_underlying` rule set, as in `Corres.thy` and `ExtraCorres.thy`.
> Enlarge the prefix_refinement rule set

- lib/Monads/wp/WP-method.ML
- lib/Monads/wp/WP_Pre.thy
This makes two improvements for tracing rules applied by `wp_pre`.
The first is that the resulting trace will be shown when `wp_pre` is called directly, not just when called from `wp`. The current implementation does mean that this output will be labelled as "Theorems used by wp", even when called in other contexts, such as `corres_pre`. This could be fixed by tagging all uses of the `WP_Pre.pre_tac` method with a string and then passing it through to where the trace is outputted, but I thought that that would not be worth doing just to avoid mislabelled debugging output.
The second improvement is avoiding a rule being incorrectly reported as being used. `wp_pre` tests the resulting goals after applying a rule and weakening the precondition, and if the test fails then it discards what it …
> Improve wp_pre tracing

- proof/crefine/AARCH64/VSpace_C.thy
This was a change made in https://github.com/seL4/l4v/commit/146eaa10fc2b3a41d26617b60571eb274535234e, as part of https://github.com/seL4/l4v/pull/696.
> aarch64 crefine: update to match other arches

- lib/Value_Type.thy
- lib/test/Value_Type_Test.thy
- proof/crefine/AARCH64/ADT_C.thy
- proof/crefine/AARCH64/ArchMove_C.thy
- proof/crefine/AARCH64/IpcCancel_C.thy
- proof/crefine/AARCH64/Retype_C.thy
- proof/crefine/AARCH64/VSpace_C.thy
- proof/crefine/AARCH64/Wellformed_C.thy
- proof/crefine/ARM/IpcCancel_C.thy
- proof/crefine/ARM/Wellformed_C.thy
- proof/crefine/ARM_HYP/IpcCancel_C.thy
- proof/crefine/ARM_HYP/Wellformed_C.thy
- proof/crefine/RISCV64/IpcCancel_C.thy
- proof/crefine/RISCV64/Wellformed_C.thy
- proof/crefine/X64/IpcCancel_C.thy
- proof/crefine/X64/Wellformed_C.thy
- proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
- proof/refine/AARCH64/ADT_H.thy
- spec/abstract/AARCH64/Arch_Structs_A.thy
- spec/cspec/AARCH64/Kernel_C.thy
Produce a `_def` theorem for the value type that provides direct symbolic access to the right-hand side of the `value_type` definition. This avoids having to unfold those terms in subsequent proofs.
The numeric value as as term is still available as `<type-name>_val`.
`value_type` is now restricted to types `nat` and `int` on the right-hand side (`int` being cast to `nat` automatically). Other types can still be used, but have to be cast to nat manually. It turns out that so far we have only needed `int` and `nat`, so this works out without changes to any of the `value_type` definitions.
> produce _def and _val theorems in value_type

- docs/setup.md
- add aarch64 and riscv cross compilers
- remove reference to ARMv7 architecture, because it now should work for all architectures.
- remove mention of Debian Buster, because it is not supported anymore.
> docs: add cross compilers to Linux dependencies

- lib/Monads/wp/WP_README.thy
This tries to remove ambiguity around the order in which `wp`, `wp_comb` and `wp_split` rules are applied.
> Improve WP_README's description of rule ordering

- lib/Monads/nondet/Nondet_VCG.thy
- lib/Monads/trace/Trace_RG.thy
- lib/Monads/trace/Trace_VCG.thy
- proof/access-control/ARM/ArchInterrupt_AC.thy
- proof/access-control/Finalise_AC.thy
- proof/access-control/Interrupt_AC.thy
- proof/access-control/RISCV64/ArchInterrupt_AC.thy
- proof/capDL-api/Invocation_DP.thy
- proof/drefine/Arch_DR.thy
- proof/drefine/Corres_D.thy
- proof/drefine/Syscall_DR.thy
- proof/drefine/Tcb_DR.thy
- proof/infoflow/ARM/ArchRetype_IF.thy
- proof/infoflow/RISCV64/ArchRetype_IF.thy
- proof/invariant-abstract/Syscall_AI.thy
- proof/refine/AARCH64/TcbAcc_R.thy
- proof/refine/AARCH64/Tcb_R.thy
- proof/refine/ARM/Arch_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/ARM_HYP/Arch_R.thy
- proof/refine/ARM_HYP/TcbAcc_R.thy
- proof/refine/ARM_HYP/Tcb_R.thy
- proof/refine/RISCV64/TcbAcc_R.thy
- proof/refine/RISCV64/Tcb_R.thy
- proof/refine/RISCV64/VSpace_R.thy
- proof/refine/X64/TcbAcc_R.thy
- proof/refine/X64/Tcb_R.thy
`hoare_seq_ext` was previously made a `wp` rule in the middle of `ainvs`, which was surprising and could lead to different behaviour depending on which session a proof was inside of. This change makes it a `wp` rule in the base `Monads` setup, along with improving consistency by adding similar rules for `validE` and its variants.
> Make hoare_seq_ext and hoare_vcg_seqE wp rules 

- lib/Defs.thy
- lib/Eisbach_Tools/Apply_Debug.thy
- lib/Eval_Bool.thy
- lib/Hoare_Sep_Tactics/Hoare_Sep_Tactics.thy
- lib/Match_Abbreviation.thy
- lib/Qualify.thy
- lib/Repeat_Attribute.thy
- lib/SimpStrategy.thy
- lib/Try_Attribute.thy
- lib/Word_Lib/Bitwise.thy
- lib/Word_Lib/Guide.thy
- lib/Word_Lib/More_Word.thy
- lib/Word_Lib/More_Word_Operations.thy
- lib/Word_Lib/Reversed_Bit_Lists.thy
- lib/Word_Lib/Signed_Division_Word.thy
- lib/Word_Lib/Singleton_Bit_Shifts.thy
- lib/Word_Lib/Word_Lemmas.thy
- lib/crunch-cmd.ML
- lib/defs.ML
- proof/crefine/Move_C.thy
- proof/crefine/lib/CToCRefine.thy
- spec/design/skel/CSpace_H.thy
- tools/asmrefine/ProveGraphRefine.thy
- tools/autocorres/WordAbstract.thy
- tools/autocorres/autocorres_trace.ML
- tools/autocorres/utils.ML
- tools/c-parser/UMM_Proofs.ML
- tools/c-parser/heapstatetype.ML
- tools/c-parser/standalone-parser/Makefile
- tools/c-parser/umm_heap/ArrayAssertion.thy
Updates all proofs and ML code to Isabelle2024.
The changes are very minor this time, and apart from one or two cases only involve ML code. The main ML differences are that:
* the simproc setup has changed slightly
* it is now an error to catch all exceptions and instead we use the new `\<^try>` antiquotation
* the underlying ML for the old-style `defs` command was downgraded, which meant that `defs` had to be correspondingly downgraded as well.
Nicely, initial testing did show some fairly significant performance improvements, particularly to the CPU time.
```
Isabelle2023:
N = 22
Average ARM CRefine: (00:28:45 real, 03:16:57 cpu, 22.11GB)
Standard Deviation: (00:01:25 real, 00:16:05 cpu, 0.38GB)
Isabelle2024:
N = 22
Average ARM CRefine: (00:24:16 real, 02:22:21 cpu, 22.12GB)
Standard …
```
> Update to Isabelle2024

- spec/haskell/src/SEL4/Machine/Hardware/AARCH64.hs
- spec/haskell/src/SEL4/Machine/Hardware/ARM.lhs
seL4/seL4#1251 changes the value of HCR_NATIVE which we mirror in the Haskell spec.
Test with: seL4/seL4#1251
> haskell: sync hcrNative with C changes

- .github/workflows/push.yml
The site doesn't like link checkers any more, so we're removing it from the check.
> github: remove haskellstack.org from link check

- docs/platform-branches.md
- what they are
- how they work
- how to fix them when they break
> docs: document platform branch procedure

- docs/arch-split.md
Some things were confusing, some changed over time. Hopefully this is an improvement.
Particular notes:
* extend_locale was unused and removed, replaced by the `_AI_2` multiple-locale strategy
* the explicit global requalify_facts strategy was used but not documented
Reviewers:
* probably easier to read https://github.com/Xaphiosis/l4v/blob/arch_split/docs/arch-split.md than only the diff
* note the two FIXMEs, I could use some help there.
* the `_AI_asms` vs `_AI_assms` is wonderfully inconsistent (1597 instances of the former, 506 of the latter): I'd like to pick one and then standardise
> docs: update arch-split

- proof/crefine/AARCH64/CSpace_C.thy
- proof/crefine/AARCH64/Finalise_C.thy
- proof/crefine/AARCH64/Invoke_C.thy
- proof/crefine/AARCH64/Retype_C.thy
- proof/crefine/AARCH64/SR_lemmas_C.thy
- proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
- proof/refine/AARCH64/ArchAcc_R.thy
This needed only very minor tweaks, and interestingly only involved more unfolding of `Kernel_Config.config_ARM_PA_SIZE_BITS_40_def`.
Most of the unfoldings involved goals where concrete `vmlevel` numbers now overflow earlier (3 = 0 for config_ARM_PA_SIZE_BITS_40, instead of 4 = 0).
Together with the `maxIRQ` pull request #773, this enables the proof to work for the `zynqmp` (`zcu102`) and `bcm2711` (`rpi4`) platforms. See also seL4/seL4#1290.
> make proofs generic in `config_ARM_PA_SIZE_BITS_40`

- .github/workflows/proof-deploy.yml
Since the proofs are now more generic,
- exynos5 no longer needs a separate proof branch, and
- zynqmp and bcm2711 are now supported for AARCH64
Test these on push/merge to the master branch for manifest deployment, but not for pull requests or weekly (to save CI cost).
> github: add tests for exynos5, zynqmp, bcm2711

- .github/workflows/pr.yml
- `GITHUB_TOKEN`` does not have write access for checks any more by default. Provide explicitly instead.
- bump annotation action version.
> github: upgrade permissions for annotation action

- .github/workflows/proof-deploy.yml
- `include` values are modifying existing combinations when they would not otherwise overwrite a value, but we don't want that. Instead we make sure that `plat` is set for the rest of the matrix and that it would be overwritten by the `include` values. This gives us additional jobs, which is what we want.
- actually use the `plat` value from the build matrix in the aws call
- use `plat` value for upload artifacts as well
> github: fix platform build matrix

- .github/workflows/lint.yml
- .github/workflows/pr.yml
`GITHUB_TOKEN` only has read access when triggered from a fork on the pull_request trigger, so we use `pull_request_target` instead. This requires passing in the PR number explicitly to the thylint action.
Requires https://github.com/seL4/ci-actions/pull/354 to be merged before we can test it.
> github: more authorised token for annotations

- lib/Corres_UL.thy
- lib/ExtraCorres.thy
- lib/HaskellLib_H.thy
- lib/Monads/nondet/Nondet_Reader_Option.thy
- lib/Monads/reader_option/Reader_Option_Monad.thy
- lib/Monads/reader_option/Reader_Option_VCG.thy
- lib/clib/CCorresLemmas.thy
- lib/clib/Corres_UL_C.thy
- lib/clib/SIMPL_Lemmas.thy
- proof/crefine/autocorres-test/AutoCorresTest.thy
- proof/drefine/Arch_DR.thy
Please note that all new rules for the reader monad are currently unused in my work in progress; I have added them here just in case we would like them. 
I'd be happy to rename any of these, so suggestions are welcome.
And I hope the commit messages are sufficiently informative, and sufficiently specific about where the changes are being made. I'm still not sure what the best approach for just adding lemmas like this is in some cases.
> Some rules for `Lib` and `CLib`

- proof/crefine/AARCH64/Finalise_C.thy
- proof/crefine/ARM/Finalise_C.thy
- proof/crefine/ARM_HYP/Finalise_C.thy
- proof/crefine/ARM_HYP/Refine_C.thy
- spec/abstract/X64/ArchInterrupt_A.thy
- spec/design/skel/AARCH64/ArchInterrupt_H.thy
- spec/design/skel/ARM/ArchInterrupt_H.thy
- spec/design/skel/ARM_HYP/ArchInterrupt_H.thy
- fix typos
- remove duplicate abbreviation
- reduce diff between ARM and ARM_HYP
Addressing final comments from #773
> fix leftover typos and tweaks from #773

- lib/ExtraCorres.thy
This was required after a recent update to the schematics of corres_symb_exec_r_conj_ex_abs
> lib: adjust corres_symb_exec_r_conj_ex_abs_forwards

- lib/Monads/nondet/Nondet_Reader_Option.thy
- lib/Monads/nondet/Nondet_VCG.thy
- lib/Monads/trace/Trace_More_RG.thy
- lib/Monads/trace/Trace_RG.thy
- lib/Monads/trace/Trace_Reader_Option.thy
- lib/Monads/trace/Trace_VCG.thy
Some local changes I had that I forgot to add to https://github.com/seL4/l4v/pull/765. Now that I'm not removing these lemmas from the Nondet Monad, the Trace Monad should have them as well.
> Monads: resync trace monad with nondet

- misc/bump/bump-ver-manifest
- misc/bump/ver-bump.py
bump-ver-manifest now takes an optional parameter `--mcs` to operate on `mcs-devel.xml` instead of `devel.xml`.
Goes together with https://github.com/seL4/verification-manifest/pull/20
> bump: make mcs-devel.xml available in bump script

- .github/workflows/proof.yml
- switch off the rt branch test -- to be added to the deployment workflow later (via merge from master)
- switch the PR test to the mcs-devel.xml manifest which is taking the role devel.xml has on the master branch
This will still use the fixed seL4 revision the mcs-devel manifest, but that revision can now be bumped with the `bump-ver-manifest` script, and in the future will also receive pre-process equivalent updates.
> github: remove rt branch test; switch to mcs-devel.xml

- .github/workflows/proof-deploy.yml
Add deployment of the mcs-devel.xml manifest to mcs.xml.
The pattern is to use the branch name in `github.ref` as a guard in the initial code freeze action, and then make any subsequent actions depend on either `code` or `mcs-code`, respectively.
All of this lives on the master branch (but does trigger on pushes to `rt`), so that it can in the future also trigger on manifest updates from `repository_dispatch` events.
Currently the latter does not happen yet, because `github.ref` will be `refs/head/master` for `repository_dispatch` events, so only the main deployment job runs for those.
> github: add mcs manifest deployment

- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
- misc/bump/bump-ver-manifest
- misc/bump/ver-bump.py
This brings in the mcs manifest deployment and mcs bump script option from master.
> merge master into `rt`

- README.md
- change MCS proof badge to the new deployment workflow
- adjust badges to only point to the branch they refer to
> README: adjust CI proof badges

- .github/workflows/proof-deploy.yml
- .github/workflows/rebase.yml
Factor out the platform branch rebase job into its own workflow which is triggered explicitly by a repository-dispatch event.
We can then re-trigger the rebase job after the proofs have succeeded on the rebased branch to confirm that everything is now up to date and get a successful rebase test run after everything has completed.
> github: factor out platform rebase into own workflow

- docs/conventions.md
The isabelle.systems site appears to be down for a while, use archive to stop the constant PR links failures while we think of a longer-term solution.
> docs: use internet archive for isabelle.systems

- lib/Requalify.thy
This uses a complex workaround to unify the parse location of the original name encoded in YXML with the name the user is actually aiming for. While intuitively one could think to use the position of the name we parsed, there appears to be no way to pass that location to read_const/read_type_name, as those expect to be fed the result of Parse.const and Parse.typ respectively.
🦆🦆🦆: aside: this also appears why the code does the weird `(Parse.position (Scan.ahead parse_nm -- Parse.name))` setup that I couldn't make sense of before.
> lib: Requalify: enable ctrl+click jumps for arch_requalify

- lib/Requalify.thy
- lib/test/Requalify_Test.thy
Previous attempts to update the code to allow ctrl+clicking on names resulted in markup overlap errors for arch_requalify commands. This was due to a misconception that YXML strings already containing correct position information (e.g. obtained via Parse.const) would be used directly by Proof_context.read_const/read_type_name. This is not the case. Instead, position information is adjusted for the content length, and since we add a prefix for L4V_ARCH, we got annotation that did not match the document text.
After hours of digging to uncover the above issue, we get this:
* the "check_parsed_nm" in gen_requalify was not an extra check, but a hook to do document annotation; updated comments
* use Proof_Context.check_const/check_type_name with parsed position of Parse.name, and manually …
> lib: Requalify: better document annotation

- proof/crefine/AARCH64/VSpace_C.thy
- proof/crefine/AARCH64/Wellformed_C.thy
- proof/crefine/ARM_HYP/VSpace_C.thy
- proof/crefine/ARM_HYP/Wellformed_C.thy
- spec/cspec/c/gen-config-thy.py
- spec/design/m-skel/AARCH64/MachineTypes.thy
- spec/design/m-skel/ARM_HYP/MachineTypes.thy
- spec/haskell/src/SEL4/Machine/Hardware/AARCH64.hs
- spec/haskell/src/SEL4/Machine/Hardware/ARM.lhs
The config option CONFIG_DISABLE_WFI_WFE_TRAPS influences the value of HCR_VCPU (hcrVCPU in Haskell).
There is not much to make generic -- it is unfolded exactly once to compare the value in the spec to the value in C. The main part is defining hcrVCPU conditionally based on the config setting.
> arm-hyp+aarch64 spec+proof: make generic in CONFIG_DISABLE_WFI_WFE_TRAPS

- misc/scripts/thydeps
- tools/autocorres/README.md
- tools/autocorres/tools/release_files/ChangeLog
- tools/autocorres/tools/release_files/README
- tools/c-parser/README.md
- tools/c-parser/RELEASES.md
- tools/c-parser/mkrelease
- update change log
- adjust release scripts for changes since Isabelle2024 update
- fix old sed backup file bug (removes junk backup file from release)
> AutoCorres 1.11 + CParser 1.21 release

- proof/crefine/RISCV64/Finalise_C.thy
- proof/crefine/RISCV64/Recycle_C.thy
- proof/crefine/RISCV64/StateRelation_C.thy
- proof/crefine/RISCV64/Tcb_C.thy
- proof/crefine/RISCV64/Wellformed_C.thy
Test with https://github.com/seL4/seL4/pull/1302
> Prove `cancelBadgedSends_ccorres`

- proof/crefine/X64/Arch_C.thy
- proof/refine/X64/Arch_R.thy
- proof/refine/X64/CNodeInv_R.thy
- proof/refine/X64/CSpace_R.thy
- proof/refine/X64/Detype_R.thy
- proof/refine/X64/Finalise_R.thy
- proof/refine/X64/InterruptAcc_R.thy
- proof/refine/X64/Interrupt_R.thy
- proof/refine/X64/InvariantUpdates_H.thy
- proof/refine/X64/Invariants_H.thy
- proof/refine/X64/IpcCancel_R.thy
- proof/refine/X64/Ipc_R.thy
- proof/refine/X64/KHeap_R.thy
- proof/refine/X64/Retype_R.thy
- proof/refine/X64/Schedule_R.thy
- proof/refine/X64/Syscall_R.thy
- proof/refine/X64/TcbAcc_R.thy
- proof/refine/X64/Tcb_R.thy
- proof/refine/X64/Untyped_R.thy
- proof/refine/X64/VSpace_R.thy
- spec/design/skel/X64/ArchVSpace_H.thy
- spec/haskell/src/SEL4/Object/IOPort/X64.lhs
🦆🦆🦆 This started with examining the IO port situation and arch-split, in particular complications due to the FC proofs on all architectures mentioning IO ports even when the architectures did not have them.
For AInvs, it was possible to fold valid_ioports into valid_arch_state and do the same for valid_ioports' and valid_arch_state' on X64 Refine... which I initially did in https://github.com/seL4/l4v/pull/829 but it turned out that for Refine this was ugly and didn't make a lot of sense.
At some point when talking with @corlewis about this, he suggested that it might be possible to do some crossing-over and reduce the IO port invariant burden in X64 Refine. After a lot of pain, I managed to figure out a way to bash the specs and proofs into submission, getting rid of valid_ioports' …
> Remove valid_ioports' from X64 Refine

- lib/Monads/wp/Datatype_Schematic.thy
- lib/Monads/wp/WPBang.thy
- lib/Monads/wp/WPFix.thy
- lib/Monads/wp/WP_Pre.thy
Use the experiment context to discard demo lemmas from the theory in the Monad session. Some of these demo lemmas confuse sledgehammer.
Fixes #827
> lib/monads: use `experiment` for demo lemmas

- proof/crefine/X64/Arch_C.thy
Updates proof after https://github.com/seL4/seL4/pull/1347
`decodeX86PortInvocation` was modified to include some explicit variable initialization to satisfy GCC.
Test with: seL4/seL4#1347
> x64 crefine: proof update after change to C

- docs/Style.thy
Adds two sections:
- Fact transformers and attributes (due to some experience with PRs this year)
- Wrapping/indenting complex rule instantiations, usually as part of `_tac` methods
- as per https://github.com/seL4/l4v/issues/746
I also added consistent double-newline before sections, and added some more emphasis on 2 being the standard indent at the start of the indentation section.
Commits are independent so can be reviewed separately. Let the bikeshedding begin.
> Style guide: _tac instantiations and attributes

- proof/crefine/AARCH64/ADT_C.thy
- proof/crefine/AARCH64/ArchMove_C.thy
- proof/crefine/AARCH64/Finalise_C.thy
- proof/crefine/AARCH64/IsolatedThreadAction.thy
- proof/crefine/AARCH64/Recycle_C.thy
- proof/crefine/Move_C.thy
- proof/refine/AARCH64/ArchInvsDefs_H.thy
- proof/refine/AARCH64/ArchInvsLemmas_H.thy
- proof/refine/AARCH64/ArchMove_R.thy
- proof/refine/AARCH64/CNodeInv_R.thy
- proof/refine/AARCH64/CSpace1_R.thy
- proof/refine/AARCH64/CSpace_R.thy
- proof/refine/AARCH64/Finalise_R.thy
- proof/refine/AARCH64/InvariantUpdates_H.thy
- proof/refine/AARCH64/IpcCancel_R.thy
- proof/refine/AARCH64/Ipc_R.thy
- proof/refine/AARCH64/KHeap_R.thy
- proof/refine/AARCH64/LevityCatch.thy
- proof/refine/AARCH64/RAB_FN.thy
- proof/refine/AARCH64/Retype_R.thy
- proof/refine/AARCH64/TcbAcc_R.thy
- proof/refine/AARCH64/Tcb_R.thy
- proof/refine/AARCH64/orphanage/Orphanage.thy
- proof/refine/InvariantsPre_H.thy
- proof/refine/Invariants_H.thy
- proof/refine/Move_R.thy
🦆🦆🦆 This PR needs feedback before I deploy anything to the other arches or move further. In an attempt to make the diff a bit more useful for reviewing than "new files added with stuff", `Invariants_H` got duplicated into each of the new files, and then clobbered by the actual file contents.
**Do not attempt to review the whole thing at once**, or the "duplicate and move Invariants_H" commit which will be squashed into once all this works.
The Refine fixup commit is not really indicative of any policies I'm aiming for in the future, it's just there so Refine builds.
The plan is: once we are OK with the way things are done, I'll expand this PR with deployment to other arches, fix up CRefine, and then we can merge it to master before continuing the arch-split train.
Invariants_H gets split …
> arch-split Refine up to Invariants_H for AARCH64 (Draft)

- proof/crefine/ARM/Ctac_lemmas_C.thy
- proof/crefine/ARM/Interrupt_C.thy
- proof/crefine/ARM/Refine_C.thy
- proof/crefine/ARM_HYP/Ctac_lemmas_C.thy
- proof/crefine/ARM_HYP/Interrupt_C.thy
- proof/crefine/ARM_HYP/Refine_C.thy
- sys-init/examples/ExampleSpecIRQ_SI.thy
- Remove remaining use of direct numeral related to `irq_len`. The lemma happened to work for `irq_len >= 8`, but not for smaller `irq_len`.
- Improve sys-init example: the example assumes an irq type of at least 8 bits. Some AArch32 boards only use 7 bit. Use smaller numbers in the example so that the example happens to work on those boards as well.
> make ARM+ARM_HYP proofs work for smaller irq_len 

- proof/invariant-abstract/ARM/ArchBCorres2_AI.thy
- proof/invariant-abstract/ARM/ArchDetSchedAux_AI.thy
- proof/invariant-abstract/ARM/ArchDetSchedDomainTime_AI.thy
- proof/invariant-abstract/ARM/ArchDetSchedSchedule_AI.thy
- proof/invariant-abstract/ARM/ArchDetype_AI.thy
- proof/invariant-abstract/ARM/ArchEmptyFail_AI.thy
- proof/invariant-abstract/ARM/ArchInterrupt_AI.thy
- proof/invariant-abstract/ARM/ArchInvariants_AI.thy
- proof/invariant-abstract/ARM/ArchKHeap_AI.thy
- proof/invariant-abstract/ARM/ArchRetype_AI.thy
- proof/invariant-abstract/ARM/ArchSchedule_AI.thy
- proof/invariant-abstract/ARM/ArchUntyped_AI.thy
- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/ARM/ArchVSpace_AI.thy
Following on from https://github.com/seL4/l4v/pull/824, this PR copies the AInvs update across to ARM for the changes to det_ext and the scheduler state.
> Update ARM AInvs for det_ext changes

- spec/abstract/AARCH64/ArchTcb_A.thy
- spec/abstract/ARM/ArchTcb_A.thy
- spec/abstract/ARM_HYP/ArchTcb_A.thy
- spec/abstract/RISCV64/ArchTcb_A.thy
- spec/abstract/Tcb_A.thy
- spec/abstract/X64/ArchTcb_A.thy
Now that domains are part of the extensible state, arch_prepare_set_domain does not need to be in the det_ext monad.
> Update explicit FPU specifications for det_ext changes

- lib/Lib.thy
- lib/Monad_Lists.thy
- lib/Monads/reader_option/Reader_Option_Monad.thy
- proof/access-control/Syscall_AC.thy
- proof/crefine/AARCH64/Retype_C.thy
- proof/crefine/ARM_HYP/Arch_C.thy
- proof/invariant-abstract/Untyped_AI.thy
These are some changes that cropped up during my work for `sorted_ipc_queues` for MCS.
I would recommend reviewing commit-by-commit, so that unrelated changes appearing in the same file can be considered individually.
> Some changes for `Lib`, December '24 edition

- lib/Heap_List.thy
- proof/refine/RISCV64/Finalise_R.thy
- proof/refine/RISCV64/IpcCancel_R.thy
- proof/refine/RISCV64/Ipc_R.thy
- proof/refine/RISCV64/SchedContextInv_R.thy
- proof/refine/RISCV64/Schedule_R.thy
- proof/refine/RISCV64/Syscall_R.thy
- proof/refine/RISCV64/TcbAcc_R.thy
> Improve reasoning for linked lists

- proof/crefine/AARCH64/ADT_C.thy
- proof/crefine/AARCH64/Arch_C.thy
- proof/crefine/AARCH64/Invoke_C.thy
- proof/crefine/AARCH64/Retype_C.thy
- proof/crefine/AARCH64/StateRelation_C.thy
- proof/crefine/AARCH64/Syscall_C.thy
- proof/crefine/AARCH64/VSpace_C.thy
- proof/crefine/AARCH64/Wellformed_C.thy
- proof/refine/AARCH64/ArchInvsDefs_H.thy
- proof/refine/AARCH64/Arch_R.thy
- proof/refine/AARCH64/InterruptAcc_R.thy
- proof/refine/AARCH64/Interrupt_R.thy
- spec/abstract/AARCH64/ArchInterrupt_A.thy
- spec/abstract/AARCH64/VCPU_A.thy
- spec/cspec/c/gen-config-thy.py
- spec/design/skel/AARCH64/ArchHypervisor_H.thy
- spec/design/skel/AARCH64/Hardware_H.thy
- spec/design/skel/AARCH64/VCPU_H.thy
- spec/haskell/src/SEL4/Machine/Hardware/AARCH64.hs
- spec/haskell/src/SEL4/Object/VCPU/AARCH64.hs
- make the option `config_ARM_GIC_V3` visible to the proofs (cherry-pick from SGI PR #733)
- adjust specs to configurable `virq` bit positions and widths
- update proofs, including:
- abstract over the value of `max_armKSGICVCPUNumListRegs` (changes with GIC version)
- adjust `virq` access proofs
- abstract over `vcpu_t` type size in C (changes with GIC version, because number of LR registers changes)
This PR enables the functional correctness proof on all remaining AArch64 platforms.
Test with: seL4/seL4#1337
> Add GIC v3 support for AArch64 platforms

- spec/haskell/src/SEL4/Machine/Hardware/RISCV64.hs
- spec/machine/RISCV64/Platform.thy
Proof update for seL4/seL4#759 -- the main visible effect is that the definition of kernelELFPAddrBase changes.
Test with: seL4/seL4#759
> riscv machine+haskell: kernelELFPAddrBase change

- proof/crefine/AARCH64/Interrupt_C.thy
- proof/crefine/AARCH64/Machine_C.thy
- proof/crefine/AARCH64/Syscall_C.thy
- proof/invariant-abstract/AARCH64/ArchBCorres2_AI.thy
- proof/invariant-abstract/AARCH64/ArchEmptyFail_AI.thy
- proof/invariant-abstract/AARCH64/ArchInterrupt_AI.thy
- proof/refine/AARCH64/Interrupt_R.thy
- spec/abstract/AARCH64/ArchInterrupt_A.thy
- spec/design/skel/AARCH64/Hardware_H.thy
- spec/haskell/src/SEL4/Machine/Hardware.lhs
- spec/haskell/src/SEL4/Machine/Hardware/AARCH64.hs
- spec/haskell/src/SEL4/Object/Interrupt/AARCH64.hs
- spec/machine/AARCH64/MachineOps.thy
Brings changes for split EOI (End Of Interrupt) mode from seL4/seL4#1183 into the verification.
Most of what changes in the seL4 pull request is underneath the machine interface and implements a different mechanism for masking/unmasking interrupts (using priority drop instead of actual masking/unmasking). For the purposes of the proof, what we want from the hardware remains the same: when deactivated, the interrupt will no longer fire.
Affects AARCH64 only.
Test with: seL4/seL4#1183
> aarch64: updates for GICv3 split EOI mode

- proof/crefine/AARCH64/Arch_C.thy
- proof/crefine/ARM_HYP/Arch_C.thy
- spec/haskell/src/SEL4/Machine/RegisterSet/AARCH64.hs
- spec/haskell/src/SEL4/Machine/RegisterSet/ARM.lhs
Mark additional registers as being saved when a VCPU is disabled
Test with seL4/seL4#1384
> arm-hyp+aarch64 haskell+crefine: fix saved-when-disabled registers

- proof/crefine/RISCV64/SchedContext_C.thy
- proof/invariant-abstract/AInvs.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/refine/RISCV64/Invariants_H.thy
- proof/refine/RISCV64/Ipc_R.thy
- proof/refine/RISCV64/KHeap_R.thy
- proof/refine/RISCV64/SchedContextInv_R.thy
- proof/refine/RISCV64/Schedule_R.thy
- proof/refine/RISCV64/Tcb_R.thy
- spec/abstract/Ipc_A.thy
- spec/abstract/Structures_A.thy
- spec/haskell/src/SEL4/API/Types/Universal.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
Please see the commit messages.
Test with https://github.com/seL4/seL4/pull/1423
> Prove `invokeSchedControl_ConfigureFlags_ccorres`

- proof/crefine/RISCV64/Ctac_lemmas_C.thy
- proof/crefine/RISCV64/IpcCancel_C.thy
- proof/crefine/RISCV64/SR_lemmas_C.thy
Requires https://github.com/seL4/seL4/pull/1358, which fixes an apparent potential bug that I discovered while working on this proof. That PR also sneaks in a few trivial changes that made verification a bit easier.
I weakened the preconditions in the still-unproven `reply_unlink_ccorres` lemma. They now correspond to those in `replyUnlinkTcb_corres`.
Edit: also requires https://github.com/seL4/seL4/pull/1297.
> Prove `cancelIPC_ccorres1`

- .github/workflows/pr.yml
- .github/workflows/push.yml
- .linkcheck-ignore.yml
Use GitHub workflow_call feature to reduce workflow duplication.
~~The central workflows in https://github.com/seL4/ci-actions/blob/master/.github/workflows/ don't support the `READ_TOKEN` bit yet, so we should hold off on merging until that is done.~~
~~I also still need to implement the ignore file format for the link checker.~~
~~Will set to non-draft when this is done.~~
Both features are implemented (https://github.com/seL4/ci-actions/pull/393 and https://github.com/seL4/ci-actions/pull/390), now ready for review.
> github: update to central workflows

- .github/workflows/proof-deploy.yml
- .github/workflows/weekly-clean.yml
The first commit adds a broader spread of platforms to CI for every merge to cover GICv3 on AARCH64 and different IRQ and other platform values for ARM.
The second commit adds all supported platforms to the weekly test. This might be too many -- I'm not sure and we should watch cost as well. Ideas welcome.
> More platform configs for CI

- proof/access-control/RISCV64/ArchAccess.thy
- proof/access-control/RISCV64/ArchArch_AC.thy
- proof/access-control/RISCV64/ArchCNode_AC.thy
- proof/access-control/RISCV64/ArchFinalise_AC.thy
- proof/access-control/RISCV64/ArchIpc_AC.thy
- proof/access-control/RISCV64/ArchRetype_AC.thy
- proof/access-control/RISCV64/ArchTcb_AC.thy
- proof/access-control/RISCV64/ExampleSystem.thy
- proof/bisim/Separation.thy
- proof/bisim/Syscall_S.thy
- proof/dpolicy/Dpolicy.thy
- proof/drefine/Arch_DR.thy
- proof/drefine/CNode_DR.thy
- proof/drefine/Finalise_DR.thy
- proof/drefine/Intent_DR.thy
- proof/drefine/Interrupt_DR.thy
- proof/drefine/Ipc_DR.thy
- proof/drefine/KHeap_DR.thy
- proof/drefine/Refine_D.thy
- proof/drefine/Schedule_DR.thy
- proof/drefine/StateTranslationProofs_DR.thy
- proof/drefine/StateTranslation_D.thy
- proof/drefine/Syscall_DR.thy
- proof/drefine/Tcb_DR.thy
- proof/drefine/Untyped_DR.thy
- spec/sep-abstract/Syscall_SA.thy
This follows on from https://github.com/seL4/l4v/pull/824 and https://github.com/seL4/l4v/pull/880. All proofs except for Infoflow should now be working.
> Update other top level proofs for det_ext changes

- .github/workflows/weekly-clean.yml
Currently the weekly tests are broken, failing on:
- artifact upload (duplicate file names for different platforms in the same architecture). Fixed in first commit.
- out of VM quota (too many concurrent tests). Fixed in second commit by reducing test load slightly.
> github: fix weekly tests

- proof/crefine/AARCH64/ADT_C.thy
- proof/crefine/AARCH64/Fastpath_Equiv.thy
- proof/crefine/AARCH64/IsolatedThreadAction.thy
- proof/crefine/AARCH64/StateRelation_C.thy
- proof/crefine/X64/ADT_C.thy
- proof/crefine/X64/IsolatedThreadAction.thy
- proof/crefine/X64/StateRelation_C.thy
- proof/refine/AARCH64/TcbAcc_R.thy
- proof/refine/X64/Ipc_R.thy
- proof/refine/X64/TcbAcc_R.thy
- spec/abstract/AARCH64/Arch_Structs_A.thy
- spec/abstract/X64/Arch_Structs_A.thy
- spec/haskell/src/SEL4/Machine/RegisterSet/AARCH64.hs
- spec/haskell/src/SEL4/Machine/RegisterSet/X64.lhs
- spec/machine/AARCH64/MachineOps.thy
- spec/machine/X64/MachineOps.thy
On architectures with FPU support, user contexts have a `user_regs` field and an `fpu_state` field. This commit renames `fpu_state` to `user_fpu_state`.
Test with https://github.com/seL4/seL4/pull/1325
> Rename fpu_state to user_fpu_state in user contexts

- proof/access-control/AARCH64/ArchArch_AC.thy
Use the generic "vmlevel" lemmas for numeral type reasoning on PT levels. This ensures that the proof also works for platforms with a different number of PT levels.
> aarch64 access: use generic numeral lemmas

- spec/cspec/Substitute.thy
The `(=)` syntax is Isabelle, not ML. It is tolerated but warned about. Use `(op =)` instead.
> cspec: remove ML warnings

- misc/regression/run_tests-bash-completion.sh
Auto-complete session names and options for the main run_tests script.
I wrote this mainly for myself, but publishing it here in case it's useful for anyone else.
The portable shell check will fail, because this is inherently bash only.
> misc: bash completion for run_tests
