seL4/l4v

- lib/WordLemmaBucket.thy
- lib/WordLib.thy
Word lemmas about casting and bitlists.
gk has the CLA.
> Mehr Lemmata ist mehr gut

- lib/Corres_UL.thy
- proof/refine/RISCV64/Untyped_R.thy
Minor commit, mostly to check github workflow.
> lib/riscv refine: move lemma

- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Schedule_R.thy
- spec/design/skel/KI_Decls_H.thy
- spec/design/skel/KernelInit_H.thy
- spec/haskell/src/Data/Helpers.hs
- spec/haskell/src/SEL4/Kernel/Init.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This solves awaken_invs' in Schedule_R.thy
> [MCS] Awaken_invs'

- proof/invariant-abstract/ARM/ArchFinalise_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/KHeap_AI.thy
- proof/refine/ARM/ArchAcc_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/Move_R.thy
- spec/abstract/IpcCancel_A.thy
trying this out...
moving this PR from bitbucket to GitHub.
> Rt blocked cancel ipc corres

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/TcbAcc_R.thy
Rebased (again) and I've addressed Corey's comments
> More ipc cancel sorries

- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/TcbAcc_R.thy
@michaelmcinerney has been working on a similar lemma, so a review from him would be helpful. Otherwise whoever has time to look at this.
> mcs: prove cancelBadgedSends_invs

- proof/crefine/RISCV64/Machine_C.thy
- proof/crefine/RISCV64/VSpace_C.thy
- proof/invariant-abstract/RISCV64/ArchAcc_AI.thy
- proof/invariant-abstract/RISCV64/ArchEmptyFail_AI.thy
- proof/invariant-abstract/RISCV64/ArchSyscall_AI.thy
- proof/invariant-abstract/RISCV64/ArchVSpace_AI.thy
- proof/refine/RISCV64/Syscall_R.thy
- proof/refine/RISCV64/VSpace_R.thy
- spec/abstract/RISCV64/ArchVSpace_A.thy
- spec/design/skel/RISCV64/Hardware_H.thy
- spec/haskell/src/SEL4/Kernel/VSpace/RISCV64.hs
- spec/haskell/src/SEL4/Machine/Hardware/RISCV64.hs
- spec/machine/RISCV64/MachineOps.thy
This updates the proofs for https://github.com/seL4/seL4/pull/231.
> riscv: rename sbadaddr -> stval

- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Reply_R.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
- spec/haskell/src/SEL4/Object/Notification.lhs
This proves `cancelAllSignals_invs'`.
I also fix up `suspend_invs'` to use the lemma Ed wrote. This removes another sorry due to duplicating that lemma statement.
I decided to lump this all into one commit, but happy to split it up if anyone would like
> prove cancelAllSignals_invs', fix suspend_invs'

- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/Ipc_AI.thy
- proof/invariant-abstract/RealTime_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- spec/abstract/KHeap_A.thy
- spec/abstract/SchedContext_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
I added a few missing reprogram timer updates to some Abstract/Haskell functions.
I also fixed a couple of minor issues which affect refinement proofs.
> Reprogram timer updates + misc fixes

- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/TcbAcc_R.thy
Work on `cancelAllIPC_invs'`, `cancel_all_invs'_helper`, and adding `replyUnlink` valid lemmas.
Sorries are fixed and first round of cleanup done. Ready for review!
> IpcCancel cancelAllIPC_invs'

- .github/workflows/proof.yml
- proof/tests.xml
- spec/haskell/Makefile
Let's see how far we can push these.
> more github CI for master branch

- proof/refine/ARM/Arch_R.thy
- proof/refine/ARM/Ipc_R.thy
This removes some sorries from Arch_R and Ipc_R. Just so we can see a little decrease in the sorry count... :)
> Arch_R and Ipc_R

- proof/refine/ARM/CNodeInv_R.thy
This fixes 4 proofs in CNodeInv_R.thy
> Four sorries in CNodeInv_R.thy

- proof/refine/ARM/Tcb_R.thy
Solve five sorries in Tcb_R.thy
> rt refine: Solve five sorries in Tcb_R.thy

- spec/haskell/src/SEL4/Object/SchedContext.lhs
prefer logic to if-then-else-False
> trivial haskell: shorten

- proof/refine/ARM/CNodeInv_R.thy
Solves three sorries in CNodeInv_R.thy.
Commit messages are currently garbage, but the changes are relatively simple so I will fix those later.
> Three sorries in CNodeInv_R.thy

- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/Tcb_R.thy
> MCS: 3 sorries in Tcb_R.thy

- proof/refine/ARM/Bits_R.thy
- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/Reply.lhs
Step 1 of 100 towards `cancelIPC_invs'`.
Edit: turned out to be step 1 of 2, and also this now includes `cancelIPC_invs'`.
> Reply_R: Prove `replyRemoveTCB_invs'`

- spec/haskell/src/SEL4/Object/Reply.lhs
> remove asserts from replyPop and replyRemoveTCB

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- spec/haskell/src/SEL4/Kernel/FaultHandler.lhs
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/Reply.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
Proved si_invs' and updated the haskell spec in a few places.
> rt haskell + refine: prove si_invs', sfi_invs_plus' and hf_invs'

- proof/refine/ARM/Tcb_R.thy
two small sorries in Tcb_R.thy
> MCS: two small sorries in Tcb_R.thy

- README.md
- misc/etc/settings
There's always something that you forget..
> readme/docs: update comments to Isabelle2020

- proof/invariant-abstract/DetSchedAux_AI.thy
- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- spec/abstract/Decode_A.thy
- spec/abstract/Ipc_A.thy
- spec/abstract/SchedContext_A.thy
- spec/abstract/Structures_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
To mirror Curtis's PR "Fix for sporadic logic", #1813 on the seL4 Bitbucket
https://bitbucket.ts.data61.csiro.au/projects/SEL4/repos/sel4/pull-requests/1813/overview
> Latest refill logic

- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/Ipc_R.thy
For whatever reason, these proofs are sensitive to the internals of `cancelIPC`, which were updated in my branch `eap/replyRemoveTCB_invs'` - hence that being the target.
These are the proofs that @MitchellBuckley and @michaelmcinerney handed off to me last week.
> rt refine: sorries in CNodeInv and Ipc

- lib/NICTATools.thy
- lib/Repeat_Attribute.thy
- proof/access-control/CNode_AC.thy
- proof/bisim/Separation.thy
- proof/bisim/Syscall_S.thy
- proof/refine/ARM/CSpace1_R.thy
- proof/refine/ARM_HYP/CSpace1_R.thy
- proof/refine/RISCV64/CSpace1_R.thy
- proof/refine/X64/CSpace1_R.thy
- spec/abstract/CSpace_A.thy
This cherry-picks two commits from the rt branch. See https://github.com/seL4/l4v/pull/122 for previous comments.
> Add REPEAT attribute and remove resolve_address_bits'.simps

- proof/refine/ARM/Tcb_R.thy
Signed-off-by: Edward Pierzchalski <ed.pierzchalski@data61.csiro.au>
> rt refine: prove decode priority corres

- .github/workflows/proof.yml
- CONTRIBUTORS.md
- ROOTS
- lib/EVTutorial/EquivValidTutorial.thy
- lib/EVTutorial/ROOT
- lib/EVTutorial/document/root.bib
- lib/EVTutorial/document/root.tex
- lib/EquivValid.thy
- lib/tests.xml
Thanks to Toby Murray (@tobycmurray) for early feedback.
Signed-off-by: Robert Sison <robert.sison@unimelb.edu.au>
> lib: A tutorial and some 'modify' monad rules for Lib.EquivValid

- proof/refine/ARM/StateRelation.thy
> rt refine: add missing sc_replies_relation in state_relationD/E

- README.md
- proof/access-control/README.md
- proof/asmrefine/README.md
- proof/capDL-api/README.md
- proof/crefine/README.md
- proof/drefine/README.md
- proof/infoflow/README.md
- proof/invariant-abstract/README.md
- proof/refine/README.md
- proof/sep-capDL/README.md
- sys-init/README.md
- tools/README.md
- tools/asmrefine/README.md
This is a cherry-pick of ba38ae33ab1e6f920d0ff0fcaa774a3ce0a29ff4 from the master branch to `rt` to stop the CI failing on those nicta.com.au links.
> update publications links

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
I updated `schedContextDonate` to align with the Abstract and C specs. I then proved `schedContextDonate_corres`.
> Prove schedContextDonate_corres

- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/IpcCancel_A.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/Notification.lhs
A couple of changes to the abstract and Haskell specs + proofs for `setP_invs'` and `sp_corres`
> Prove setP_invs' and sp_corres

- proof/refine/ARM/Reply_R.thy
> rt refine: resurrect some crunches for updateReply

- lib/Heap_List.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/TcbAcc_R.thy
Collecting small PRs here for merging. I'll retarget #173 to this.
> rt refine: combine #174 and #171

- spec/haskell/src/SEL4/Object/CNode.lhs
This should have been part of #182, but I somehow managed to drop the commit.
> rt haskell: revert accidental edit

- proof/invariant-abstract/ARM/ArchCNodeInv_AI.thy
- proof/invariant-abstract/ARM/ArchFinalise_AI.thy
- proof/invariant-abstract/ARM/ArchTcb_AI.thy
- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Finalise_AI.thy
- proof/invariant-abstract/IpcCancel_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/Ipc_AI.thy
- proof/invariant-abstract/KHeap_AI.thy
- proof/invariant-abstract/RISCV64/ArchCNodeInv_AI.thy
- proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
- proof/invariant-abstract/RISCV64/ArchTcb_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- spec/abstract/CSpace_A.thy
- spec/abstract/Ipc_A.thy
The most significant change is updating `fast_finalise` to not handle the `SchedContextCap` case.
> rt: several minor updates to aspec and ainvs

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/Syscall_AI.thy
- spec/abstract/Ipc_A.thy
Remove an assertion from send_ipc (ASpec)
> Remove send_ipc assertion

- proof/refine/ARM/Tcb_R.thy
Signed-off-by: Michael McInerney <Michael.McInerney@data61.csiro.au>
> Small decode sorries

- proof/refine/ARM/PageTableDuplicates.thy
Signed-off-by: Michael McInerney <Michael.McInerney@data61.csiro.au>
> Simple page table duplicate sorries

- lib/Corres_UL.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/refine/ARM/CSpace_I.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/Decode_A.thy
- spec/abstract/Invocations_A.thy
- spec/abstract/Schedule_A.thy
- spec/haskell/src/SEL4/Object/TCB.lhs
See the commit messages for a quick rundown of what's here
> decodeSchedContext lemmas

- proof/invariant-abstract/Tcb_AI.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/Decode_A.thy
- spec/haskell/src/SEL4/Object/TCB.lhs
This should bring the Haskell in line with the abstract and C. It would be great if someone could closely check the Haskell to make sure it's OK, but given that the corres rules are working, I'm fairly sure it's fine
> More decode sorries

- proof/invariant-abstract/IpcDet_AI.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/haskell/src/SEL4/Object/Endpoint.lhs
- spec/haskell/src/SEL4/Object/Notification.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
Moved around some lemmas to make the proofs work. Additionally, found an unneeded lemma in AInvs to do with `sort_queue`.
> Prove sai_invs', rai_invs' and ri_invs'

- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- KHeap_R: cleaned up get_reply_valid_reply', etc.
- Reply_R, Ipc_R: some cleanup around replyPush, removing
redundant assumptions, etc.
> rt refine: some cleanup

- proof/refine/ARM/Refine.thy
- proof/refine/Move_R.thy
Some of the small added lemmas should probably be moved. Either to AInvs, or to move.thy.
> four small sorries in Refine_R.thy

- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
* `setDomain_corres` is proved and renamed
* Two wp lemmas about `rescheduleRequired` are deleted.
* A third `rescheduleRequired` lemma is trivial when two stronger sub-lemmas are used.
> 4 small sorries in Syscall_R.thy

- README.md
- proof/access-control/Dpolicy.thy
- proof/access-control/README.md
- proof/asmrefine/README.md
- proof/capDL-api/README.md
- proof/crefine/README.md
- proof/drefine/README.md
- proof/infoflow/README.md
- proof/invariant-abstract/README.md
- proof/refine/README.md
- proof/sep-capDL/README.md
- sys-init/README.md
- tools/README.md
- tools/asmrefine/README.md
This just cherry-picks two commits from master that should fix the links test.
> rt: fix links to papers

- misc/testboard/README.md
- misc/testboard/testboardpush
This cherry-picks Gerwin's commits for the `testboardpush` script
> testboardpush for rt

- lib/Monad_WP/NonDetMonadVCG.thy
- proof/refine/ARM/ADT_H.thy
- proof/refine/ARM/ArchAcc_R.thy
- proof/refine/ARM/Arch_R.thy
- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/CSpace_R.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/InterruptAcc_R.thy
- proof/refine/ARM/Interrupt_R.thy
- proof/refine/ARM/InvariantUpdates_H.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Machine_R.thy
- proof/refine/ARM/Refine.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/ARM/Untyped_R.thy
- proof/refine/ARM/VSpace_R.thy
- spec/haskell/src/SEL4/Object/Reply.lhs
This is a rebased and slightly updated version of Victor's previous PR. 
I probably should have just added some new commits, rather than squashing, to make reviewing easier. Sorry. The only significant change is in the commit that says "replyPop lemmas", and there, the only significant change is the addition of the proof of `replyPop_iflive`, though there were some small changes due to the latest spec change to `replyPop`.
> Michaelm reply pop lemmas

- spec/cspec/c/kernel.mk
This one is relevant for MacOs
Signed-off-by: Gerwin Klein <kleing@unsw.edu.au>
> yet another TOOLPREFIX for riscv toolchain

- lib/Monad_WP/NonDetMonadVCG.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/Move_R.thy
Solved 5 smallish sorries in `Syscall_R`
> rt refine: 5 sorries in `Syscall_R`

- proof/refine/ARM/Finalise_R.thy
This was pretty straightforward now that the `replyPop` and `replyRemove` invs lemmas have been proved.
> rt refine: prove replyClear_invs'

- docs/README.md
- docs/arch-split.md
- docs/compacting-proofs.md
- docs/de-duplicating-proofs.md
- docs/find-consts.md
- docs/find-theorems.md
* Matt's short guide on compacting proofs
* Matt's guide on deduplication
* Matt's and Joel's guide on arch split
* Japheth's guide on find_consts
* Japheth's guide on find_theorems
> Some Isabelle guides

- docs/README.md
- docs/plans/README.md
- docs/plans/other_ideas.md
- docs/plans/smaller_tasks.md
- docs/plans/the-matrix.md
added some more formatting and included the things that can be made public
> Add list of proof engineering ideas

- proof/crefine/RISCV64/Delete_C.thy
- proof/crefine/X64/Delete_C.thy
- proof/crefine/X64/SyscallArgs_C.thy
Closes [VER-748]
[VER-748]: https://sel4.atlassian.net/browse/VER-748
> Remove remaining tab characters in .thy files

- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/Move_R.thy
- spec/haskell/src/SEL4/Object/Endpoint.lhs
Updated the Haskell for `receiveIPC` and solved `receiveIPC_corres`.
Depends on a single sorry from another PR.
> receiveIPC_corres

- lib/Heap_List.thy
- proof/refine/ARM/ArchAcc_R.thy
- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/CSpace_R.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/InterruptAcc_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/ARM/Untyped_R.thy
- spec/haskell/src/SEL4/Object/Reply.lhs
This removes one sorry in `Invariants_H.thy` by adding the `valid_replies'` invariants to `invs'`. This means that we now need to prove that it is preserved instead of just getting to assume that it holds.
> rt: prove valid_replies'

- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/InterruptAcc_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/Move_R.thy
- spec/haskell/src/SEL4/Kernel/Thread.lhs
This solves `doReplyTransfer_corres` while strengthening a few related lemmas.
The spec did need some updating, but I don't there are many significant pieces of work here outside the main resolved sorry.
> doReplyTransfer_corres

- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
As title describes. Nothing very fancy here.
> PageTableDuplicates (2 sorries)

- docs/README.md
Hook @zaklogician's MD file into the table of contents
> docs: hook in new Haskell assertions doc

- spec/haskell/src/SEL4/Object/SchedContext.lhs
> rt haskell: fix a bug in mergeRefills

- lib/ExtraCorres.thy
- proof/refine/ARM/Schedule_R.thy
Improvements to corres_whileLoop
> Improvements to corres_whileLoop

- ROOTS
- docs/Makefile
- docs/ROOT
- docs/Style.thy
- docs/Style_pre.thy
- docs/tests.xml
I've drafted up a short style guide that is intended as a starting point for a more complete and rigorous guide which can be developed over time. I hope that the rules/examples in this version are correct.
I suggest:
1. Review and corrections of this limited guide up to a point where it is readable and accurate.
2. Merge.
3. Improvements, more details, and new sections can be proposed through pull-requests and go through the usual review process. 
In this way we can democratise the process somewhat, and also distribute the work-load across all interested parties.
> Initial style guide

- .github/workflows/trigger.yml
This action triggers docker container deployment in the repo [seL4/ci-actions](https://github.com/seL4/ci-actions) when the C parser changes here.
> auto-deploy CParser docker container

- lib/Crunch_Test_NonDet.thy
- lib/crunch-cmd.ML
Cherry-pick https://github.com/seL4/l4v/pull/301.
> rt: support crunching lifted monadic functions

- lib/Monad_WP/OptionMonad.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
> rename opt_map_left_Some to opt_map_red

- misc/regression/run_tests.py
- run_tests
This pulls in 3 commits from master to make the Github logs nicer to read (esp once the test has finished).
> cherry-picking nicer log commits

- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/DetSchedDomainTime_AI.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/IpcDet_AI.thy
- proof/invariant-abstract/KHeap_AI.thy
- proof/invariant-abstract/RISCV64/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/ADT_H.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/Syscall_R.thy
- spec/abstract/Decode_A.thy
- spec/abstract/Invocations_A.thy
- spec/abstract/Ipc_A.thy
- spec/abstract/Structures_A.thy
- spec/abstract/Syscall_A.thy
- spec/design/skel/ObjectInstances_H.thy
- spec/haskell/src/SEL4/API/Invocation.lhs
- spec/haskell/src/SEL4/API/InvocationLabels.lhs
- spec/haskell/src/SEL4/API/Types/Universal.lhs
- spec/haskell/src/SEL4/Object/Instances.lhs
- spec/haskell/src/SEL4/Object/ObjectType.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/Structures.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
this adds `scSporadic` as a new field of `sched_context` which will be set via `invokeSchedControl_ConfigureFlags` (which was previously called `invokeSchedControl_Configure`)
> add Sporadic flags

- lib/Monad_WP/OptionMonad.thy
A small addition to OptionMonad, a few lemmas for controlling `opt_map` and `opt_pred`. `opt_predD` has been useful for me.
> add opt_predD and other opt_map/opt_pred lemmas

- misc/bump/README.md
Remove old mention of Bamboo and fix a typo.
> trivial: misc/bump/README update

- proof/invariant-abstract/CSpace_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Deterministic_AI.thy
- proof/refine/ARM/InterruptAcc_R.thy
- proof/refine/ARM/PageTableDuplicates.thy
- proof/refine/ARM/Refine.thy
- spec/abstract/KHeap_A.thy
- spec/abstract/Syscall_A.thy
- spec/haskell/src/SEL4.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
This perfoms a spec update in alignment with the following C commit
https://github.com/seL4/seL4/commit/9663e1e6f5552b8b6eb3cb929e68465b26b79643
and updates the proofs
> Unconditional call to `update_time_stamp`

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- spec/abstract/Syscall_A.thy
- spec/haskell/src/SEL4/Object/TCB.lhs
This updates this spec in alignment with the following C commit
https://github.com/seL4/seL4/commit/bbd3f5ab17d712e8e9b124e77d2b5f83fd71f2a4
and updates the proofs
> Clear consumed time

- proof/invariant-abstract/DetSchedAux_AI.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/Syscall_R.thy
- spec/abstract/Schedule_A.thy
This is a PR containing several bite-size cleanup/improvement/addition to DetSched files.
It would be easier to review commit-by-commit.
> DetSched* misc updates

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- spec/abstract/SchedContext_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/machine/MachineExports.thy
This brings the guard in `refill_budget_check` in line with the C: see
https://github.com/seL4/seL4/blob/master/src/kernel/sporadic.c#L284
> refill_budget_check guard

- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/Tcb_R.thy
Trying to avoid having `invs`/`invs’` where possible, but also trying not to touch the IPC related functions.
What is in this PR is mostly around `schedContextResume`.
Signed-off-by: Miki Tanaka <miki.tanaka@unsw.edu.au>
> rt refine: weaken invs/invs' preconditions for schedContextResume_corres, etc.

- docs/haskell-assertions.md
- proof/refine/ARM/KHeap_R.thy
This collects all the `add_xxx` methods at the end of `KHeap_R.thy`.
I cherry-picked the commit from `master` that added the `haskell-assertions.md` file, and added a section about our use of cross lemma and asserts, and some details on implementing this. Hopefully this is OK as far as the merge goes. And I'm not too clear on the details of the `skel` files, so let me know if that can be improved.
> Collect `add` methods and add cross lemma and assert documentation

- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/SchedContext_R.thy
Please see the short description in the commit message
> `refillNew_invs'` and `refillUpdate_invs'`

- lib/crunch-cmd.ML
This cherry-picks this commit into the rt branch.
> Notify if crunch generates side-conditions

- lib/Corres_UL.thy
- proof/invariant-abstract/AInvs.thy
- proof/invariant-abstract/ARM/ArchVSpaceEntries_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/Finalise_R.thy
- proof/refine/ARM/InvariantUpdates_H.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/Ipc_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/SchedContextInv_R.thy
- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
- proof/refine/ARM/Tcb_R.thy
- spec/abstract/Ipc_A.thy
- spec/haskell/src/SEL4/Object/SchedContext.lhs
The first commit in the branch was cherry-picked from the `call_kernel` lemmas PR
> `invokeSchedControlConfigureFlags_corres`

- proof/refine/ARM/SchedContext_R.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/TcbAcc_R.thy
Signed-off-by: Michael McInerney <m.mcinerney@unsw.edu.au>
> `performInv_invs`

- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Syscall_R.thy
- spec/abstract/Ipc_A.thy
- spec/haskell/src/SEL4/API/Syscall.lhs
- spec/haskell/src/SEL4/Kernel/Thread.lhs
This PR proves handleYield_corres.
Also includes:
- corres rules for endTimeslice, chargeBudget, etc.
- some spec updates for abstract and design specs
> handleYield_corres

- lib/Monad_WP/NonDetMonadVCG.thy
- proof/invariant-abstract/AInvs.thy
- proof/invariant-abstract/ARM/ArchDetSchedSchedule_AI.thy
- proof/invariant-abstract/DetSchedAux_AI.thy
- proof/invariant-abstract/DetSchedInvs_AI.thy
- proof/invariant-abstract/DetSchedSchedule_AI.thy
- proof/invariant-abstract/Invariants_AI.thy
- proof/invariant-abstract/Ipc_AI.thy
- proof/invariant-abstract/RISCV64/ArchDetSchedSchedule_AI.thy
- proof/invariant-abstract/SchedContextInv_AI.thy
- proof/invariant-abstract/SchedContext_AI.thy
- proof/refine/ARM/Bits_R.thy
- proof/refine/ARM/CNodeInv_R.thy
- proof/refine/ARM/CSpace1_R.thy
- proof/refine/ARM/CSpace_R.thy
- proof/refine/ARM/Init_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM/StateRelation.thy
- proof/refine/ARM/Syscall_R.thy
- proof/refine/ARM/Untyped_R.thy
- spec/abstract/Ipc_A.thy
- spec/abstract/SchedContext_A.thy
- spec/design/skel/KernelInit_H.thy
- spec/design/skel/KernelStateData_H.thy
- spec/haskell/src/SEL4/Model/StateData.lhs
- spec/haskell/src/SEL4/Object/SchedContext.lhs
- spec/haskell/src/SEL4/Object/TCB.lhs
Anna mentioned in https://github.com/seL4/seL4/issues/684 the idea that the idle sc could have infinite budget, and so would always be ready and sufficient. I did try this out, but it was quite difficult to get things working, and I have abandoned this idea for now. Perhaps we can go with the approach in this PR now, and reconsider this infinite budget idea later down the track
> Do not charge the idle sc

- proof/refine/ARM/EmptyFail_H.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM/Refine.thy
- proof/refine/ARM/Syscall_R.thy
- spec/design/skel/KernelStateData_H.thy
- spec/haskell/src/SEL4.lhs
- spec/haskell/src/SEL4/Model/StateData.lhs
This PR removes all the remaining sorries in Refine.
> fix sorries in Refine.thy

- lib/Corres_UL.thy
- lib/Monad_WP/OptionMonad.thy
- proof/refine/ARM/IpcCancel_R.thy
- proof/refine/ARM/KHeap_R.thy
- proof/refine/ARM/Reply_R.thy
- proof/refine/RISCV64/ArchMove_R.thy
- proof/refine/RISCV64/Bits_R.thy
- proof/refine/RISCV64/Corres.thy
- proof/refine/RISCV64/EmptyFail.thy
- proof/refine/RISCV64/InvariantUpdates_H.thy
- proof/refine/RISCV64/Invariants_H.thy
- proof/refine/RISCV64/KHeap_R.thy
- proof/refine/RISCV64/LevityCatch.thy
- proof/refine/RISCV64/Machine_R.thy
- proof/refine/RISCV64/StateRelation.thy
- spec/haskell/src/SEL4/API/Types/Universal.lhs
This contains some work for RISCV MCS Refine. I have completed all files in the Refine session up to and including `KHeap_R.thy`, and it would be good to carefully check these (in particular, `Invariants_H.thy` and `StateRelation.thy` as well as `KHeap_R.thy`). The changes in the files after are just from the patch.
> RISCV MCS Refine

- proof/infoflow/timeprotection/MemSysExample_Generic32Bit_A.thy
- proof/infoflow/timeprotection/TimeProtection.thy
Have our abstraction of the microarchitecture support making the necessary distinction between virtual and physical addresses. Includes a basic test instantiation.
> Page table abstraction for experimental-timeprot

- .github/workflows/pr.yml
- .github/workflows/push.yml
These allow the test to run on private repos. If set to empty, they have no effect.
> github: provide auth tokens

- proof/asmrefine/export/SEL4SimplExport.thy
- spec/cspec/ARM/Kernel_C.thy
- spec/cspec/ARM_HYP/Kernel_C.thy
- spec/cspec/RISCV64/Kernel_C.thy
- spec/cspec/X64/Kernel_C.thy
- tools/asmrefine/SimplExport.thy
- tools/asmrefine/testfiles/global_array_swap_gref.thy
- tools/asmrefine/testfiles/global_asm_stmt_gref.thy
- tools/asmrefine/testfiles/inf_loop_gref.thy
@mbrcknl : hoping this doesn't break other BV efforts
Needs full regression test to make sure I didn't derp anything else.
> asmrefine pfx (prefix for finding constants via name) + Kernel_C tweaks

- .github/workflows/trigger.yml
> trivial: fix typo

- lib/HaskellLib_H.thy
- lib/Monad_WP/OptionMonad.thy
- lib/Monad_WP/OptionMonadND.thy
This should bring `master` fully up to date with all OptionMonad improvements from the MCS work.
There are further `lib/` changes which we might want to add to `master`, but those are probably better done in separate PRs.
> cherry pick OptionMonad updates from rt branch

- tools/c-parser/standalone-parser/main.sml
In order to compare ASTs for appearance/disappearance/modification of
declarations, it is easier to have the annotations obvious to any
external tool for ease of parsing.
Annotations take the form:
"##<decl_type>: <name>", e.g. "##Function: ctzl"
Signed-off-by: Rafal Kolanski <rafal.kolanski@proofcraft.systems>
> cparser: annotate AST printing for top-level decls

- lib/Corres_UL.thy
- lib/MonadicRewrite.thy
- proof/crefine/ARM/CSpace_RAB_C.thy
- proof/crefine/ARM/Fastpath_Equiv.thy
- proof/crefine/ARM/Ipc_C.thy
- proof/crefine/ARM_HYP/CSpace_RAB_C.thy
- proof/crefine/ARM_HYP/Fastpath_Equiv.thy
- proof/crefine/ARM_HYP/Ipc_C.thy
- proof/crefine/ARM_HYP/IsolatedThreadAction.thy
- proof/crefine/Move_C.thy
- proof/crefine/RISCV64/CSpace_RAB_C.thy
- proof/crefine/RISCV64/Ipc_C.thy
- proof/crefine/RISCV64/IsolatedThreadAction.thy
- proof/crefine/X64/CSpace_RAB_C.thy
- proof/crefine/X64/Ipc_C.thy
- proof/crefine/X64/IsolatedThreadAction.thy
- proof/drefine/Finalise_DR.thy
- proof/drefine/Ipc_DR.thy
- proof/drefine/Untyped_DR.thy
- proof/infoflow/Ipc_IF.thy
- proof/invariant-abstract/Untyped_AI.thy
Next step will be trying to wrap my head around how these lemmas are supposed to be used in practice and maybe adding some documentation on the approach in general.
I'm mainly looking for feedback on:
* style/sections/etc
* names of things (I did not rename in this set of patches)
* derps
* future ideas (I have some, but the more the merrier)
> Monadic rewrite cleanup

- proof/crefine/RISCV64/StateRelation_C.thy
- proof/crefine/RISCV64/Wellformed_C.thy
- spec/abstract/Structures_A.thy
- spec/cspec/RISCV64/Kernel_C.thy
This updates `cstate_relation`, and fixes breakages in `Wellformed_C.thy`.
> `cstate_relation`

- docs/setup.md
Instructions mainly for macOS, and a small update for Python
> Setup instructions

- proof/crefine/RISCV64/CSpace_C.thy
- proof/crefine/RISCV64/PSpace_C.thy
- proof/crefine/RISCV64/SR_lemmas_C.thy
- proof/crefine/RISCV64/TcbAcc_C.thy
- proof/crefine/RISCV64/TcbQueue_C.thy
This adds one (subgoal) sorry and gets everything else at least working until the end of `TcbQueue_C.thy`.
> Sorry till end of `TcbQueue_C.thy`

- lib/Eisbach_Methods.thy
These allow for pattern-matching on the conclusion and reacting to whether the match succeeded.
> lib: add if_then_else, has_concl, case_concl Eisbach_Methods

- lib/Eisbach_Methods.thy
fwd_all and ALLGOALS_FWD act like `all`, but supplied method is applied to goals in first-to-last order, taking into account goals solved and generated.
fwd_all_new and FWD_ALL_NEW act like `;` and THEN_ALL_NEW, but with the second method is applied to the results of the first in the order they were produced, making it safe for WP reasoning.
Note: had to drop the WP rule tests as they don't work in Eisbach_Methods
> lib: add fwd_all + fwd_all_new methods, combinators

- .github/workflows/trigger.yml
(token is about to be deleted)
> github: replace obsolete access token

- docs/Style.thy
This is my stab at writing down the result of the discussions of the recent past and the hopeful resulting consensus.
> docs: proof style on using `by`

- lib/Basics/README.md
- lib/Eisbach_Tools/README.md
- lib/ML_Utils/README.md
- lib/Monads/README.md
In particular for:
- Basics
- ML_Utils
- Eisbach_Tools
- Monads
> README files for the new sessions 

- proof/Makefile
- proof/invariant-abstract/AARCH64/ArchADT_AI.thy
- proof/invariant-abstract/AARCH64/ArchAInvsPre.thy
- proof/invariant-abstract/AARCH64/ArchAcc_AI.thy
- proof/invariant-abstract/AARCH64/ArchArch_AI.thy
- proof/invariant-abstract/AARCH64/ArchCNodeInv_AI.thy
- proof/invariant-abstract/AARCH64/ArchDetSchedDomainTime_AI.thy
- proof/invariant-abstract/AARCH64/ArchDetSchedSchedule_AI.thy
- proof/invariant-abstract/AARCH64/ArchDeterministic_AI.thy
- proof/invariant-abstract/AARCH64/ArchDetype_AI.thy
- proof/invariant-abstract/AARCH64/ArchFinalise_AI.thy
- proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
- proof/invariant-abstract/AARCH64/ArchKernelInit_AI.thy
- proof/invariant-abstract/AARCH64/ArchRetype_AI.thy
- proof/invariant-abstract/AARCH64/ArchSyscall_AI.thy
- proof/invariant-abstract/AARCH64/ArchVCPU_AI.thy
- proof/invariant-abstract/AARCH64/ArchVSpace_AI.thy
- spec/abstract/AARCH64/ArchDecode_A.thy
- spec/abstract/AARCH64/Init_A.thy
- spec/abstract/AARCH64/VCPUAcc_A.thy
- spec/haskell/src/SEL4/Machine/Hardware/AARCH64.hs
- spec/machine/AARCH64/MachineOps.thy
- spec/machine/AARCH64/Platform.thy
Finished AInvs proof and switches off `quick_and_dirty` setting for proper proof checking.
Still plenty of FIXMEs open, which will be addressed in a separate PR.
> finish AArch64 abstract invariants

- lib/EmptyFailLib.thy
- lib/ExtraCorres.thy
- lib/HaskellLib_H.thy
- lib/Monad_Commute.thy
- lib/Monad_Lists.thy
- lib/Monads/More_NonDetMonadVCG.thy
- lib/Monads/NonDetMonad.thy
- lib/Monads/NonDetMonadVCG.thy
- lib/Monads/OptionMonad.thy
- lib/Monads/WhileLoopRules.thy
- lib/clib/CCorresLemmas.thy
- lib/clib/Corres_UL_C.thy
- lib/test/Crunch_Test_NonDet.thy
- proof/refine/ARM/Schedule_R.thy
- proof/refine/ARM_HYP/Schedule_R.thy
- proof/refine/RISCV64/Schedule_R.thy
- proof/refine/X64/Schedule_R.thy
This adds definitions and lemmas that were added to the `rt` branch, including many things related to while loops at both Refine and CRefine levels
> Stuff from `rt`

- .github/workflows/proof.yml
Switches on L4V_FEATURES=MCS for MCS builds.
> github: build with MCS feature

- proof/access-control/Tcb_AC.thy
- proof/invariant-abstract/Tcb_AI.thy
- proof/refine/ARM/Tcb_R.thy
- proof/refine/ARM_HYP/Tcb_R.thy
- proof/refine/RISCV64/Tcb_R.thy
- proof/refine/X64/Tcb_R.thy
- spec/abstract/Invocations_A.thy
Cherry-pick https://github.com/seL4/l4v/pull/572 into rt, updated as required.
> MCS: remove is_thread_control and thread_control_target 

- proof/invariant-abstract/AARCH64/ArchInvariants_AI.thy
- proof/invariant-abstract/AARCH64/ArchVSpace_AI.thy
Both of these affect other architectures and need more discussion.
Converted into issues #599 and #600.
> aarch64 ainvs: convert 2 FIXMEs into longer term issues

- lib/Monads/Monad_Equations.thy
- lib/clib/Corres_UL_C.thy
- proof/refine/ARM/Retype_R.thy
- proof/refine/ARM_HYP/Retype_R.thy
- proof/refine/RISCV64/Retype_R.thy
- proof/refine/X64/Retype_R.thy
This also improves the style of this lemma
> Rename `bind_assoc_reverse` to `bind_assoc_return_reverse`

- lib/clib/MonadicRewrite_C.thy
This makes the flags schematic
> clib: generalise `monadic_rewrite_ccorres_assemble`

- proof/crefine/RISCV64/ArchMove_C.thy
- proof/refine/ARM/Detype_R.thy
- proof/refine/ARM/Invariants_H.thy
- proof/refine/ARM_HYP/Detype_R.thy
- proof/refine/ARM_HYP/Invariants_H.thy
- proof/refine/RISCV64/Detype_R.thy
- proof/refine/RISCV64/Invariants_H.thy
- proof/refine/X64/Detype_R.thy
- proof/refine/X64/Invariants_H.thy
This also moves several lemmas required for obj_range'_disjoint to Invariants_H
> refine: add obj_range'_disjoint

- lib/Monads/NonDetMonadVCG.thy
- lib/Monads/OptionMonadWP.thy
- lib/Monads/WhileLoopRules.thy
This pulls in changes made to `Monads` on the `rt` branch, in preparation for further refactoring.
> monads: synchronise with rt branch

- lib/Monads/Fun_Pred_Syntax.thy
- lib/Monads/ROOT
- lib/Monads/Strengthen.thy
- lib/Monads/Strengthen_Demo.thy
- lib/Monads/document/root.tex
- lib/Monads/nondet/Nondet_Empty_Fail.thy
- lib/Monads/nondet/Nondet_No_Throw.thy
- lib/Monads/nondet/Nondet_Total.thy
- lib/Monads/nondet/Nondet_VCG.thy
- lib/Monads/nondet/Nondet_While_Loop_Rules.thy
- lib/Monads/reader_option/Reader_Option_Monad.thy
- lib/Monads/trace/Trace_Empty_Fail.thy
- lib/Monads/trace/Trace_Monad.thy
- lib/Monads/trace/Trace_Monad_Equations.thy
- lib/Monads/trace/Trace_No_Fail.thy
- lib/Monads/trace/Trace_No_Throw.thy
- lib/Monads/trace/Trace_RG.thy
- lib/Monads/trace/Trace_Total.thy
- lib/Monads/trace/Trace_VCG.thy
- lib/Monads/wp/Datatype_Schematic.thy
- lib/Monads/wp/Eisbach_WP.thy
- lib/Monads/wp/WP.thy
- lib/Monads/wp/WPI.thy
- lib/Monads/wp/WP_Pre.thy
- add document setup in preparation for AFP entry
- consequently clean up structure and document issues
> document setup for Monad Lib

- lib/clib/CCorresLemmas.thy
- lib/clib/Corres_UL_C.thy
- lib/clib/SIMPL_Lemmas.thy
- proof/crefine/ARM_HYP/Retype_C.thy
- proof/crefine/RISCV64/Retype_C.thy
- proof/crefine/X64/Retype_C.thy
This updates `ccorres_While` and `ccorres_call_getter_setter` to be more useful, adding and moving a few other things along the way
> Some rules for CLib

- .github/workflows/proof-deploy.yml
Documents the GitHub workflow chain for automated platform branch rebasing.
> github: docs for platform branch rebase workflow

- lib/clib/CCorresLemmas.thy
Cherry-picks a commit from `master`
> `ccorres_While` on `rt`

- .github/workflows/aarch64.yml
- .github/workflows/external.yml
- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
- .github/workflows/trigger.yml
- .github/workflows/weekly-clean.yml
- enable AWS cache configuration per repo
- bump action versions to node20
> GitHub workflow updates

- .github/workflows/proof-deploy.yml
This is to get a green badge for the rebase job on the master branch and to confirm that things are in sync after everything has completed.
Needs to be merged after #803
> github: re-trigger platform branch rebase on master

- .github/workflows/proof-deploy.yml
- .github/workflows/proof.yml
- fix concurrency group syntax (needs a group entry)
- cancel started runs
> github: fix concurrency group syntax

- proof/invariant-abstract/AARCH64/ArchArch_AI.thy
- proof/invariant-abstract/AARCH64/ArchDetSchedSchedule_AI.thy
- proof/invariant-abstract/AARCH64/ArchFinalise_AI.thy
- proof/invariant-abstract/AARCH64/ArchTcbAcc_AI.thy
- proof/invariant-abstract/ARM/ArchTcbAcc_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchArch_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchDetSchedSchedule_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchFinalise_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchTcbAcc_AI.thy
- proof/invariant-abstract/ARM_HYP/ArchVSpace_AI.thy
- proof/invariant-abstract/KHeapPre_AI.thy
- proof/invariant-abstract/RISCV64/ArchFinalise_AI.thy
- proof/invariant-abstract/RISCV64/ArchTcbAcc_AI.thy
- proof/invariant-abstract/TcbAcc_AI.thy
- proof/invariant-abstract/X64/ArchTcbAcc_AI.thy
Move earlier and make generic where possible.
> Refactor arch_thread_get/set lemmas
